title: SystemCraft
description: High-Level System Design notes for tech interviews
url: "https://systemcraft.in"
baseurl: ""
theme: jekyll-theme-midnight
markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
