title: SystemCraft
description: High-Level System Design notes for tech interviews
url: "https://systemcraft.in"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

plugins:
  - jekyll-seo-tag
