const { T, randInt, randArr, ln } = require('./gen.js');

function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function ED(o) {
  var h = '';
  if (o.intuition) h += '<h3>Intuition</h3>' + (Array.isArray(o.intuition) ? o.intuition.map(function (p) { return '<p>' + p + '</p>'; }).join('') : '<p>' + o.intuition + '</p>');
  if (o.approach) h += '<h3>Approach</h3><ol>' + o.approach.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ol>';
  if (o.walkthrough) h += '<h3>Walkthrough</h3><pre><code>' + esc(o.walkthrough) + '</code></pre>';
  if (o.code) h += '<h3>Solution</h3><pre><code>' + esc(o.code) + '</code></pre>';
  h += '<h3>Complexity</h3><ul><li><b>Time — ' + o.time + ':</b> ' + o.timeWhy + '</li><li><b>Space — ' + o.space + ':</b> ' + o.spaceWhy + '</li></ul>';
  if (o.pitfalls) h += '<h3>Common Pitfalls</h3><ul>' + o.pitfalls.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ul>';
  return h;
}
function shuffle(a) { for (var i = a.length - 1; i > 0; i--) { var j = randInt(0, i); var t = a[i]; a[i] = a[j]; a[j] = t; } return a; }

const MORE3 = [];

MORE3.push({ slug: 'longest-consecutive-sequence', title: 'Longest Consecutive Sequence', difficulty: 'medium', topics: ['Array', 'Hash Table', 'Union Find'], type: 'ARR_INT', langsrc: T.ARR_INT('longestConsecutive'),
  desc: '<p>Given an unsorted array <code>nums</code>, return the length of the longest run of consecutive integers. You must do it in O(n) time.</p>',
  examples: [{ in: 'nums = [100,4,200,1,3,2]', out: '4', ex: 'The run [1,2,3,4] has length 4.' }, { in: 'nums = [0,3,7,2,5,8,4,6,0,1]', out: '9' }],
  constraints: ['0 &lt;= nums.length &lt;= 10^5', '-10^9 &lt;= nums[i] &lt;= 10^9'],
  editorial: ED({ intuition: ['Sorting would be O(n log n). To hit O(n), drop everything into a hash set for O(1) membership.', 'The trick is to only start counting a run from its <em>smallest</em> element — a number <code>x</code> where <code>x-1</code> is not in the set. That guarantees each element is walked at most once.'], approach: ['Put all numbers in a set.', 'For each number that has no predecessor (<code>x-1</code> not in set), walk <code>x, x+1, x+2, ...</code> counting the run.', 'Track the longest run seen.'], walkthrough: 'nums = [100,4,200,1,3,2]  set={1,2,3,4,100,200}\nstart at 1 (0 not in set): 1,2,3,4 -> len 4\nstart at 100: 100 -> len 1\nstart at 200: 200 -> len 1\nanswer 4', code: 'def longestConsecutive(nums):\n    s = set(nums)\n    best = 0\n    for x in s:\n        if x - 1 not in s:\n            y = x\n            while y + 1 in s:\n                y += 1\n            best = max(best, y - x + 1)\n    return best', time: 'O(n)', timeWhy: 'each number is visited once as part of exactly one run.', space: 'O(n)', spaceWhy: 'the hash set holds all numbers.', pitfalls: ['Only start a walk at run-starts, or you re-scan runs and degrade to O(n\u00b2).'] }),
  gen: function () { var o = [[[100, 4, 200, 1, 3, 2]], [[0, 3, 7, 2, 5, 8, 4, 6, 0, 1]], [[]], [[1]]]; for (var k = 0; k < 40; k++) o.push([randArr(randInt(0, 12), -5, 10)]); return o; },
  ref: function (a) { var s = new Set(a[0]); var best = 0; s.forEach(function (x) { if (!s.has(x - 1)) { var y = x; while (s.has(y + 1)) y++; best = Math.max(best, y - x + 1); } }); return best; } });

MORE3.push({ slug: 'find-the-duplicate-number', title: 'Find the Duplicate Number', difficulty: 'medium', topics: ['Array', 'Two Pointers', 'Binary Search'], type: 'ARR_INT', langsrc: T.ARR_INT('findDuplicate'),
  desc: '<p>Given an array <code>nums</code> of <code>n+1</code> integers where each value is in <code>[1, n]</code>, exactly one value is repeated. Return the repeated number without modifying the array and using O(1) extra space.</p>',
  examples: [{ in: 'nums = [1,3,4,2,2]', out: '2' }, { in: 'nums = [3,1,3,4,2]', out: '3' }],
  constraints: ['1 &lt;= n &lt;= 10^5', 'nums.length == n + 1', 'Only one repeated number, but it may appear more than once.'],
  editorial: ED({ intuition: ['Because values lie in <code>[1, n]</code>, treat each value as a "next index" pointer. Following these pointers must eventually cycle, and the entrance to the cycle is the duplicate.', 'Floyd\u2019s tortoise-and-hare finds that cycle entrance in O(1) space, without altering the array.'], approach: ['Phase 1: advance <code>slow</code> by one and <code>fast</code> by two until they meet inside the cycle.', 'Phase 2: reset <code>slow</code> to the start; move both one step at a time. Where they meet is the cycle entrance = the duplicate.'], walkthrough: 'nums = [1,3,4,2,2]\nfollow indices -> a cycle forms at value 2\nFloyd meeting + reset lands on 2 -> answer 2', code: 'def findDuplicate(nums):\n    slow = fast = nums[0]\n    while True:\n        slow = nums[slow]\n        fast = nums[nums[fast]]\n        if slow == fast:\n            break\n    slow = nums[0]\n    while slow != fast:\n        slow = nums[slow]\n        fast = nums[fast]\n    return slow', time: 'O(n)', timeWhy: 'both phases traverse a linear number of steps.', space: 'O(1)', spaceWhy: 'two pointers, array untouched.', pitfalls: ['Sorting or a hash set are simpler but violate the O(1)-space / read-only constraints.'] }),
  gen: function () { var o = [[[1, 3, 4, 2, 2]], [[3, 1, 3, 4, 2]], [[1, 1]]]; for (var k = 0; k < 40; k++) { var n = randInt(1, 8); var arr = []; for (var i = 1; i <= n; i++) arr.push(i); arr.push(randInt(1, n)); o.push([shuffle(arr)]); } return o; },
  ref: function (a) { var seen = {}; for (var i = 0; i < a[0].length; i++) { if (seen[a[0][i]]) return a[0][i]; seen[a[0][i]] = 1; } return -1; } });

MORE3.push({ slug: 'squares-of-a-sorted-array', title: 'Squares of a Sorted Array', difficulty: 'easy', topics: ['Array', 'Two Pointers', 'Sorting'], type: 'ARR_ARR', langsrc: T.ARR_ARR('sortedSquares'),
  desc: '<p>Given an array <code>nums</code> sorted in non-decreasing order, return an array of the squares of each number, also sorted in non-decreasing order.</p>',
  examples: [{ in: 'nums = [-4,-1,0,3,10]', out: '[0,1,9,16,100]' }, { in: 'nums = [-7,-3,2,3,11]', out: '[4,9,9,49,121]' }],
  constraints: ['1 &lt;= nums.length &lt;= 10^4', '-10^4 &lt;= nums[i] &lt;= 10^4', 'nums is sorted non-decreasing.'],
  editorial: ED({ intuition: ['The largest squares come from the extremes (most negative or most positive). So fill the output from the back using two pointers at both ends.', 'This beats the trivial "square then sort" O(n log n) with a clean O(n) merge.'], approach: ['Pointers <code>l</code>, <code>r</code> at both ends; write position at the end of the output.', 'Compare squares at <code>l</code> and <code>r</code>; place the larger at the current output slot and move that pointer inward.', 'Repeat until the pointers cross.'], walkthrough: 'nums = [-4,-1,0,3,10]\nsquares extremes: 16 vs 100 -> place 100\n16 vs 9 -> 16 ... result [0,1,9,16,100]', code: 'def sortedSquares(nums):\n    n = len(nums)\n    res = [0] * n\n    l, r, i = 0, n - 1, n - 1\n    while l <= r:\n        if abs(nums[l]) > abs(nums[r]):\n            res[i] = nums[l] * nums[l]; l += 1\n        else:\n            res[i] = nums[r] * nums[r]; r -= 1\n        i -= 1\n    return res', time: 'O(n)', timeWhy: 'single two-pointer pass.', space: 'O(n)', spaceWhy: 'the output array (O(1) beyond it).' }),
  gen: function () { var o = [[[-4, -1, 0, 3, 10]], [[-7, -3, 2, 3, 11]], [[0]], [[-2, -1]]]; for (var k = 0; k < 40; k++) o.push([randArr(randInt(1, 10), -12, 12).sort(function (a, b) { return a - b; })]); return o; },
  ref: function (a) { return a[0].map(function (x) { return x * x; }).sort(function (p, q) { return p - q; }); } });

MORE3.push({ slug: 'first-unique-character-in-a-string', title: 'First Unique Character in a String', difficulty: 'easy', topics: ['String', 'Hash Table', 'Queue'], type: 'STR_INT', langsrc: T.STR_INT('firstUniqChar'),
  desc: '<p>Given a string <code>s</code>, return the index of the first non-repeating character. If none exists, return <code>-1</code>.</p>',
  examples: [{ in: 's = "leetcode"', out: '0' }, { in: 's = "loveleetcode"', out: '2' }, { in: 's = "aabb"', out: '-1' }],
  constraints: ['1 &lt;= s.length &lt;= 10^5', 's consists of lowercase English letters.'],
  editorial: ED({ intuition: 'A character is the answer if it appears exactly once. Count every character first, then scan left to right for the first with a count of 1.', approach: ['Build a frequency map of all characters.', 'Scan the string; return the index of the first character whose count is 1.', 'If none, return -1.'], walkthrough: 's = "loveleetcode"\ncounts: l:2 o:2 v:1 e:4 t:1 c:1 d:1\nfirst count==1 while scanning -> index 2 (v)', code: 'from collections import Counter\ndef firstUniqChar(s):\n    count = Counter(s)\n    for i, c in enumerate(s):\n        if count[c] == 1:\n            return i\n    return -1', time: 'O(n)', timeWhy: 'two passes over the string.', space: 'O(1)', spaceWhy: 'the count map is bounded by the 26-letter alphabet.' }),
  gen: function () { var o = [['leetcode'], ['loveleetcode'], ['aabb'], ['z'], ['']]; var ch = 'abc'; for (var k = 0; k < 40; k++) { var L = randInt(0, 8), s = ''; for (var i = 0; i < L; i++) s += ch[randInt(0, 2)]; o.push([s]); } return o; },
  ref: function (a) { var s = a[0], c = {}; for (var i = 0; i < s.length; i++) c[s[i]] = (c[s[i]] || 0) + 1; for (var j = 0; j < s.length; j++) if (c[s[j]] === 1) return j; return -1; } });

MORE3.push({ slug: 'is-subsequence', title: 'Is Subsequence', difficulty: 'easy', topics: ['String', 'Two Pointers', 'Dynamic Programming'], type: 'STR_STR_BOOL', langsrc: T.STR_STR_BOOL('isSubsequence'),
  desc: '<p>Given two strings <code>s</code> and <code>t</code>, return <code>true</code> if <code>s</code> is a subsequence of <code>t</code> (formed by deleting some characters of <code>t</code> without changing the order of the rest).</p>',
  examples: [{ in: 's = "abc", t = "ahbgdc"', out: 'true' }, { in: 's = "axc", t = "ahbgdc"', out: 'false' }],
  constraints: ['0 &lt;= s.length &lt;= 100', '0 &lt;= t.length &lt;= 10^4'],
  editorial: ED({ intuition: 'Greedily match the characters of <code>s</code> against <code>t</code> in order. Advance through <code>t</code>; whenever it matches the current needed character of <code>s</code>, move to the next needed character. If we consume all of <code>s</code>, it is a subsequence.', approach: ['Pointer <code>i</code> into <code>s</code>.', 'Walk <code>t</code>; when <code>t[j] == s[i]</code>, advance <code>i</code>.', 'If <code>i</code> reaches the end of <code>s</code>, return True.'], walkthrough: 's = "abc", t = "ahbgdc"\na matches a, b matches b, c matches c -> consumed all of s -> true', code: 'def isSubsequence(s, t):\n    i = 0\n    for c in t:\n        if i < len(s) and s[i] == c:\n            i += 1\n    return i == len(s)', time: 'O(|t|)', timeWhy: 'one pass over t.', space: 'O(1)', spaceWhy: 'two indices.', pitfalls: ['An empty <code>s</code> is a subsequence of anything \u2014 the pointer starts already "consumed".'] }),
  gen: function () { var o = [['abc', 'ahbgdc'], ['axc', 'ahbgdc'], ['', 'abc'], ['abc', '']]; var ch = 'abc'; function rw(L) { var s = ''; for (var i = 0; i < L; i++) s += ch[randInt(0, 2)]; return s; } for (var k = 0; k < 38; k++) o.push([rw(randInt(0, 4)), rw(randInt(0, 8))]); return o; },
  ref: function (a) { var s = a[0], t = a[1], i = 0; for (var j = 0; j < t.length; j++) if (i < s.length && s[i] === t[j]) i++; return i === s.length; } });

MORE3.push({ slug: 'number-of-1-bits', title: 'Number of 1 Bits', difficulty: 'easy', topics: ['Bit Manipulation'], type: 'INT_INT', langsrc: T.INT_INT('hammingWeight'),
  desc: '<p>Given a non-negative integer <code>n</code>, return the number of set bits (1s) in its binary representation (its Hamming weight).</p>',
  examples: [{ in: 'n = 11', out: '3', ex: '11 = 1011 in binary.' }, { in: 'n = 128', out: '1' }],
  constraints: ['0 &lt;= n &lt;= 2^31 - 1'],
  editorial: ED({ intuition: 'The identity <code>n &amp; (n - 1)</code> clears the lowest set bit. Repeatedly applying it counts exactly as many iterations as there are set bits.', approach: ['Initialize a counter to 0.', 'While <code>n</code> is non-zero, do <code>n &amp;= n - 1</code> and increment the counter.', 'Return the counter.'], walkthrough: 'n = 11 (1011)\n1011 & 1010 = 1010  (count 1)\n1010 & 1001 = 1000  (count 2)\n1000 & 0111 = 0000  (count 3) -> answer 3', code: 'def hammingWeight(n):\n    count = 0\n    while n:\n        n &= n - 1\n        count += 1\n    return count', time: 'O(bits set)', timeWhy: 'one iteration per set bit (at most 32).', space: 'O(1)', spaceWhy: 'a single counter.' }),
  gen: function () { var o = [[11], [128], [0], [7], [2147483647]]; for (var k = 0; k < 40; k++) o.push([randInt(0, 100000)]); return o; },
  ref: function (a) { var n = a[0], c = 0; while (n) { n &= n - 1; c++; } return c; } });

MORE3.push({ slug: 'koko-eating-bananas', title: 'Koko Eating Bananas', difficulty: 'medium', topics: ['Array', 'Binary Search'], type: 'ARR_TGT_INT', langsrc: T.ARR_TGT_INT('minEatingSpeed'),
  desc: '<p>Koko has piles of bananas (<code>nums</code>) and <code>h</code> hours (passed as <code>target</code>) before the guards return. Each hour she eats up to <code>k</code> bananas from one pile. Return the minimum integer speed <code>k</code> so she finishes all piles within <code>h</code> hours.</p>',
  examples: [{ in: 'piles = [3,6,7,11], h = 8', out: '4' }, { in: 'piles = [30,11,23,4,20], h = 5', out: '30' }],
  constraints: ['1 &lt;= piles.length &lt;= 10^4', 'piles.length &lt;= h &lt;= 10^9', '1 &lt;= piles[i] &lt;= 10^9'],
  editorial: ED({ intuition: ['"Can Koko finish at speed k?" is monotonic: if a speed works, every larger speed works too. That monotonic yes/no boundary is exactly what binary search finds.', 'So binary-search the speed in <code>[1, max(piles)]</code> for the smallest feasible value.'], approach: ['At speed <code>k</code>, hours needed = <code>sum(ceil(pile / k))</code>.', 'Binary-search <code>k</code>: if the hours are within <code>h</code>, try slower (smaller k); otherwise faster.', 'Return the smallest feasible speed.'], walkthrough: 'piles=[3,6,7,11], h=8\nk=4 -> ceil: 1+2+2+3 = 8 <= 8 feasible\nk=3 -> 1+2+3+4 = 10 > 8 not feasible\nsmallest feasible = 4', code: 'import math\ndef minEatingSpeed(piles, h):\n    lo, hi = 1, max(piles)\n    while lo < hi:\n        k = (lo + hi) // 2\n        hours = sum((p + k - 1) // k for p in piles)\n        if hours <= h:\n            hi = k\n        else:\n            lo = k + 1\n    return lo', time: 'O(n log maxPile)', timeWhy: 'each binary-search step scans the piles once.', space: 'O(1)', spaceWhy: 'a few scalars.', pitfalls: ['Search the answer space (speeds), not the array itself.'] }),
  gen: function () { var o = [[[3, 6, 7, 11], 8], [[30, 11, 23, 4, 20], 5], [[312884470], 968709470]]; for (var k = 0; k < 40; k++) { var n = randInt(1, 6), piles = randArr(n, 1, 30); o.push([piles, randInt(n, n + 20)]); } return o; },
  ref: function (a) { var piles = a[0], h = a[1], lo = 1, hi = Math.max.apply(null, piles); while (lo < hi) { var k = Math.floor((lo + hi) / 2); var hrs = 0; for (var i = 0; i < piles.length; i++) hrs += Math.ceil(piles[i] / k); if (hrs <= h) hi = k; else lo = k + 1; } return lo; } });

MORE3.push({ slug: 'subarray-sum-equals-k', title: 'Subarray Sum Equals K', difficulty: 'medium', topics: ['Array', 'Hash Table', 'Prefix Sum'], type: 'ARR_TGT_INT', langsrc: T.ARR_TGT_INT('subarraySum'),
  desc: '<p>Given an integer array <code>nums</code> and an integer <code>k</code> (passed as <code>target</code>), return the total number of contiguous subarrays whose sum equals <code>k</code>.</p>',
  examples: [{ in: 'nums = [1,1,1], k = 2', out: '2' }, { in: 'nums = [1,2,3], k = 3', out: '2' }],
  constraints: ['1 &lt;= nums.length &lt;= 2*10^4', '-1000 &lt;= nums[i] &lt;= 1000', 'nums may contain negatives (sliding window will not work).'],
  editorial: ED({ intuition: ['A subarray sum equals <code>prefix[j] - prefix[i]</code>. We want that difference to be <code>k</code>, i.e. <code>prefix[i] = prefix[j] - k</code>.', 'So as we sweep and maintain a running prefix sum, we count how many earlier prefix sums equal <code>current - k</code> using a hash map. This handles negatives, which a sliding window cannot.'], approach: ['Keep a map of prefix-sum \u2192 how many times it has occurred, seeded with <code>{0: 1}</code>.', 'Maintain the running sum. Add <code>count[sum - k]</code> to the answer.', 'Increment <code>count[sum]</code>.'], walkthrough: 'nums = [1,1,1], k = 2\nsum=1 need -1 -> 0; count{0:1,1:1}\nsum=2 need 0 -> +1; count{...2:1}\nsum=3 need 1 -> +1  total = 2', code: 'from collections import defaultdict\ndef subarraySum(nums, k):\n    count = defaultdict(int)\n    count[0] = 1\n    s = res = 0\n    for x in nums:\n        s += x\n        res += count[s - k]\n        count[s] += 1\n    return res', time: 'O(n)', timeWhy: 'one pass with O(1) map operations.', space: 'O(n)', spaceWhy: 'the prefix-sum frequency map.', pitfalls: ['Seed the map with <code>{0:1}</code> so subarrays starting at index 0 are counted.'] }),
  gen: function () { var o = [[[1, 1, 1], 2], [[1, 2, 3], 3], [[1], 0]]; for (var k = 0; k < 40; k++) { var n = randInt(1, 8), arr = randArr(n, -3, 3); o.push([arr, randInt(-4, 6)]); } return o; },
  ref: function (a) { var nums = a[0], k = a[1], count = { 0: 1 }, s = 0, res = 0; for (var i = 0; i < nums.length; i++) { s += nums[i]; res += (count[s - k] || 0); count[s] = (count[s] || 0) + 1; } return res; } });

MORE3.push({ slug: 'minimum-size-subarray-sum', title: 'Minimum Size Subarray Sum', difficulty: 'medium', topics: ['Array', 'Sliding Window', 'Two Pointers'], type: 'ARR_TGT_INT', langsrc: T.ARR_TGT_INT('minSubArrayLen'),
  desc: '<p>Given an array of positive integers <code>nums</code> and a positive integer <code>target</code>, return the minimal length of a contiguous subarray whose sum is \u2265 <code>target</code>. If there is none, return <code>0</code>.</p>',
  examples: [{ in: 'target = 7, nums = [2,3,1,2,4,3]', out: '2', ex: 'The subarray [4,3] has sum 7 and length 2.' }, { in: 'target = 11, nums = [1,1,1,1,1]', out: '0' }],
  constraints: ['1 &lt;= nums.length &lt;= 10^5', '1 &lt;= nums[i] &lt;= 10^4', '1 &lt;= target &lt;= 10^9'],
  editorial: ED({ intuition: ['All numbers are positive, so growing the window only increases the sum and shrinking only decreases it \u2014 a sliding window works.', 'Expand the right edge until the sum reaches the target, then shrink from the left as far as possible while still \u2265 target, recording the smallest width.'], approach: ['Move the right end, adding to the running sum.', 'While the sum \u2265 target, record the window length and remove the left element (shrink).', 'Track the minimum length; 0 if the target is never reached.'], walkthrough: 'target=7, nums=[2,3,1,2,4,3]\nwindow grows to [2,3,1,2] sum 8, shrink -> [3,1,2] len 3\n... eventually [4,3] sum 7 len 2 -> answer 2', code: 'def minSubArrayLen(nums, target):\n    left = 0\n    s = 0\n    best = float("inf")\n    for right, x in enumerate(nums):\n        s += x\n        while s >= target:\n            best = min(best, right - left + 1)\n            s -= nums[left]\n            left += 1\n    return best if best != float("inf") else 0', time: 'O(n)', timeWhy: 'each element enters and leaves the window at most once.', space: 'O(1)', spaceWhy: 'a few scalars.', pitfalls: ['This relies on all-positive values; with negatives you would need a different (prefix-sum + deque) approach.'] }),
  gen: function () { var o = [[[2, 3, 1, 2, 4, 3], 7], [[1, 1, 1, 1, 1], 11], [[1, 4, 4], 4]]; for (var k = 0; k < 40; k++) { var n = randInt(1, 10), arr = randArr(n, 1, 8); o.push([arr, randInt(1, 25)]); } return o; },
  ref: function (a) { var nums = a[0], target = a[1], left = 0, s = 0, best = Infinity; for (var r = 0; r < nums.length; r++) { s += nums[r]; while (s >= target) { best = Math.min(best, r - left + 1); s -= nums[left]; left++; } } return best === Infinity ? 0 : best; } });

MORE3.push({ slug: 'rotate-array', title: 'Rotate Array', difficulty: 'medium', topics: ['Array', 'Two Pointers'], type: 'ARR_TGT_ARR', langsrc: T.ARR_TGT_ARR('rotate'),
  desc: '<p>Given an array <code>nums</code>, rotate it to the right by <code>k</code> steps (<code>k</code> passed as <code>target</code>) and return the rotated array.</p>',
  examples: [{ in: 'nums = [1,2,3,4,5,6,7], k = 3', out: '[5,6,7,1,2,3,4]' }, { in: 'nums = [-1,-100,3,99], k = 2', out: '[3,99,-1,-100]' }],
  constraints: ['1 &lt;= nums.length &lt;= 10^5', '0 &lt;= k &lt;= 10^5'],
  editorial: ED({ intuition: ['Rotating right by <code>k</code> moves the last <code>k</code> elements to the front. Reduce <code>k</code> modulo <code>n</code> first (rotating by n does nothing).', 'The elegant in-place trick: reverse the whole array, then reverse the first <code>k</code> and the remaining <code>n-k</code> \u2014 O(1) space.'], approach: ['Set <code>k %= n</code>.', 'Reverse the entire array.', 'Reverse the first <code>k</code> elements, then reverse the rest.'], walkthrough: 'nums=[1,2,3,4,5,6,7], k=3\nreverse all -> [7,6,5,4,3,2,1]\nreverse first 3 -> [5,6,7,4,3,2,1]\nreverse rest -> [5,6,7,1,2,3,4]', code: 'def rotate(nums, k):\n    n = len(nums)\n    k %= n\n    nums[:] = nums[-k:] + nums[:-k] if k else nums\n    return nums', time: 'O(n)', timeWhy: 'the reversals touch each element a constant number of times.', space: 'O(1)', spaceWhy: 'the reversal method rotates in place.', pitfalls: ['Reduce <code>k</code> modulo <code>n</code>, or large <code>k</code> breaks slicing / over-rotates.'] }),
  gen: function () { var o = [[[1, 2, 3, 4, 5, 6, 7], 3], [[-1, -100, 3, 99], 2], [[1], 0], [[1, 2], 3]]; for (var k = 0; k < 40; k++) { var n = randInt(1, 9), arr = randArr(n, -10, 10); o.push([arr, randInt(0, 12)]); } return o; },
  ref: function (a) { var nums = a[0].slice(), n = nums.length, k = a[1] % n; if (k === 0) return nums; return nums.slice(n - k).concat(nums.slice(0, n - k)); } });

module.exports = { MORE3 };
