// Batch 22: famous "design" (operations-replay) problems on the theme of
// STACKS, QUEUES, and DESIGN. Every problem is type OPS: a test case is a
// sequence of method calls; the harness constructs the user's class, dispatches
// each call, and prints the return tokens joined by '|' (null for
// constructors/void). Mirrors LeetCode's design-problem format and the batch-K
// design problems (min-stack, lru-cache, ...).
const { randInt, ln } = require('./gen.js');

function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function ED(o) {
  var h = '';
  if (o.intuition) h += '<h3>Intuition</h3>' + (Array.isArray(o.intuition) ? o.intuition.map(function (p) { return '<p>' + p + '</p>'; }).join('') : '<p>' + o.intuition + '</p>');
  if (o.approach) h += '<h3>Approach</h3><ol>' + o.approach.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ol>';
  if (o.code) h += '<h3>Solution</h3><pre><code>' + esc(o.code) + '</code></pre>';
  h += '<h3>Complexity</h3><ul><li><b>Time — ' + o.time + ':</b> ' + o.timeWhy + '</li><li><b>Space — ' + o.space + ':</b> ' + o.spaceWhy + '</li></ul>';
  if (o.pitfalls) h += '<h3>Common Pitfalls</h3><ul>' + o.pitfalls.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ul>';
  return h;
}

// Build the four-language ops-replay harness for a class. dispatch is a small
// per-language chain of `op == name` -> code producing a token pushed to _res.
// (identical mechanism to batch K's opsHarness.)
function opsHarness(className, py, js, cpp, java) {
  return {
    python: ln('import sys', '_L=sys.stdin.read().split("\\n"); _i=0', '_T=int(_L[_i]); _i+=1; _out=[]', 'for _c in range(_T):', '    _m=int(_L[_i]); _i+=1; _res=[]; _o=None', '    for _j in range(_m):', '        _p=_L[_i].split(); _i+=1; _op=_p[0]', py, "    _out.append('|'.join(_res))", 'print("\\n".join(_out))'),
    javascript: ln("const _L=require('fs').readFileSync(0,'utf8').split('\\n'); let _i=0;", 'const _T=+_L[_i++]; const _out=[];', 'for(let _c=0;_c<_T;_c++){ const _m=+_L[_i++]; const _res=[]; let _o=null;', ' for(let _j=0;_j<_m;_j++){ const _p=(_L[_i++]||"").split(/\\s+/).filter(x=>x.length); const _op=_p[0];', js, ' } _out.push(_res.join("|")); }', 'console.log(_out.join("\\n"));'),
    cpp: ln('int main(){ string _line; getline(cin,_line); int _T=stoi(_line);', ' for(int _c=0;_c<_T;_c++){ getline(cin,_line); int _m=stoi(_line); vector<string> _res; ' + className + '* _o=nullptr;', '  for(int _j=0;_j<_m;_j++){ getline(cin,_line); istringstream _is(_line); string _op; _is>>_op;', cpp, '  }', '  string _s; for(size_t _k=0;_k<_res.size();_k++){ if(_k)_s+="|"; _s+=_res[_k]; } cout<<_s<<"\\n";', ' }', '}'),
    java: ln('public class Main {', '  public static void main(String[] a){ Scanner sc=new Scanner(System.in); int T=Integer.parseInt(sc.nextLine().trim()); StringBuilder sb=new StringBuilder();', '    for(int c=0;c<T;c++){ int m=Integer.parseInt(sc.nextLine().trim()); List<String> res=new ArrayList<>(); ' + className + ' o=null;', '      for(int j=0;j<m;j++){ String[] p=sc.nextLine().trim().split("\\\\s+"); String op=p[0];', java, '      }', '      sb.append(String.join("|",res)).append("\\n");', '    }', '    System.out.print(sb);', '  }', '}'),
  };
}

const MORE22 = [];

// ---- Implement Queue using Stacks ----
MORE22.push({ slug: 'implement-queue-using-stacks', title: 'Implement Queue using Stacks', difficulty: 'easy', topics: ['Stack', 'Queue', 'Design'], type: 'OPS',
  desc: '<p>Implement a first-in-first-out (FIFO) queue using only two stacks. Implement <code>MyQueue</code> with <code>push(x)</code>, <code>pop()</code> (removes and returns the front element), <code>peek()</code> (returns the front element), and <code>empty()</code>.</p>',
  examples: [{ in: 'operations = ["MyQueue","push","push","peek","pop","empty"], values = [[],[1],[2],[],[],[]]', out: '[null,null,null,1,1,false]' }],
  constraints: ['1 &lt;= x &lt;= 9', 'At most 100 calls to push, pop, peek, and empty.', 'pop and peek are only called on a non-empty queue.'],
  editorial: ED({ intuition: 'A stack is LIFO but a queue is FIFO. Use an <em>input</em> stack for pushes and an <em>output</em> stack for pops. When the output stack is empty, pour the input stack into it — this reverses the order so the oldest element ends up on top.', approach: ['push always goes onto the input stack.', 'For pop/peek, if the output stack is empty, move every element from input to output (reversing order).', 'The front of the queue is then the top of the output stack.'], code: 'class MyQueue:\n    def __init__(self):\n        self.inp, self.out = [], []\n    def push(self, x):\n        self.inp.append(x)\n    def _shift(self):\n        if not self.out:\n            while self.inp:\n                self.out.append(self.inp.pop())\n    def pop(self):\n        self._shift(); return self.out.pop()\n    def peek(self):\n        self._shift(); return self.out[-1]\n    def empty(self):\n        return not self.inp and not self.out', time: 'O(1) amortized', timeWhy: 'each element is moved between stacks at most once.', space: 'O(n)', spaceWhy: 'the two stacks hold all queued elements.', pitfalls: ['Only refill the output stack when it is empty; refilling early scrambles the order.'] }),
  custom: {
    python: { stub: ln('class MyQueue:', '    def __init__(self):', '        # Write your code here', '        pass', '    def push(self, x):', '        pass', '    def pop(self):', '        return 0', '    def peek(self):', '        return 0', '    def empty(self):', '        return True'), harness: null },
    javascript: { stub: ln('class MyQueue {', '    constructor() {', '        // Write your code here', '    }', '    push(x) {}', '    pop() { return 0; }', '    peek() { return 0; }', '    empty() { return true; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class MyQueue {', 'public:', '    MyQueue() {', '        // Write your code here', '    }', '    void push(int x) {}', '    int pop() { return 0; }', '    int peek() { return 0; }', '    bool empty() { return true; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class MyQueue {', '    public MyQueue() {', '        // Write your code here', '    }', '    public void push(int x) {}', '    public int pop() { return 0; }', '    public int peek() { return 0; }', '    public boolean empty() { return true; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'MyQueue', a: [] }, { name: 'push', a: [1] }, { name: 'push', a: [2] }, { name: 'peek', a: [] }, { name: 'pop', a: [] }, { name: 'empty', a: [] }]]];
    for (var k = 0; k < 34; k++) { var ops = [{ name: 'MyQueue', a: [] }], size = 0, n = randInt(3, 12); for (var i = 0; i < n; i++) { if (size === 0 || Math.random() < 0.5) { ops.push({ name: 'push', a: [randInt(1, 9)] }); size++; } else { var c = Math.random(); if (c < 0.34) { ops.push({ name: 'pop', a: [] }); size--; } else if (c < 0.67) ops.push({ name: 'peek', a: [] }); else ops.push({ name: 'empty', a: [] }); } } ops.push({ name: 'empty', a: [] }); o.push([ops]); }
    return o;
  },
  ref: function (a) { var q = [], res = []; a[0].forEach(function (o) { if (o.name === 'MyQueue') { q = []; res.push('null'); } else if (o.name === 'push') { q.push(o.a[0]); res.push('null'); } else if (o.name === 'pop') res.push(String(q.shift())); else if (o.name === 'peek') res.push(String(q[0])); else if (o.name === 'empty') res.push(q.length === 0 ? 'true' : 'false'); }); return res.join('|'); } });

// ---- Implement Stack using Queues ----
MORE22.push({ slug: 'implement-stack-using-queues', title: 'Implement Stack using Queues', difficulty: 'easy', topics: ['Stack', 'Queue', 'Design'], type: 'OPS',
  desc: '<p>Implement a last-in-first-out (LIFO) stack using only queues. Implement <code>MyStack</code> with <code>push(x)</code>, <code>pop()</code> (removes and returns the top element), <code>top()</code> (returns the top element), and <code>empty()</code>.</p>',
  examples: [{ in: 'operations = ["MyStack","push","push","top","pop","empty"], values = [[],[1],[2],[],[],[]]', out: '[null,null,null,2,2,false]' }],
  constraints: ['1 &lt;= x &lt;= 9', 'At most 100 calls to push, pop, top, and empty.', 'pop and top are only called on a non-empty stack.'],
  editorial: ED({ intuition: 'A single queue can behave like a stack if, right after each push, you rotate all the earlier elements behind the new one. Then the newest element sits at the front and dequeues first — LIFO from a FIFO structure.', approach: ['Keep one queue.', 'On push, enqueue x, then dequeue-and-re-enqueue the other elements so x moves to the front.', 'pop/top read the front; empty checks the size.'], code: 'from collections import deque\n\nclass MyStack:\n    def __init__(self):\n        self.q = deque()\n    def push(self, x):\n        self.q.append(x)\n        for _ in range(len(self.q) - 1):\n            self.q.append(self.q.popleft())\n    def pop(self):\n        return self.q.popleft()\n    def top(self):\n        return self.q[0]\n    def empty(self):\n        return not self.q', time: 'O(n) push', timeWhy: 'push rotates the queue; pop/top/empty are O(1).', space: 'O(n)', spaceWhy: 'the queue holds all elements.', pitfalls: ['Rotate exactly size-1 times so the new element ends up at the front.'] }),
  custom: {
    python: { stub: ln('class MyStack:', '    def __init__(self):', '        # Write your code here', '        pass', '    def push(self, x):', '        pass', '    def pop(self):', '        return 0', '    def top(self):', '        return 0', '    def empty(self):', '        return True'), harness: null },
    javascript: { stub: ln('class MyStack {', '    constructor() {', '        // Write your code here', '    }', '    push(x) {}', '    pop() { return 0; }', '    top() { return 0; }', '    empty() { return true; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class MyStack {', 'public:', '    MyStack() {', '        // Write your code here', '    }', '    void push(int x) {}', '    int pop() { return 0; }', '    int top() { return 0; }', '    bool empty() { return true; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class MyStack {', '    public MyStack() {', '        // Write your code here', '    }', '    public void push(int x) {}', '    public int pop() { return 0; }', '    public int top() { return 0; }', '    public boolean empty() { return true; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'MyStack', a: [] }, { name: 'push', a: [1] }, { name: 'push', a: [2] }, { name: 'top', a: [] }, { name: 'pop', a: [] }, { name: 'empty', a: [] }]]];
    for (var k = 0; k < 34; k++) { var ops = [{ name: 'MyStack', a: [] }], size = 0, n = randInt(3, 12); for (var i = 0; i < n; i++) { if (size === 0 || Math.random() < 0.5) { ops.push({ name: 'push', a: [randInt(1, 9)] }); size++; } else { var c = Math.random(); if (c < 0.34) { ops.push({ name: 'pop', a: [] }); size--; } else if (c < 0.67) ops.push({ name: 'top', a: [] }); else ops.push({ name: 'empty', a: [] }); } } ops.push({ name: 'empty', a: [] }); o.push([ops]); }
    return o;
  },
  ref: function (a) { var st = [], res = []; a[0].forEach(function (o) { if (o.name === 'MyStack') { st = []; res.push('null'); } else if (o.name === 'push') { st.push(o.a[0]); res.push('null'); } else if (o.name === 'pop') res.push(String(st.pop())); else if (o.name === 'top') res.push(String(st[st.length - 1])); else if (o.name === 'empty') res.push(st.length === 0 ? 'true' : 'false'); }); return res.join('|'); } });

// ---- Design HashMap ----
MORE22.push({ slug: 'design-hashmap', title: 'Design HashMap', difficulty: 'easy', topics: ['Array', 'Hash Table', 'Design'], type: 'OPS',
  desc: '<p>Design a HashMap without using any built-in hash table libraries. Implement <code>MyHashMap</code> with <code>put(key, value)</code>, <code>get(key)</code> (returns the value or <code>-1</code> if the key is absent), and <code>remove(key)</code>.</p>',
  examples: [{ in: 'operations = ["MyHashMap","put","put","get","get","put","get","remove","get"], values = [[],[1,1],[2,2],[1],[3],[2,1],[2],[2],[2]]', out: '[null,null,null,1,-1,null,1,null,-1]' }],
  constraints: ['0 &lt;= key, value &lt;= 10^6', 'At most 10^4 calls to put, get, and remove.'],
  editorial: ED({ intuition: 'A hash map maps keys to values with O(1) average access. Bucket keys by a hash and store (key, value) pairs so collisions live in the same bucket and are scanned linearly.', approach: ['Keep an array of buckets; hash the key to pick a bucket.', 'put scans the bucket to update an existing key or appends a new pair.', 'get scans the bucket and returns the value or -1; remove deletes the pair.'], code: 'class MyHashMap:\n    def __init__(self):\n        self.n = 1009\n        self.buckets = [[] for _ in range(self.n)]\n    def put(self, key, value):\n        b = self.buckets[key % self.n]\n        for p in b:\n            if p[0] == key:\n                p[1] = value; return\n        b.append([key, value])\n    def get(self, key):\n        for p in self.buckets[key % self.n]:\n            if p[0] == key:\n                return p[1]\n        return -1\n    def remove(self, key):\n        b = self.buckets[key % self.n]\n        for i, p in enumerate(b):\n            if p[0] == key:\n                b.pop(i); return', time: 'O(1) average', timeWhy: 'each operation touches one bucket; with a good load factor buckets stay short.', space: 'O(n)', spaceWhy: 'stored key/value pairs plus the bucket array.', pitfalls: ['get must return -1 for missing keys, not 0.', 'put must overwrite an existing key rather than adding a duplicate.'] }),
  custom: {
    python: { stub: ln('class MyHashMap:', '    def __init__(self):', '        # Write your code here', '        pass', '    def put(self, key, value):', '        pass', '    def get(self, key):', '        return -1', '    def remove(self, key):', '        pass'), harness: null },
    javascript: { stub: ln('class MyHashMap {', '    constructor() {', '        // Write your code here', '    }', '    put(key, value) {}', '    get(key) { return -1; }', '    remove(key) {}', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class MyHashMap {', 'public:', '    MyHashMap() {', '        // Write your code here', '    }', '    void put(int key, int value) {}', '    int get(int key) { return -1; }', '    void remove(int key) {}', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class MyHashMap {', '    public MyHashMap() {', '        // Write your code here', '    }', '    public void put(int key, int value) {}', '    public int get(int key) { return -1; }', '    public void remove(int key) {}', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'MyHashMap', a: [] }, { name: 'put', a: [1, 1] }, { name: 'put', a: [2, 2] }, { name: 'get', a: [1] }, { name: 'get', a: [3] }, { name: 'put', a: [2, 1] }, { name: 'get', a: [2] }, { name: 'remove', a: [2] }, { name: 'get', a: [2] }]]];
    for (var k = 0; k < 34; k++) { var ops = [{ name: 'MyHashMap', a: [] }], n = randInt(4, 14); for (var i = 0; i < n; i++) { var c = Math.random(); if (c < 0.45) ops.push({ name: 'put', a: [randInt(0, 5), randInt(0, 9)] }); else if (c < 0.8) ops.push({ name: 'get', a: [randInt(0, 5)] }); else ops.push({ name: 'remove', a: [randInt(0, 5)] }); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var map = {}, res = []; a[0].forEach(function (o) { if (o.name === 'MyHashMap') { map = {}; res.push('null'); } else if (o.name === 'put') { map[o.a[0]] = o.a[1]; res.push('null'); } else if (o.name === 'get') res.push(map.hasOwnProperty(o.a[0]) ? String(map[o.a[0]]) : '-1'); else if (o.name === 'remove') { delete map[o.a[0]]; res.push('null'); } }); return res.join('|'); } });

// ---- Design HashSet ----
MORE22.push({ slug: 'design-hashset', title: 'Design HashSet', difficulty: 'easy', topics: ['Array', 'Hash Table', 'Design'], type: 'OPS',
  desc: '<p>Design a HashSet without using any built-in hash set libraries. Implement <code>MyHashSet</code> with <code>add(key)</code>, <code>contains(key)</code> (returns whether the key is present), and <code>remove(key)</code>.</p>',
  examples: [{ in: 'operations = ["MyHashSet","add","add","contains","contains","add","contains","remove","contains"], values = [[],[1],[2],[1],[3],[2],[2],[2],[2]]', out: '[null,null,null,true,false,null,true,null,false]' }],
  constraints: ['0 &lt;= key &lt;= 10^6', 'At most 10^4 calls to add, remove, and contains.'],
  editorial: ED({ intuition: 'A hash set stores membership only. Bucket each key by a hash and keep the keys that collide in the same bucket.', approach: ['Keep an array of buckets; hash the key to a bucket index.', 'add appends the key if not already present; remove deletes it.', 'contains scans the bucket for the key.'], code: 'class MyHashSet:\n    def __init__(self):\n        self.n = 1009\n        self.buckets = [[] for _ in range(self.n)]\n    def add(self, key):\n        b = self.buckets[key % self.n]\n        if key not in b:\n            b.append(key)\n    def contains(self, key):\n        return key in self.buckets[key % self.n]\n    def remove(self, key):\n        b = self.buckets[key % self.n]\n        if key in b:\n            b.remove(key)', time: 'O(1) average', timeWhy: 'each operation touches one short bucket.', space: 'O(n)', spaceWhy: 'stored keys plus the bucket array.', pitfalls: ['add must not insert duplicates.'] }),
  custom: {
    python: { stub: ln('class MyHashSet:', '    def __init__(self):', '        # Write your code here', '        pass', '    def add(self, key):', '        pass', '    def contains(self, key):', '        return False', '    def remove(self, key):', '        pass'), harness: null },
    javascript: { stub: ln('class MyHashSet {', '    constructor() {', '        // Write your code here', '    }', '    add(key) {}', '    contains(key) { return false; }', '    remove(key) {}', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class MyHashSet {', 'public:', '    MyHashSet() {', '        // Write your code here', '    }', '    void add(int key) {}', '    bool contains(int key) { return false; }', '    void remove(int key) {}', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class MyHashSet {', '    public MyHashSet() {', '        // Write your code here', '    }', '    public void add(int key) {}', '    public boolean contains(int key) { return false; }', '    public void remove(int key) {}', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'MyHashSet', a: [] }, { name: 'add', a: [1] }, { name: 'add', a: [2] }, { name: 'contains', a: [1] }, { name: 'contains', a: [3] }, { name: 'add', a: [2] }, { name: 'contains', a: [2] }, { name: 'remove', a: [2] }, { name: 'contains', a: [2] }]]];
    for (var k = 0; k < 34; k++) { var ops = [{ name: 'MyHashSet', a: [] }], n = randInt(4, 14); for (var i = 0; i < n; i++) { var c = Math.random(); if (c < 0.45) ops.push({ name: 'add', a: [randInt(0, 5)] }); else if (c < 0.8) ops.push({ name: 'contains', a: [randInt(0, 5)] }); else ops.push({ name: 'remove', a: [randInt(0, 5)] }); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var set = {}, res = []; a[0].forEach(function (o) { if (o.name === 'MyHashSet') { set = {}; res.push('null'); } else if (o.name === 'add') { set[o.a[0]] = 1; res.push('null'); } else if (o.name === 'contains') res.push(set.hasOwnProperty(o.a[0]) ? 'true' : 'false'); else if (o.name === 'remove') { delete set[o.a[0]]; res.push('null'); } }); return res.join('|'); } });

// ---- Design Circular Queue ----
MORE22.push({ slug: 'design-circular-queue', title: 'Design Circular Queue', difficulty: 'medium', topics: ['Array', 'Queue', 'Design'], type: 'OPS',
  desc: '<p>Design a circular queue using a fixed-size array. Implement <code>MyCircularQueue(k)</code> and: <code>enQueue(value)</code> (returns true on success), <code>deQueue()</code> (returns true on success), <code>Front()</code> and <code>Rear()</code> (return the front/rear value or <code>-1</code> if empty), <code>isEmpty()</code>, and <code>isFull()</code>.</p>',
  examples: [{ in: 'operations = ["MyCircularQueue","enQueue","enQueue","enQueue","enQueue","Rear","isFull","deQueue","enQueue","Rear"], values = [[3],[1],[2],[3],[4],[],[],[],[4],[]]', out: '[null,true,true,true,false,3,true,true,true,4]' }],
  constraints: ['1 &lt;= k &lt;= 1000', '0 &lt;= value &lt;= 1000', 'At most 3000 calls.'],
  editorial: ED({ intuition: 'A circular queue reuses a fixed array by wrapping indices with modulo, so no shifting is needed. Track a head index and a size; the tail is derived from them.', approach: ['Store a fixed array of capacity k, a head index, and a count.', 'enQueue writes at (head + count) % k when not full and bumps the count.', 'deQueue advances head modulo k and drops the count; Front/Rear read positions or return -1 when empty.'], code: 'class MyCircularQueue:\n    def __init__(self, k):\n        self.q = [0] * k\n        self.cap = k\n        self.head = 0\n        self.count = 0\n    def enQueue(self, value):\n        if self.count == self.cap:\n            return False\n        self.q[(self.head + self.count) % self.cap] = value\n        self.count += 1\n        return True\n    def deQueue(self):\n        if self.count == 0:\n            return False\n        self.head = (self.head + 1) % self.cap\n        self.count -= 1\n        return True\n    def Front(self):\n        return -1 if self.count == 0 else self.q[self.head]\n    def Rear(self):\n        return -1 if self.count == 0 else self.q[(self.head + self.count - 1) % self.cap]\n    def isEmpty(self):\n        return self.count == 0\n    def isFull(self):\n        return self.count == self.cap', time: 'O(1)', timeWhy: 'every operation is constant time via modular indexing.', space: 'O(k)', spaceWhy: 'the fixed backing array.', pitfalls: ['Compute the tail as (head + count - 1) % cap, not a separate mutable tail that can desync.'] }),
  custom: {
    python: { stub: ln('class MyCircularQueue:', '    def __init__(self, k):', '        # Write your code here', '        pass', '    def enQueue(self, value):', '        return False', '    def deQueue(self):', '        return False', '    def Front(self):', '        return -1', '    def Rear(self):', '        return -1', '    def isEmpty(self):', '        return True', '    def isFull(self):', '        return False'), harness: null },
    javascript: { stub: ln('class MyCircularQueue {', '    constructor(k) {', '        // Write your code here', '    }', '    enQueue(value) { return false; }', '    deQueue() { return false; }', '    Front() { return -1; }', '    Rear() { return -1; }', '    isEmpty() { return true; }', '    isFull() { return false; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class MyCircularQueue {', 'public:', '    MyCircularQueue(int k) {', '        // Write your code here', '    }', '    bool enQueue(int value) { return false; }', '    bool deQueue() { return false; }', '    int Front() { return -1; }', '    int Rear() { return -1; }', '    bool isEmpty() { return true; }', '    bool isFull() { return false; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class MyCircularQueue {', '    public MyCircularQueue(int k) {', '        // Write your code here', '    }', '    public boolean enQueue(int value) { return false; }', '    public boolean deQueue() { return false; }', '    public int Front() { return -1; }', '    public int Rear() { return -1; }', '    public boolean isEmpty() { return true; }', '    public boolean isFull() { return false; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'MyCircularQueue', a: [3] }, { name: 'enQueue', a: [1] }, { name: 'enQueue', a: [2] }, { name: 'enQueue', a: [3] }, { name: 'enQueue', a: [4] }, { name: 'Rear', a: [] }, { name: 'isFull', a: [] }, { name: 'deQueue', a: [] }, { name: 'enQueue', a: [4] }, { name: 'Rear', a: [] }]]];
    for (var k = 0; k < 34; k++) { var ops = [{ name: 'MyCircularQueue', a: [randInt(1, 4)] }], n = randInt(5, 16); for (var i = 0; i < n; i++) { var c = Math.random(); if (c < 0.4) ops.push({ name: 'enQueue', a: [randInt(0, 9)] }); else if (c < 0.6) ops.push({ name: 'deQueue', a: [] }); else if (c < 0.72) ops.push({ name: 'Front', a: [] }); else if (c < 0.84) ops.push({ name: 'Rear', a: [] }); else if (c < 0.92) ops.push({ name: 'isEmpty', a: [] }); else ops.push({ name: 'isFull', a: [] }); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var cap = 0, q = [], res = []; a[0].forEach(function (o) { if (o.name === 'MyCircularQueue') { cap = o.a[0]; q = []; res.push('null'); } else if (o.name === 'enQueue') { if (q.length === cap) res.push('false'); else { q.push(o.a[0]); res.push('true'); } } else if (o.name === 'deQueue') { if (q.length === 0) res.push('false'); else { q.shift(); res.push('true'); } } else if (o.name === 'Front') res.push(q.length === 0 ? '-1' : String(q[0])); else if (o.name === 'Rear') res.push(q.length === 0 ? '-1' : String(q[q.length - 1])); else if (o.name === 'isEmpty') res.push(q.length === 0 ? 'true' : 'false'); else if (o.name === 'isFull') res.push(q.length === cap ? 'true' : 'false'); }); return res.join('|'); } });

// ---- Design Circular Deque ----
MORE22.push({ slug: 'design-circular-deque', title: 'Design Circular Deque', difficulty: 'medium', topics: ['Array', 'Queue', 'Design'], type: 'OPS',
  desc: '<p>Design a circular double-ended queue. Implement <code>MyCircularDeque(k)</code> and: <code>insertFront(value)</code>, <code>insertLast(value)</code>, <code>deleteFront()</code>, <code>deleteLast()</code> (each returns true on success), <code>getFront()</code> and <code>getRear()</code> (return the value or <code>-1</code> if empty), <code>isEmpty()</code>, and <code>isFull()</code>.</p>',
  examples: [{ in: 'operations = ["MyCircularDeque","insertLast","insertLast","insertFront","insertFront","getRear","isFull","deleteLast","insertFront","getFront"], values = [[3],[1],[2],[3],[4],[],[],[],[4],[]]', out: '[null,true,true,true,false,2,true,true,true,4]' }],
  constraints: ['1 &lt;= k &lt;= 1000', '0 &lt;= value &lt;= 1000', 'At most 2000 calls.'],
  editorial: ED({ intuition: 'A deque supports insert/delete at both ends. Back it with a fixed array and track a head index and a size; the front grows by moving head backward (modulo), the rear grows forward.', approach: ['Keep an array of capacity k, a head index, and a count.', 'insertFront moves head back by one (modulo) and writes; insertLast writes at (head + count) % k.', 'deleteFront advances head; deleteLast just drops the count; getFront/getRear read the ends or return -1.'], code: 'class MyCircularDeque:\n    def __init__(self, k):\n        self.q = [0] * k\n        self.cap = k\n        self.head = 0\n        self.count = 0\n    def insertFront(self, value):\n        if self.count == self.cap:\n            return False\n        self.head = (self.head - 1) % self.cap\n        self.q[self.head] = value\n        self.count += 1\n        return True\n    def insertLast(self, value):\n        if self.count == self.cap:\n            return False\n        self.q[(self.head + self.count) % self.cap] = value\n        self.count += 1\n        return True\n    def deleteFront(self):\n        if self.count == 0:\n            return False\n        self.head = (self.head + 1) % self.cap\n        self.count -= 1\n        return True\n    def deleteLast(self):\n        if self.count == 0:\n            return False\n        self.count -= 1\n        return True\n    def getFront(self):\n        return -1 if self.count == 0 else self.q[self.head]\n    def getRear(self):\n        return -1 if self.count == 0 else self.q[(self.head + self.count - 1) % self.cap]\n    def isEmpty(self):\n        return self.count == 0\n    def isFull(self):\n        return self.count == self.cap', time: 'O(1)', timeWhy: 'both ends update in constant time via modular indexing.', space: 'O(k)', spaceWhy: 'the fixed backing array.', pitfalls: ['Python\u2019s % keeps head in range on decrement; in C++/Java add cap before taking the modulo to avoid negatives.'] }),
  custom: {
    python: { stub: ln('class MyCircularDeque:', '    def __init__(self, k):', '        # Write your code here', '        pass', '    def insertFront(self, value):', '        return False', '    def insertLast(self, value):', '        return False', '    def deleteFront(self):', '        return False', '    def deleteLast(self):', '        return False', '    def getFront(self):', '        return -1', '    def getRear(self):', '        return -1', '    def isEmpty(self):', '        return True', '    def isFull(self):', '        return False'), harness: null },
    javascript: { stub: ln('class MyCircularDeque {', '    constructor(k) {', '        // Write your code here', '    }', '    insertFront(value) { return false; }', '    insertLast(value) { return false; }', '    deleteFront() { return false; }', '    deleteLast() { return false; }', '    getFront() { return -1; }', '    getRear() { return -1; }', '    isEmpty() { return true; }', '    isFull() { return false; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class MyCircularDeque {', 'public:', '    MyCircularDeque(int k) {', '        // Write your code here', '    }', '    bool insertFront(int value) { return false; }', '    bool insertLast(int value) { return false; }', '    bool deleteFront() { return false; }', '    bool deleteLast() { return false; }', '    int getFront() { return -1; }', '    int getRear() { return -1; }', '    bool isEmpty() { return true; }', '    bool isFull() { return false; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class MyCircularDeque {', '    public MyCircularDeque(int k) {', '        // Write your code here', '    }', '    public boolean insertFront(int value) { return false; }', '    public boolean insertLast(int value) { return false; }', '    public boolean deleteFront() { return false; }', '    public boolean deleteLast() { return false; }', '    public int getFront() { return -1; }', '    public int getRear() { return -1; }', '    public boolean isEmpty() { return true; }', '    public boolean isFull() { return false; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'MyCircularDeque', a: [3] }, { name: 'insertLast', a: [1] }, { name: 'insertLast', a: [2] }, { name: 'insertFront', a: [3] }, { name: 'insertFront', a: [4] }, { name: 'getRear', a: [] }, { name: 'isFull', a: [] }, { name: 'deleteLast', a: [] }, { name: 'insertFront', a: [4] }, { name: 'getFront', a: [] }]]];
    for (var k = 0; k < 34; k++) { var ops = [{ name: 'MyCircularDeque', a: [randInt(1, 4)] }], n = randInt(5, 16); for (var i = 0; i < n; i++) { var c = Math.random(); if (c < 0.22) ops.push({ name: 'insertFront', a: [randInt(0, 9)] }); else if (c < 0.44) ops.push({ name: 'insertLast', a: [randInt(0, 9)] }); else if (c < 0.56) ops.push({ name: 'deleteFront', a: [] }); else if (c < 0.68) ops.push({ name: 'deleteLast', a: [] }); else if (c < 0.78) ops.push({ name: 'getFront', a: [] }); else if (c < 0.88) ops.push({ name: 'getRear', a: [] }); else if (c < 0.94) ops.push({ name: 'isEmpty', a: [] }); else ops.push({ name: 'isFull', a: [] }); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var cap = 0, dq = [], res = []; a[0].forEach(function (o) { if (o.name === 'MyCircularDeque') { cap = o.a[0]; dq = []; res.push('null'); } else if (o.name === 'insertFront') { if (dq.length === cap) res.push('false'); else { dq.unshift(o.a[0]); res.push('true'); } } else if (o.name === 'insertLast') { if (dq.length === cap) res.push('false'); else { dq.push(o.a[0]); res.push('true'); } } else if (o.name === 'deleteFront') { if (dq.length === 0) res.push('false'); else { dq.shift(); res.push('true'); } } else if (o.name === 'deleteLast') { if (dq.length === 0) res.push('false'); else { dq.pop(); res.push('true'); } } else if (o.name === 'getFront') res.push(dq.length === 0 ? '-1' : String(dq[0])); else if (o.name === 'getRear') res.push(dq.length === 0 ? '-1' : String(dq[dq.length - 1])); else if (o.name === 'isEmpty') res.push(dq.length === 0 ? 'true' : 'false'); else if (o.name === 'isFull') res.push(dq.length === cap ? 'true' : 'false'); }); return res.join('|'); } });

// ---- Kth Largest Element in a Stream ----
MORE22.push({ slug: 'kth-largest-element-in-a-stream', title: 'Kth Largest Element in a Stream', difficulty: 'easy', topics: ['Heap', 'Design', 'Binary Search Tree'], type: 'OPS',
  desc: '<p>Design a class to find the <code>k</code>th largest element in a stream (the kth largest in sorted order, not the kth distinct). Implement <code>KthLargest(k, nums)</code> which initializes with an integer <code>k</code> and a stream of integers <code>nums</code>, and <code>add(val)</code> which appends <code>val</code> and returns the kth largest element so far.</p>',
  examples: [{ in: 'operations = ["KthLargest","add","add","add","add","add"], values = [[3,[4,5,8,2]],[3],[5],[10],[9],[4]]', out: '[null,4,5,5,8,8]' }],
  constraints: ['1 &lt;= k &lt;= 10^4', 'At least k elements exist when add is queried.', 'At most 10^4 calls to add.'],
  editorial: ED({ intuition: 'You only ever need the k largest values seen so far; the kth largest is the smallest of those. A min-heap of size k keeps exactly them, with the answer sitting at its root.', approach: ['Push all initial numbers into a min-heap, then pop until only k remain.', 'On add, push the new value; if the heap exceeds size k, pop the smallest.', 'The heap root is the kth largest element.'], code: 'import heapq\n\nclass KthLargest:\n    def __init__(self, k, nums):\n        self.k = k\n        self.h = nums\n        heapq.heapify(self.h)\n        while len(self.h) > k:\n            heapq.heappop(self.h)\n    def add(self, val):\n        heapq.heappush(self.h, val)\n        if len(self.h) > self.k:\n            heapq.heappop(self.h)\n        return self.h[0]', time: 'O(log k) per add', timeWhy: 'each add does a heap push/pop bounded by size k.', space: 'O(k)', spaceWhy: 'the heap holds at most k elements.', pitfalls: ['Keep a min-heap (smallest on top), not a max-heap — the kth largest is the minimum of the top k.'] }),
  custom: {
    python: { stub: ln('class KthLargest:', '    def __init__(self, k, nums):', '        # Write your code here', '        pass', '    def add(self, val):', '        return 0'), harness: null },
    javascript: { stub: ln('class KthLargest {', '    constructor(k, nums) {', '        // Write your code here', '    }', '    add(val) { return 0; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class KthLargest {', 'public:', '    KthLargest(int k, vector<int>& nums) {', '        // Write your code here', '    }', '    int add(int val) { return 0; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class KthLargest {', '    public KthLargest(int k, int[] nums) {', '        // Write your code here', '    }', '    public int add(int val) { return 0; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'KthLargest', a: [3, 4, 5, 8, 2] }, { name: 'add', a: [3] }, { name: 'add', a: [5] }, { name: 'add', a: [10] }, { name: 'add', a: [9] }, { name: 'add', a: [4] }]]];
    for (var t = 0; t < 34; t++) { var k = randInt(1, 4), len = k + randInt(0, 4), nums = []; for (var i = 0; i < len; i++) nums.push(randInt(-10, 20)); var ops = [{ name: 'KthLargest', a: [k].concat(nums) }], n = randInt(3, 10); for (var j = 0; j < n; j++) ops.push({ name: 'add', a: [randInt(-10, 20)] }); o.push([ops]); }
    return o;
  },
  ref: function (a) { var k = 0, arr = [], res = []; a[0].forEach(function (o) { if (o.name === 'KthLargest') { k = o.a[0]; arr = o.a.slice(1); res.push('null'); } else if (o.name === 'add') { arr.push(o.a[0]); var s = arr.slice().sort(function (x, y) { return y - x; }); res.push(String(s[k - 1])); } }); return res.join('|'); } });

// ---- Design Parking System ----
MORE22.push({ slug: 'design-parking-system', title: 'Design Parking System', difficulty: 'easy', topics: ['Design', 'Counting', 'Simulation'], type: 'OPS',
  desc: '<p>Design a parking system for a lot with three kinds of spaces: big, medium, and small, with a fixed number of each. Implement <code>ParkingSystem(big, medium, small)</code> and <code>addCar(carType)</code> where <code>carType</code> is 1 (big), 2 (medium), or 3 (small). Return <code>true</code> if there is an available slot of that type (and park the car), otherwise <code>false</code>.</p>',
  examples: [{ in: 'operations = ["ParkingSystem","addCar","addCar","addCar","addCar"], values = [[1,1,0],[1],[2],[3],[1]]', out: '[null,true,true,false,false]' }],
  constraints: ['0 &lt;= big, medium, small &lt;= 1000', 'carType is 1, 2, or 3.', 'At most 1000 calls to addCar.'],
  editorial: ED({ intuition: 'Only the remaining count of each slot type matters. Keep three counters and decrement the right one when a car parks.', approach: ['Store counts indexed by carType (1, 2, 3).', 'addCar checks the counter for that type; if positive, decrement and return true.', 'Otherwise return false.'], code: 'class ParkingSystem:\n    def __init__(self, big, medium, small):\n        self.slots = [0, big, medium, small]\n    def addCar(self, carType):\n        if self.slots[carType] > 0:\n            self.slots[carType] -= 1\n            return True\n        return False', time: 'O(1)', timeWhy: 'each addCar is a single counter check and decrement.', space: 'O(1)', spaceWhy: 'three counters.', pitfalls: ['Index slots by carType directly (1-based) to avoid off-by-one mistakes.'] }),
  custom: {
    python: { stub: ln('class ParkingSystem:', '    def __init__(self, big, medium, small):', '        # Write your code here', '        pass', '    def addCar(self, carType):', '        return False'), harness: null },
    javascript: { stub: ln('class ParkingSystem {', '    constructor(big, medium, small) {', '        // Write your code here', '    }', '    addCar(carType) { return false; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class ParkingSystem {', 'public:', '    ParkingSystem(int big, int medium, int small) {', '        // Write your code here', '    }', '    bool addCar(int carType) { return false; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class ParkingSystem {', '    public ParkingSystem(int big, int medium, int small) {', '        // Write your code here', '    }', '    public boolean addCar(int carType) { return false; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'ParkingSystem', a: [1, 1, 0] }, { name: 'addCar', a: [1] }, { name: 'addCar', a: [2] }, { name: 'addCar', a: [3] }, { name: 'addCar', a: [1] }]]];
    for (var t = 0; t < 34; t++) { var ops = [{ name: 'ParkingSystem', a: [randInt(0, 3), randInt(0, 3), randInt(0, 3)] }], n = randInt(4, 14); for (var i = 0; i < n; i++) ops.push({ name: 'addCar', a: [randInt(1, 3)] }); o.push([ops]); }
    return o;
  },
  ref: function (a) { var slots = [0, 0, 0, 0], res = []; a[0].forEach(function (o) { if (o.name === 'ParkingSystem') { slots = [0, o.a[0], o.a[1], o.a[2]]; res.push('null'); } else if (o.name === 'addCar') { var t = o.a[0]; if (slots[t] > 0) { slots[t]--; res.push('true'); } else res.push('false'); } }); return res.join('|'); } });

// ---- Design Browser History ----
MORE22.push({ slug: 'design-browser-history', title: 'Design Browser History', difficulty: 'medium', topics: ['Array', 'Linked List', 'Stack', 'Design'], type: 'OPS',
  desc: '<p>You have a browser with one tab starting on a homepage. Implement <code>BrowserHistory(homepage)</code>, <code>visit(url)</code> (visits <code>url</code> from the current page and clears all forward history), <code>back(steps)</code> (move back up to <code>steps</code> pages, return the current url), and <code>forward(steps)</code> (move forward up to <code>steps</code> pages, return the current url).</p>',
  examples: [{ in: 'operations = ["BrowserHistory","visit","visit","visit","back","back","forward","visit","forward","back","back"], values = [["leetcode"],["google"],["facebook"],["youtube"],[1],[1],[1],["linkedin"],[2],[2],[7]]', out: '[null,null,null,null,facebook,google,facebook,null,linkedin,google,leetcode]' }],
  constraints: ['1 &lt;= homepage.length, url.length &lt;= 20', '1 &lt;= steps &lt;= 100', 'At most 5000 calls.'],
  editorial: ED({ intuition: 'History is a line of pages with a cursor at the current one. Store the visited pages in a list and an index; visiting truncates everything after the cursor, back/forward just clamp the cursor.', approach: ['Keep a list of urls and a current index, starting with the homepage.', 'visit truncates the list after the current index, appends the url, and advances the index.', 'back/forward move the index by up to steps but clamp to the valid range, returning the url there.'], code: 'class BrowserHistory:\n    def __init__(self, homepage):\n        self.hist = [homepage]\n        self.cur = 0\n    def visit(self, url):\n        self.hist = self.hist[:self.cur + 1]\n        self.hist.append(url)\n        self.cur += 1\n    def back(self, steps):\n        self.cur = max(0, self.cur - steps)\n        return self.hist[self.cur]\n    def forward(self, steps):\n        self.cur = min(len(self.hist) - 1, self.cur + steps)\n        return self.hist[self.cur]', time: 'O(1) amortized', timeWhy: 'back/forward are constant; visit is amortized constant.', space: 'O(n)', spaceWhy: 'stores every page on the current history line.', pitfalls: ['visit must discard forward history, otherwise stale forward pages resurface.'] }),
  custom: {
    python: { stub: ln('class BrowserHistory:', '    def __init__(self, homepage):', '        # Write your code here', '        pass', '    def visit(self, url):', '        pass', '    def back(self, steps):', '        return ""', '    def forward(self, steps):', '        return ""'), harness: null },
    javascript: { stub: ln('class BrowserHistory {', '    constructor(homepage) {', '        // Write your code here', '    }', '    visit(url) {}', '    back(steps) { return ""; }', '    forward(steps) { return ""; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class BrowserHistory {', 'public:', '    BrowserHistory(string homepage) {', '        // Write your code here', '    }', '    void visit(string url) {}', '    string back(int steps) { return ""; }', '    string forward(int steps) { return ""; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class BrowserHistory {', '    public BrowserHistory(String homepage) {', '        // Write your code here', '    }', '    public void visit(String url) {}', '    public String back(int steps) { return ""; }', '    public String forward(int steps) { return ""; }', '}'), harness: null },
  },
  gen: function () {
    var urls = ['leetcode', 'google', 'facebook', 'youtube', 'linkedin', 'amazon', 'github', 'twitch'];
    var o = [[[{ name: 'BrowserHistory', a: ['leetcode'] }, { name: 'visit', a: ['google'] }, { name: 'visit', a: ['facebook'] }, { name: 'visit', a: ['youtube'] }, { name: 'back', a: [1] }, { name: 'back', a: [1] }, { name: 'forward', a: [1] }, { name: 'visit', a: ['linkedin'] }, { name: 'forward', a: [2] }, { name: 'back', a: [2] }, { name: 'back', a: [7] }]]];
    for (var t = 0; t < 34; t++) { var ops = [{ name: 'BrowserHistory', a: [urls[randInt(0, urls.length - 1)]] }], n = randInt(4, 14); for (var i = 0; i < n; i++) { var c = Math.random(); if (c < 0.45) ops.push({ name: 'visit', a: [urls[randInt(0, urls.length - 1)]] }); else if (c < 0.72) ops.push({ name: 'back', a: [randInt(1, 5)] }); else ops.push({ name: 'forward', a: [randInt(1, 5)] }); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var hist = [], cur = 0, res = []; a[0].forEach(function (o) { if (o.name === 'BrowserHistory') { hist = [o.a[0]]; cur = 0; res.push('null'); } else if (o.name === 'visit') { hist = hist.slice(0, cur + 1); hist.push(o.a[0]); cur++; res.push('null'); } else if (o.name === 'back') { cur = Math.max(0, cur - o.a[0]); res.push(hist[cur]); } else if (o.name === 'forward') { cur = Math.min(hist.length - 1, cur + o.a[0]); res.push(hist[cur]); } }); return res.join('|'); } });

// ---- Number of Recent Calls ----
MORE22.push({ slug: 'number-of-recent-calls', title: 'Number of Recent Calls', difficulty: 'easy', topics: ['Queue', 'Design', 'Data Stream'], type: 'OPS',
  desc: '<p>Implement <code>RecentCounter</code> that counts recent requests within a time window. Implement <code>ping(t)</code> which records a request at time <code>t</code> (in milliseconds) and returns the number of requests that happened in the inclusive range <code>[t - 3000, t]</code>. Every call to <code>ping</code> uses a strictly larger <code>t</code> than the previous call.</p>',
  examples: [{ in: 'operations = ["RecentCounter","ping","ping","ping","ping"], values = [[],[1],[100],[3001],[3002]]', out: '[null,1,2,3,3]' }],
  constraints: ['1 &lt;= t &lt;= 10^9', 'Each call to ping uses a strictly increasing t.', 'At most 10^4 calls to ping.'],
  editorial: ED({ intuition: 'Because timestamps only increase, requests older than t - 3000 can never count again. A queue lets you drop those stale timestamps from the front and report the size of what remains.', approach: ['Keep a queue of timestamps.', 'On ping(t), enqueue t, then dequeue from the front while the front is < t - 3000.', 'Return the queue size — the number of requests in [t - 3000, t].'], code: 'from collections import deque\n\nclass RecentCounter:\n    def __init__(self):\n        self.q = deque()\n    def ping(self, t):\n        self.q.append(t)\n        while self.q[0] < t - 3000:\n            self.q.popleft()\n        return len(self.q)', time: 'O(1) amortized', timeWhy: 'each timestamp is enqueued and dequeued at most once.', space: 'O(w)', spaceWhy: 'the queue holds only timestamps inside the 3000 ms window.', pitfalls: ['The window is inclusive of t - 3000, so drop only strictly smaller timestamps.'] }),
  custom: {
    python: { stub: ln('class RecentCounter:', '    def __init__(self):', '        # Write your code here', '        pass', '    def ping(self, t):', '        return 0'), harness: null },
    javascript: { stub: ln('class RecentCounter {', '    constructor() {', '        // Write your code here', '    }', '    ping(t) { return 0; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class RecentCounter {', 'public:', '    RecentCounter() {', '        // Write your code here', '    }', '    int ping(int t) { return 0; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class RecentCounter {', '    public RecentCounter() {', '        // Write your code here', '    }', '    public int ping(int t) { return 0; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'RecentCounter', a: [] }, { name: 'ping', a: [1] }, { name: 'ping', a: [100] }, { name: 'ping', a: [3001] }, { name: 'ping', a: [3002] }]]];
    for (var t = 0; t < 34; t++) { var ops = [{ name: 'RecentCounter', a: [] }], cur = randInt(1, 50), n = randInt(3, 12); for (var i = 0; i < n; i++) { ops.push({ name: 'ping', a: [cur] }); cur += randInt(1, 2000); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var q = [], res = []; a[0].forEach(function (o) { if (o.name === 'RecentCounter') { q = []; res.push('null'); } else if (o.name === 'ping') { var t = o.a[0]; q.push(t); while (q[0] < t - 3000) q.shift(); res.push(String(q.length)); } }); return res.join('|'); } });

// ---- Design a Stack With Increment Operation ----
MORE22.push({ slug: 'design-a-stack-with-increment-operation', title: 'Design a Stack With Increment Operation', difficulty: 'medium', topics: ['Stack', 'Array', 'Design'], type: 'OPS',
  desc: '<p>Design a stack with a bulk-increment operation. Implement <code>CustomStack(maxSize)</code> and: <code>push(x)</code> (adds <code>x</code> only if the stack size is less than <code>maxSize</code>), <code>pop()</code> (removes and returns the top element, or <code>-1</code> if empty), and <code>increment(k, val)</code> (adds <code>val</code> to the bottom <code>k</code> elements — or all of them if the stack has fewer than <code>k</code>).</p>',
  examples: [{ in: 'operations = ["CustomStack","push","push","pop","push","push","push","increment","increment","pop","pop","pop","pop"], values = [[3],[1],[2],[],[2],[3],[4],[5,100],[2,100],[],[],[],[]]', out: '[null,null,null,2,null,null,null,null,null,103,202,201,-1]' }],
  constraints: ['1 &lt;= maxSize &lt;= 1000', '1 &lt;= x, val &lt;= 100', '0 &lt;= k &lt;= 1000', 'At most 1000 calls.'],
  editorial: ED({ intuition: 'A plain array is the stack. The only twist is increment: naively adding val to k elements is O(k), but you can defer it with a lazy increment array so each op is O(1).', approach: ['Back the stack with an array; push respects maxSize, pop returns -1 when empty.', 'Keep a parallel <code>inc</code> array where inc[i] is added when element i is popped, and propagated to inc[i-1].', 'increment(k, val) just adds val to inc[min(k, size) - 1] — the bottom k elements inherit it on the way out.'], code: 'class CustomStack:\n    def __init__(self, maxSize):\n        self.cap = maxSize\n        self.st = []\n        self.inc = []\n    def push(self, x):\n        if len(self.st) < self.cap:\n            self.st.append(x)\n            self.inc.append(0)\n    def pop(self):\n        if not self.st:\n            return -1\n        i = len(self.st) - 1\n        add = self.inc.pop()\n        if i > 0:\n            self.inc[i - 1] += add\n        return self.st.pop() + add\n    def increment(self, k, val):\n        i = min(k, len(self.st)) - 1\n        if i >= 0:\n            self.inc[i] += val', time: 'O(1)', timeWhy: 'push, pop, and increment are all constant time with the lazy increment array.', space: 'O(maxSize)', spaceWhy: 'the value and increment arrays.', pitfalls: ['A direct loop in increment is also accepted but O(k); the lazy array keeps it O(1).'] }),
  custom: {
    python: { stub: ln('class CustomStack:', '    def __init__(self, maxSize):', '        # Write your code here', '        pass', '    def push(self, x):', '        pass', '    def pop(self):', '        return -1', '    def increment(self, k, val):', '        pass'), harness: null },
    javascript: { stub: ln('class CustomStack {', '    constructor(maxSize) {', '        // Write your code here', '    }', '    push(x) {}', '    pop() { return -1; }', '    increment(k, val) {}', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class CustomStack {', 'public:', '    CustomStack(int maxSize) {', '        // Write your code here', '    }', '    void push(int x) {}', '    int pop() { return -1; }', '    void increment(int k, int val) {}', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class CustomStack {', '    public CustomStack(int maxSize) {', '        // Write your code here', '    }', '    public void push(int x) {}', '    public int pop() { return -1; }', '    public void increment(int k, int val) {}', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'CustomStack', a: [3] }, { name: 'push', a: [1] }, { name: 'push', a: [2] }, { name: 'pop', a: [] }, { name: 'push', a: [2] }, { name: 'push', a: [3] }, { name: 'push', a: [4] }, { name: 'increment', a: [5, 100] }, { name: 'increment', a: [2, 100] }, { name: 'pop', a: [] }, { name: 'pop', a: [] }, { name: 'pop', a: [] }, { name: 'pop', a: [] }]]];
    for (var t = 0; t < 34; t++) { var ops = [{ name: 'CustomStack', a: [randInt(1, 5)] }], n = randInt(5, 16); for (var i = 0; i < n; i++) { var c = Math.random(); if (c < 0.5) ops.push({ name: 'push', a: [randInt(1, 100)] }); else if (c < 0.78) ops.push({ name: 'pop', a: [] }); else ops.push({ name: 'increment', a: [randInt(0, 6), randInt(1, 100)] }); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var cap = 0, st = [], res = []; a[0].forEach(function (o) { if (o.name === 'CustomStack') { cap = o.a[0]; st = []; res.push('null'); } else if (o.name === 'push') { if (st.length < cap) st.push(o.a[0]); res.push('null'); } else if (o.name === 'pop') { res.push(st.length ? String(st.pop()) : '-1'); } else if (o.name === 'increment') { var k = o.a[0], val = o.a[1], m = Math.min(k, st.length); for (var i = 0; i < m; i++) st[i] += val; res.push('null'); } }); return res.join('|'); } });

// ---- Range Sum Query - Immutable ----
MORE22.push({ slug: 'range-sum-query-immutable', title: 'Range Sum Query - Immutable', difficulty: 'easy', topics: ['Array', 'Prefix Sum', 'Design'], type: 'OPS',
  desc: '<p>Given an integer array <code>nums</code>, handle multiple queries of the sum of the elements between indices <code>left</code> and <code>right</code> inclusive. Implement <code>NumArray(nums)</code> and <code>sumRange(left, right)</code> which returns the sum <code>nums[left] + ... + nums[right]</code>.</p>',
  examples: [{ in: 'operations = ["NumArray","sumRange","sumRange","sumRange"], values = [[-2,0,3,-5,2,-1],[0,2],[2,5],[0,5]]', out: '[null,1,-1,-3]' }],
  constraints: ['1 &lt;= nums.length &lt;= 10^4', '-10^5 &lt;= nums[i] &lt;= 10^5', '0 &lt;= left &lt;= right &lt; nums.length', 'At most 10^4 calls to sumRange.'],
  editorial: ED({ intuition: 'Recomputing a range sum each query is O(n). Precompute a prefix-sum array once so any range sum becomes a single subtraction.', approach: ['Build prefix[i] = sum of the first i elements in the constructor.', 'sumRange(left, right) returns prefix[right + 1] - prefix[left].', 'Every query is then O(1).'], code: 'class NumArray:\n    def __init__(self, nums):\n        self.pre = [0]\n        for x in nums:\n            self.pre.append(self.pre[-1] + x)\n    def sumRange(self, left, right):\n        return self.pre[right + 1] - self.pre[left]', time: 'O(1) per query', timeWhy: 'the prefix array is built once in O(n); each sumRange is a subtraction.', space: 'O(n)', spaceWhy: 'the prefix-sum array.', pitfalls: ['Use prefix[right + 1] so the right endpoint is included.'] }),
  custom: {
    python: { stub: ln('class NumArray:', '    def __init__(self, nums):', '        # Write your code here', '        pass', '    def sumRange(self, left, right):', '        return 0'), harness: null },
    javascript: { stub: ln('class NumArray {', '    constructor(nums) {', '        // Write your code here', '    }', '    sumRange(left, right) { return 0; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class NumArray {', 'public:', '    NumArray(vector<int>& nums) {', '        // Write your code here', '    }', '    int sumRange(int left, int right) { return 0; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class NumArray {', '    public NumArray(int[] nums) {', '        // Write your code here', '    }', '    public int sumRange(int left, int right) { return 0; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'NumArray', a: [-2, 0, 3, -5, 2, -1] }, { name: 'sumRange', a: [0, 2] }, { name: 'sumRange', a: [2, 5] }, { name: 'sumRange', a: [0, 5] }]]];
    for (var t = 0; t < 34; t++) { var len = randInt(1, 8), nums = []; for (var i = 0; i < len; i++) nums.push(randInt(-9, 9)); var ops = [{ name: 'NumArray', a: nums.slice() }], n = randInt(3, 10); for (var j = 0; j < n; j++) { var l = randInt(0, len - 1), r = randInt(l, len - 1); ops.push({ name: 'sumRange', a: [l, r] }); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var arr = [], res = []; a[0].forEach(function (o) { if (o.name === 'NumArray') { arr = o.a.slice(); res.push('null'); } else if (o.name === 'sumRange') { var l = o.a[0], r = o.a[1], s = 0; for (var i = l; i <= r; i++) s += arr[i]; res.push(String(s)); } }); return res.join('|'); } });

// ---- Logger Rate Limiter ----
MORE22.push({ slug: 'logger-rate-limiter', title: 'Logger Rate Limiter', difficulty: 'easy', topics: ['Hash Table', 'Design', 'Data Stream'], type: 'OPS',
  desc: '<p>Design a logger that limits each unique message to being printed at most once every 10 seconds. Implement <code>Logger()</code> and <code>shouldPrintMessage(timestamp, message)</code>, which returns <code>true</code> if the message should be printed at the given <code>timestamp</code> (in seconds), and <code>false</code> otherwise. A message printed at time <code>t</code> may next be printed at <code>t + 10</code> or later.</p>',
  examples: [{ in: 'operations = ["Logger","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage","shouldPrintMessage"], values = [[],[1,"foo"],[2,"bar"],[3,"foo"],[8,"bar"],[10,"foo"],[11,"foo"]]', out: '[null,true,true,false,false,false,true]' }],
  constraints: ['0 &lt;= timestamp &lt;= 10^9', 'Every timestamp is greater than or equal to the previous.', 'At most 10^4 calls.'],
  editorial: ED({ intuition: 'For each message you only need the next timestamp at which it may be printed again. Store that in a hash map and compare against the incoming timestamp.', approach: ['Keep a map from message to the earliest allowed next timestamp.', 'shouldPrintMessage returns true when the message is new or its allowed time has arrived, then records timestamp + 10.', 'Otherwise it returns false without updating.'], code: 'class Logger:\n    def __init__(self):\n        self.next_ok = {}\n    def shouldPrintMessage(self, timestamp, message):\n        if message not in self.next_ok or timestamp >= self.next_ok[message]:\n            self.next_ok[message] = timestamp + 10\n            return True\n        return False', time: 'O(1)', timeWhy: 'each call is a single hash-map lookup and update.', space: 'O(m)', spaceWhy: 'one entry per distinct message seen.', pitfalls: ['Only update the allowed time when returning true, otherwise the window keeps sliding forward.'] }),
  custom: {
    python: { stub: ln('class Logger:', '    def __init__(self):', '        # Write your code here', '        pass', '    def shouldPrintMessage(self, timestamp, message):', '        return False'), harness: null },
    javascript: { stub: ln('class Logger {', '    constructor() {', '        // Write your code here', '    }', '    shouldPrintMessage(timestamp, message) { return false; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class Logger {', 'public:', '    Logger() {', '        // Write your code here', '    }', '    bool shouldPrintMessage(int timestamp, string message) { return false; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class Logger {', '    public Logger() {', '        // Write your code here', '    }', '    public boolean shouldPrintMessage(int timestamp, String message) { return false; }', '}'), harness: null },
  },
  gen: function () {
    var msgs = ['foo', 'bar', 'baz', 'qux'];
    var o = [[[{ name: 'Logger', a: [] }, { name: 'shouldPrintMessage', a: [1, 'foo'] }, { name: 'shouldPrintMessage', a: [2, 'bar'] }, { name: 'shouldPrintMessage', a: [3, 'foo'] }, { name: 'shouldPrintMessage', a: [8, 'bar'] }, { name: 'shouldPrintMessage', a: [10, 'foo'] }, { name: 'shouldPrintMessage', a: [11, 'foo'] }]]];
    for (var t = 0; t < 34; t++) { var ops = [{ name: 'Logger', a: [] }], cur = randInt(0, 5), n = randInt(4, 14); for (var i = 0; i < n; i++) { ops.push({ name: 'shouldPrintMessage', a: [cur, msgs[randInt(0, msgs.length - 1)]] }); cur += randInt(0, 6); } o.push([ops]); }
    return o;
  },
  ref: function (a) { var nextOk = {}, res = []; a[0].forEach(function (o) { if (o.name === 'Logger') { nextOk = {}; res.push('null'); } else if (o.name === 'shouldPrintMessage') { var ts = o.a[0], msg = o.a[1]; if (!nextOk.hasOwnProperty(msg) || ts >= nextOk[msg]) { nextOk[msg] = ts + 10; res.push('true'); } else res.push('false'); } }); return res.join('|'); } });

// ---- Design Hit Counter ----
MORE22.push({ slug: 'design-hit-counter', title: 'Design Hit Counter', difficulty: 'medium', topics: ['Queue', 'Design', 'Binary Search', 'Data Stream'], type: 'OPS',
  desc: '<p>Design a hit counter that counts hits received in the past 5 minutes (300 seconds). Implement <code>HitCounter()</code>, <code>hit(timestamp)</code> which records a hit at the given <code>timestamp</code> (in seconds), and <code>getHits(timestamp)</code> which returns the number of hits in the past 300 seconds — that is, hits with a recorded time in the range <code>(timestamp - 300, timestamp]</code>. Calls are made in non-decreasing time order.</p>',
  examples: [{ in: 'operations = ["HitCounter","hit","hit","hit","getHits","hit","getHits","getHits"], values = [[],[1],[2],[3],[4],[300],[300],[301]]', out: '[null,null,null,null,3,null,4,3]' }],
  constraints: ['1 &lt;= timestamp &lt;= 2*10^9', 'All calls are made with non-decreasing timestamps.', 'At most 300 calls per getHits window in the basic version.'],
  editorial: ED({ intuition: 'Only hits within the trailing 300-second window matter. Since timestamps never decrease, older hits can be dropped from the front of a queue.', approach: ['Store hit timestamps in a queue in arrival order.', 'On getHits(t), evict timestamps from the front that are &lt;= t - 300.', 'Return the queue size — the hits remaining in (t - 300, t].'], code: 'from collections import deque\n\nclass HitCounter:\n    def __init__(self):\n        self.q = deque()\n    def hit(self, timestamp):\n        self.q.append(timestamp)\n    def getHits(self, timestamp):\n        while self.q and self.q[0] <= timestamp - 300:\n            self.q.popleft()\n        return len(self.q)', time: 'O(1) amortized', timeWhy: 'each timestamp is enqueued and evicted at most once.', space: 'O(w)', spaceWhy: 'the queue holds only hits inside the 300 s window.', pitfalls: ['The window excludes timestamp - 300, so evict hits with time &lt;= t - 300.'] }),
  custom: {
    python: { stub: ln('class HitCounter:', '    def __init__(self):', '        # Write your code here', '        pass', '    def hit(self, timestamp):', '        pass', '    def getHits(self, timestamp):', '        return 0'), harness: null },
    javascript: { stub: ln('class HitCounter {', '    constructor() {', '        // Write your code here', '    }', '    hit(timestamp) {}', '    getHits(timestamp) { return 0; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class HitCounter {', 'public:', '    HitCounter() {', '        // Write your code here', '    }', '    void hit(int timestamp) {}', '    int getHits(int timestamp) { return 0; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class HitCounter {', '    public HitCounter() {', '        // Write your code here', '    }', '    public void hit(int timestamp) {}', '    public int getHits(int timestamp) { return 0; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'HitCounter', a: [] }, { name: 'hit', a: [1] }, { name: 'hit', a: [2] }, { name: 'hit', a: [3] }, { name: 'getHits', a: [4] }, { name: 'hit', a: [300] }, { name: 'getHits', a: [300] }, { name: 'getHits', a: [301] }]]];
    for (var t = 0; t < 34; t++) { var ops = [{ name: 'HitCounter', a: [] }], cur = randInt(1, 10), n = randInt(4, 14); for (var i = 0; i < n; i++) { if (Math.random() < 0.6) { ops.push({ name: 'hit', a: [cur] }); cur += randInt(0, 120); } else { ops.push({ name: 'getHits', a: [cur] }); cur += randInt(0, 120); } } o.push([ops]); }
    return o;
  },
  ref: function (a) { var q = [], res = []; a[0].forEach(function (o) { if (o.name === 'HitCounter') { q = []; res.push('null'); } else if (o.name === 'hit') { q.push(o.a[0]); res.push('null'); } else if (o.name === 'getHits') { var t = o.a[0]; while (q.length && q[0] <= t - 300) q.shift(); res.push(String(q.length)); } }); return res.join('|'); } });

// ---- Max Stack ----
MORE22.push({ slug: 'max-stack', title: 'Max Stack', difficulty: 'hard', topics: ['Stack', 'Design', 'Sorted Set'], type: 'OPS',
  desc: '<p>Design a stack that supports finding and removing the maximum element. Implement <code>MaxStack()</code> and: <code>push(x)</code>, <code>top()</code> (returns the top element), <code>pop()</code> (removes and returns the top element), <code>peekMax()</code> (returns the maximum element), and <code>popMax()</code> (removes and returns the maximum element; if there are ties, remove the one closest to the top).</p>',
  examples: [{ in: 'operations = ["MaxStack","push","push","push","top","popMax","top","peekMax","pop","top"], values = [[],[5],[1],[5],[],[],[],[],[],[]]', out: '[null,null,null,null,5,5,1,5,1,5]' }],
  constraints: ['-10^7 &lt;= x &lt;= 10^7', 'At most 10^4 calls.', 'top, pop, peekMax, popMax are only called on a non-empty stack.'],
  editorial: ED({ intuition: 'A normal stack handles push/top/pop. The extra requirement is fast max lookup and removal of the top-most maximum, which needs the stack order preserved even after removing an element from the middle.', approach: ['Keep the values in a stack (a list) for ordering.', 'top and pop act on the end; peekMax scans (or a balanced structure tracks) the maximum.', 'popMax finds the last occurrence of the maximum and removes it, preserving the order of the rest.'], code: 'class MaxStack:\n    def __init__(self):\n        self.st = []\n    def push(self, x):\n        self.st.append(x)\n    def top(self):\n        return self.st[-1]\n    def pop(self):\n        return self.st.pop()\n    def peekMax(self):\n        return max(self.st)\n    def popMax(self):\n        m = max(self.st)\n        for i in range(len(self.st) - 1, -1, -1):\n            if self.st[i] == m:\n                self.st.pop(i)\n                return m', time: 'O(n) for max ops', timeWhy: 'peekMax/popMax scan the stack; push/top/pop are O(1). A balanced BST plus doubly-linked list makes max ops O(log n).', space: 'O(n)', spaceWhy: 'the stack holds all elements.', pitfalls: ['popMax must remove the top-most maximum (scan from the end), not the first occurrence.'] }),
  custom: {
    python: { stub: ln('class MaxStack:', '    def __init__(self):', '        # Write your code here', '        pass', '    def push(self, x):', '        pass', '    def top(self):', '        return 0', '    def pop(self):', '        return 0', '    def peekMax(self):', '        return 0', '    def popMax(self):', '        return 0'), harness: null },
    javascript: { stub: ln('class MaxStack {', '    constructor() {', '        // Write your code here', '    }', '    push(x) {}', '    top() { return 0; }', '    pop() { return 0; }', '    peekMax() { return 0; }', '    popMax() { return 0; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class MaxStack {', 'public:', '    MaxStack() {', '        // Write your code here', '    }', '    void push(int x) {}', '    int top() { return 0; }', '    int pop() { return 0; }', '    int peekMax() { return 0; }', '    int popMax() { return 0; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class MaxStack {', '    public MaxStack() {', '        // Write your code here', '    }', '    public void push(int x) {}', '    public int top() { return 0; }', '    public int pop() { return 0; }', '    public int peekMax() { return 0; }', '    public int popMax() { return 0; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'MaxStack', a: [] }, { name: 'push', a: [5] }, { name: 'push', a: [1] }, { name: 'push', a: [5] }, { name: 'top', a: [] }, { name: 'popMax', a: [] }, { name: 'top', a: [] }, { name: 'peekMax', a: [] }, { name: 'pop', a: [] }, { name: 'top', a: [] }]]];
    for (var k = 0; k < 34; k++) { var ops = [{ name: 'MaxStack', a: [] }], size = 0, n = randInt(4, 14); for (var i = 0; i < n; i++) { if (size === 0 || Math.random() < 0.45) { ops.push({ name: 'push', a: [randInt(-9, 9)] }); size++; } else { var c = Math.random(); if (c < 0.25) { ops.push({ name: 'top', a: [] }); } else if (c < 0.5) { ops.push({ name: 'pop', a: [] }); size--; } else if (c < 0.75) { ops.push({ name: 'peekMax', a: [] }); } else { ops.push({ name: 'popMax', a: [] }); size--; } } } o.push([ops]); }
    return o;
  },
  ref: function (a) { var st = [], res = []; a[0].forEach(function (o) { if (o.name === 'MaxStack') { st = []; res.push('null'); } else if (o.name === 'push') { st.push(o.a[0]); res.push('null'); } else if (o.name === 'top') res.push(String(st[st.length - 1])); else if (o.name === 'pop') res.push(String(st.pop())); else if (o.name === 'peekMax') res.push(String(Math.max.apply(null, st))); else if (o.name === 'popMax') { var m = Math.max.apply(null, st); for (var i = st.length - 1; i >= 0; i--) { if (st[i] === m) { st.splice(i, 1); break; } } res.push(String(m)); } }); return res.join('|'); } });

// ---- Find Median from Data Stream ----
MORE22.push({ slug: 'find-median-from-data-stream', title: 'Find Median from Data Stream', difficulty: 'hard', topics: ['Heap', 'Design', 'Two Pointers', 'Sorting'], type: 'OPS',
  desc: '<p>The median is the middle value in an ordered list; for an even-sized list it is the average of the two middle values. Design a structure that supports a stream of integers. Implement <code>MedianFinder</code> with <code>addNum(num)</code> to add an integer, and <code>findMedian()</code> to return the median of all elements so far. Medians are reported to <strong>one decimal place</strong> (e.g. <code>2.0</code>, <code>1.5</code>).</p>',
  examples: [{ in: 'operations = ["MedianFinder","addNum","addNum","findMedian","addNum","findMedian"], values = [[],[1],[2],[],[3],[]]', out: '[null,null,null,1.5,null,2.0]' }],
  constraints: ['-10^5 &lt;= num &lt;= 10^5', 'At most 5*10^4 calls to addNum and findMedian.', 'findMedian is only called on a non-empty structure.'],
  editorial: ED({ intuition: 'Keep the lower half of the numbers in a max-heap and the upper half in a min-heap, balanced in size. The median is then either the top of one heap (odd count) or the average of both tops (even count) — all in O(log n) per insert.', approach: ['Push the new value into the max-heap (lower half), then move its top into the min-heap so ordering holds.', 'If the min-heap grows larger, move its top back so the max-heap has equal or one more element.', 'findMedian returns the max-heap top when the total is odd, else the average of the two tops.'], code: 'import heapq\nclass MedianFinder:\n    def __init__(self):\n        self.lo = []  # max-heap (store negatives)\n        self.hi = []  # min-heap\n    def addNum(self, num):\n        heapq.heappush(self.lo, -num)\n        heapq.heappush(self.hi, -heapq.heappop(self.lo))\n        if len(self.hi) > len(self.lo):\n            heapq.heappush(self.lo, -heapq.heappop(self.hi))\n    def findMedian(self):\n        if len(self.lo) > len(self.hi):\n            return float(-self.lo[0])\n        return (-self.lo[0] + self.hi[0]) / 2.0', time: 'O(log n) per addNum', timeWhy: 'each insert does a constant number of heap pushes/pops; findMedian is O(1).', space: 'O(n)', spaceWhy: 'the two heaps together store every number.', pitfalls: ['Rebalance after every insert so the two heaps never differ in size by more than one.', 'For even counts, average as a float so 1 and 2 give 1.5, not 1.'] }),
  custom: {
    python: { stub: ln('import heapq', '', 'class MedianFinder:', '    def __init__(self):', '        # Write your code here', '        pass', '    def addNum(self, num):', '        pass', '    def findMedian(self):', '        return 0.0'), harness: null },
    javascript: { stub: ln('class MedianFinder {', '    constructor() {', '        // Write your code here', '    }', '    addNum(num) {}', '    findMedian() { return 0; }', '}'), harness: null },
    cpp: { stub: ln('#include <bits/stdc++.h>', 'using namespace std;', '', 'class MedianFinder {', 'public:', '    MedianFinder() {', '        // Write your code here', '    }', '    void addNum(int num) {}', '    double findMedian() { return 0; }', '};'), harness: null },
    java: { stub: ln('import java.util.*;', '', 'class MedianFinder {', '    public MedianFinder() {', '        // Write your code here', '    }', '    public void addNum(int num) {}', '    public double findMedian() { return 0; }', '}'), harness: null },
  },
  gen: function () {
    var o = [[[{ name: 'MedianFinder', a: [] }, { name: 'addNum', a: [1] }, { name: 'addNum', a: [2] }, { name: 'findMedian', a: [] }, { name: 'addNum', a: [3] }, { name: 'findMedian', a: [] }]]];
    for (var k = 0; k < 34; k++) { var ops = [{ name: 'MedianFinder', a: [] }], size = 0, n = randInt(3, 14); for (var i = 0; i < n; i++) { if (size === 0 || Math.random() < 0.6) { ops.push({ name: 'addNum', a: [randInt(-20, 20)] }); size++; } else { ops.push({ name: 'findMedian', a: [] }); } } ops.push({ name: 'findMedian', a: [] }); o.push([ops]); }
    return o;
  },
  ref: function (a) { var arr = [], res = []; a[0].forEach(function (o) { if (o.name === 'MedianFinder') { arr = []; res.push('null'); } else if (o.name === 'addNum') { var x = o.a[0], lo = 0, hi = arr.length; while (lo < hi) { var m = (lo + hi) >> 1; if (arr[m] < x) lo = m + 1; else hi = m; } arr.splice(lo, 0, x); res.push('null'); } else if (o.name === 'findMedian') { var n = arr.length, med; if (n % 2 === 1) med = arr[(n - 1) / 2]; else med = (arr[n / 2 - 1] + arr[n / 2]) / 2; res.push(med.toFixed(1)); } }); return res.join('|'); } });

// ---- wire the ops-replay harness into each design problem ----
function attach(slug, cls, py, js, cpp, java) {
  var p = MORE22.filter(function (x) { return x.slug === slug; })[0];
  var h = opsHarness(cls, py, js, cpp, java);
  p.custom.python.harness = h.python;
  p.custom.javascript.harness = h.javascript;
  p.custom.cpp.harness = h.cpp;
  p.custom.java.harness = h.java;
}

attach('implement-queue-using-stacks', 'MyQueue',
  ln("        if _op=='MyQueue': _o=MyQueue(); _res.append('null')", "        elif _op=='push': _o.push(int(_p[1])); _res.append('null')", "        elif _op=='pop': _res.append(str(_o.pop()))", "        elif _op=='peek': _res.append(str(_o.peek()))", "        elif _op=='empty': _res.append('true' if _o.empty() else 'false')"),
  ln("  if(_op==='MyQueue'){_o=new MyQueue();_res.push('null');}", "  else if(_op==='push'){_o.push(+_p[1]);_res.push('null');}", "  else if(_op==='pop'){_res.push(String(_o.pop()));}", "  else if(_op==='peek'){_res.push(String(_o.peek()));}", "  else if(_op==='empty'){_res.push(_o.empty()?'true':'false');}"),
  ln('   if(_op=="MyQueue"){_o=new MyQueue();_res.push_back("null");}', '   else if(_op=="push"){int _x;_is>>_x;_o->push(_x);_res.push_back("null");}', '   else if(_op=="pop"){_res.push_back(to_string(_o->pop()));}', '   else if(_op=="peek"){_res.push_back(to_string(_o->peek()));}', '   else if(_op=="empty"){_res.push_back(_o->empty()?"true":"false");}'),
  ln('        if(op.equals("MyQueue")){o=new MyQueue();res.add("null");}', '        else if(op.equals("push")){o.push(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("pop")){res.add(String.valueOf(o.pop()));}', '        else if(op.equals("peek")){res.add(String.valueOf(o.peek()));}', '        else if(op.equals("empty")){res.add(o.empty()?"true":"false");}'));

attach('implement-stack-using-queues', 'MyStack',
  ln("        if _op=='MyStack': _o=MyStack(); _res.append('null')", "        elif _op=='push': _o.push(int(_p[1])); _res.append('null')", "        elif _op=='pop': _res.append(str(_o.pop()))", "        elif _op=='top': _res.append(str(_o.top()))", "        elif _op=='empty': _res.append('true' if _o.empty() else 'false')"),
  ln("  if(_op==='MyStack'){_o=new MyStack();_res.push('null');}", "  else if(_op==='push'){_o.push(+_p[1]);_res.push('null');}", "  else if(_op==='pop'){_res.push(String(_o.pop()));}", "  else if(_op==='top'){_res.push(String(_o.top()));}", "  else if(_op==='empty'){_res.push(_o.empty()?'true':'false');}"),
  ln('   if(_op=="MyStack"){_o=new MyStack();_res.push_back("null");}', '   else if(_op=="push"){int _x;_is>>_x;_o->push(_x);_res.push_back("null");}', '   else if(_op=="pop"){_res.push_back(to_string(_o->pop()));}', '   else if(_op=="top"){_res.push_back(to_string(_o->top()));}', '   else if(_op=="empty"){_res.push_back(_o->empty()?"true":"false");}'),
  ln('        if(op.equals("MyStack")){o=new MyStack();res.add("null");}', '        else if(op.equals("push")){o.push(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("pop")){res.add(String.valueOf(o.pop()));}', '        else if(op.equals("top")){res.add(String.valueOf(o.top()));}', '        else if(op.equals("empty")){res.add(o.empty()?"true":"false");}'));

attach('design-hashmap', 'MyHashMap',
  ln("        if _op=='MyHashMap': _o=MyHashMap(); _res.append('null')", "        elif _op=='put': _o.put(int(_p[1]),int(_p[2])); _res.append('null')", "        elif _op=='get': _res.append(str(_o.get(int(_p[1]))))", "        elif _op=='remove': _o.remove(int(_p[1])); _res.append('null')"),
  ln("  if(_op==='MyHashMap'){_o=new MyHashMap();_res.push('null');}", "  else if(_op==='put'){_o.put(+_p[1],+_p[2]);_res.push('null');}", "  else if(_op==='get'){_res.push(String(_o.get(+_p[1])));}", "  else if(_op==='remove'){_o.remove(+_p[1]);_res.push('null');}"),
  ln('   if(_op=="MyHashMap"){_o=new MyHashMap();_res.push_back("null");}', '   else if(_op=="put"){int _k,_v;_is>>_k>>_v;_o->put(_k,_v);_res.push_back("null");}', '   else if(_op=="get"){int _k;_is>>_k;_res.push_back(to_string(_o->get(_k)));}', '   else if(_op=="remove"){int _k;_is>>_k;_o->remove(_k);_res.push_back("null");}'),
  ln('        if(op.equals("MyHashMap")){o=new MyHashMap();res.add("null");}', '        else if(op.equals("put")){o.put(Integer.parseInt(p[1]),Integer.parseInt(p[2]));res.add("null");}', '        else if(op.equals("get")){res.add(String.valueOf(o.get(Integer.parseInt(p[1]))));}', '        else if(op.equals("remove")){o.remove(Integer.parseInt(p[1]));res.add("null");}'));

attach('design-hashset', 'MyHashSet',
  ln("        if _op=='MyHashSet': _o=MyHashSet(); _res.append('null')", "        elif _op=='add': _o.add(int(_p[1])); _res.append('null')", "        elif _op=='contains': _res.append('true' if _o.contains(int(_p[1])) else 'false')", "        elif _op=='remove': _o.remove(int(_p[1])); _res.append('null')"),
  ln("  if(_op==='MyHashSet'){_o=new MyHashSet();_res.push('null');}", "  else if(_op==='add'){_o.add(+_p[1]);_res.push('null');}", "  else if(_op==='contains'){_res.push(_o.contains(+_p[1])?'true':'false');}", "  else if(_op==='remove'){_o.remove(+_p[1]);_res.push('null');}"),
  ln('   if(_op=="MyHashSet"){_o=new MyHashSet();_res.push_back("null");}', '   else if(_op=="add"){int _k;_is>>_k;_o->add(_k);_res.push_back("null");}', '   else if(_op=="contains"){int _k;_is>>_k;_res.push_back(_o->contains(_k)?"true":"false");}', '   else if(_op=="remove"){int _k;_is>>_k;_o->remove(_k);_res.push_back("null");}'),
  ln('        if(op.equals("MyHashSet")){o=new MyHashSet();res.add("null");}', '        else if(op.equals("add")){o.add(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("contains")){res.add(o.contains(Integer.parseInt(p[1]))?"true":"false");}', '        else if(op.equals("remove")){o.remove(Integer.parseInt(p[1]));res.add("null");}'));

attach('design-circular-queue', 'MyCircularQueue',
  ln("        if _op=='MyCircularQueue': _o=MyCircularQueue(int(_p[1])); _res.append('null')", "        elif _op=='enQueue': _res.append('true' if _o.enQueue(int(_p[1])) else 'false')", "        elif _op=='deQueue': _res.append('true' if _o.deQueue() else 'false')", "        elif _op=='Front': _res.append(str(_o.Front()))", "        elif _op=='Rear': _res.append(str(_o.Rear()))", "        elif _op=='isEmpty': _res.append('true' if _o.isEmpty() else 'false')", "        elif _op=='isFull': _res.append('true' if _o.isFull() else 'false')"),
  ln("  if(_op==='MyCircularQueue'){_o=new MyCircularQueue(+_p[1]);_res.push('null');}", "  else if(_op==='enQueue'){_res.push(_o.enQueue(+_p[1])?'true':'false');}", "  else if(_op==='deQueue'){_res.push(_o.deQueue()?'true':'false');}", "  else if(_op==='Front'){_res.push(String(_o.Front()));}", "  else if(_op==='Rear'){_res.push(String(_o.Rear()));}", "  else if(_op==='isEmpty'){_res.push(_o.isEmpty()?'true':'false');}", "  else if(_op==='isFull'){_res.push(_o.isFull()?'true':'false');}"),
  ln('   if(_op=="MyCircularQueue"){int _k;_is>>_k;_o=new MyCircularQueue(_k);_res.push_back("null");}', '   else if(_op=="enQueue"){int _x;_is>>_x;_res.push_back(_o->enQueue(_x)?"true":"false");}', '   else if(_op=="deQueue"){_res.push_back(_o->deQueue()?"true":"false");}', '   else if(_op=="Front"){_res.push_back(to_string(_o->Front()));}', '   else if(_op=="Rear"){_res.push_back(to_string(_o->Rear()));}', '   else if(_op=="isEmpty"){_res.push_back(_o->isEmpty()?"true":"false");}', '   else if(_op=="isFull"){_res.push_back(_o->isFull()?"true":"false");}'),
  ln('        if(op.equals("MyCircularQueue")){o=new MyCircularQueue(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("enQueue")){res.add(o.enQueue(Integer.parseInt(p[1]))?"true":"false");}', '        else if(op.equals("deQueue")){res.add(o.deQueue()?"true":"false");}', '        else if(op.equals("Front")){res.add(String.valueOf(o.Front()));}', '        else if(op.equals("Rear")){res.add(String.valueOf(o.Rear()));}', '        else if(op.equals("isEmpty")){res.add(o.isEmpty()?"true":"false");}', '        else if(op.equals("isFull")){res.add(o.isFull()?"true":"false");}'));

attach('design-circular-deque', 'MyCircularDeque',
  ln("        if _op=='MyCircularDeque': _o=MyCircularDeque(int(_p[1])); _res.append('null')", "        elif _op=='insertFront': _res.append('true' if _o.insertFront(int(_p[1])) else 'false')", "        elif _op=='insertLast': _res.append('true' if _o.insertLast(int(_p[1])) else 'false')", "        elif _op=='deleteFront': _res.append('true' if _o.deleteFront() else 'false')", "        elif _op=='deleteLast': _res.append('true' if _o.deleteLast() else 'false')", "        elif _op=='getFront': _res.append(str(_o.getFront()))", "        elif _op=='getRear': _res.append(str(_o.getRear()))", "        elif _op=='isEmpty': _res.append('true' if _o.isEmpty() else 'false')", "        elif _op=='isFull': _res.append('true' if _o.isFull() else 'false')"),
  ln("  if(_op==='MyCircularDeque'){_o=new MyCircularDeque(+_p[1]);_res.push('null');}", "  else if(_op==='insertFront'){_res.push(_o.insertFront(+_p[1])?'true':'false');}", "  else if(_op==='insertLast'){_res.push(_o.insertLast(+_p[1])?'true':'false');}", "  else if(_op==='deleteFront'){_res.push(_o.deleteFront()?'true':'false');}", "  else if(_op==='deleteLast'){_res.push(_o.deleteLast()?'true':'false');}", "  else if(_op==='getFront'){_res.push(String(_o.getFront()));}", "  else if(_op==='getRear'){_res.push(String(_o.getRear()));}", "  else if(_op==='isEmpty'){_res.push(_o.isEmpty()?'true':'false');}", "  else if(_op==='isFull'){_res.push(_o.isFull()?'true':'false');}"),
  ln('   if(_op=="MyCircularDeque"){int _k;_is>>_k;_o=new MyCircularDeque(_k);_res.push_back("null");}', '   else if(_op=="insertFront"){int _x;_is>>_x;_res.push_back(_o->insertFront(_x)?"true":"false");}', '   else if(_op=="insertLast"){int _x;_is>>_x;_res.push_back(_o->insertLast(_x)?"true":"false");}', '   else if(_op=="deleteFront"){_res.push_back(_o->deleteFront()?"true":"false");}', '   else if(_op=="deleteLast"){_res.push_back(_o->deleteLast()?"true":"false");}', '   else if(_op=="getFront"){_res.push_back(to_string(_o->getFront()));}', '   else if(_op=="getRear"){_res.push_back(to_string(_o->getRear()));}', '   else if(_op=="isEmpty"){_res.push_back(_o->isEmpty()?"true":"false");}', '   else if(_op=="isFull"){_res.push_back(_o->isFull()?"true":"false");}'),
  ln('        if(op.equals("MyCircularDeque")){o=new MyCircularDeque(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("insertFront")){res.add(o.insertFront(Integer.parseInt(p[1]))?"true":"false");}', '        else if(op.equals("insertLast")){res.add(o.insertLast(Integer.parseInt(p[1]))?"true":"false");}', '        else if(op.equals("deleteFront")){res.add(o.deleteFront()?"true":"false");}', '        else if(op.equals("deleteLast")){res.add(o.deleteLast()?"true":"false");}', '        else if(op.equals("getFront")){res.add(String.valueOf(o.getFront()));}', '        else if(op.equals("getRear")){res.add(String.valueOf(o.getRear()));}', '        else if(op.equals("isEmpty")){res.add(o.isEmpty()?"true":"false");}', '        else if(op.equals("isFull")){res.add(o.isFull()?"true":"false");}'));

attach('kth-largest-element-in-a-stream', 'KthLargest',
  ln("        if _op=='KthLargest': _o=KthLargest(int(_p[1]), list(map(int,_p[2:]))); _res.append('null')", "        elif _op=='add': _res.append(str(_o.add(int(_p[1]))))"),
  ln("  if(_op==='KthLargest'){_o=new KthLargest(+_p[1], _p.slice(2).map(Number));_res.push('null');}", "  else if(_op==='add'){_res.push(String(_o.add(+_p[1])));}"),
  ln('   if(_op=="KthLargest"){int _k;_is>>_k;vector<int> _v;int _x;while(_is>>_x)_v.push_back(_x);_o=new KthLargest(_k,_v);_res.push_back("null");}', '   else if(_op=="add"){int _x;_is>>_x;_res.push_back(to_string(_o->add(_x)));}'),
  ln('        if(op.equals("KthLargest")){int _k=Integer.parseInt(p[1]);int[] _nums=new int[p.length-2];for(int _z=2;_z<p.length;_z++)_nums[_z-2]=Integer.parseInt(p[_z]);o=new KthLargest(_k,_nums);res.add("null");}', '        else if(op.equals("add")){res.add(String.valueOf(o.add(Integer.parseInt(p[1]))));}'));

attach('design-parking-system', 'ParkingSystem',
  ln("        if _op=='ParkingSystem': _o=ParkingSystem(int(_p[1]),int(_p[2]),int(_p[3])); _res.append('null')", "        elif _op=='addCar': _res.append('true' if _o.addCar(int(_p[1])) else 'false')"),
  ln("  if(_op==='ParkingSystem'){_o=new ParkingSystem(+_p[1],+_p[2],+_p[3]);_res.push('null');}", "  else if(_op==='addCar'){_res.push(_o.addCar(+_p[1])?'true':'false');}"),
  ln('   if(_op=="ParkingSystem"){int _b,_m,_s;_is>>_b>>_m>>_s;_o=new ParkingSystem(_b,_m,_s);_res.push_back("null");}', '   else if(_op=="addCar"){int _t;_is>>_t;_res.push_back(_o->addCar(_t)?"true":"false");}'),
  ln('        if(op.equals("ParkingSystem")){o=new ParkingSystem(Integer.parseInt(p[1]),Integer.parseInt(p[2]),Integer.parseInt(p[3]));res.add("null");}', '        else if(op.equals("addCar")){res.add(o.addCar(Integer.parseInt(p[1]))?"true":"false");}'));

attach('design-browser-history', 'BrowserHistory',
  ln("        if _op=='BrowserHistory': _o=BrowserHistory(_p[1]); _res.append('null')", "        elif _op=='visit': _o.visit(_p[1]); _res.append('null')", "        elif _op=='back': _res.append(_o.back(int(_p[1])))", "        elif _op=='forward': _res.append(_o.forward(int(_p[1])))"),
  ln("  if(_op==='BrowserHistory'){_o=new BrowserHistory(_p[1]);_res.push('null');}", "  else if(_op==='visit'){_o.visit(_p[1]);_res.push('null');}", "  else if(_op==='back'){_res.push(_o.back(+_p[1]));}", "  else if(_op==='forward'){_res.push(_o.forward(+_p[1]));}"),
  ln('   if(_op=="BrowserHistory"){string _h;_is>>_h;_o=new BrowserHistory(_h);_res.push_back("null");}', '   else if(_op=="visit"){string _u;_is>>_u;_o->visit(_u);_res.push_back("null");}', '   else if(_op=="back"){int _s;_is>>_s;_res.push_back(_o->back(_s));}', '   else if(_op=="forward"){int _s;_is>>_s;_res.push_back(_o->forward(_s));}'),
  ln('        if(op.equals("BrowserHistory")){o=new BrowserHistory(p[1]);res.add("null");}', '        else if(op.equals("visit")){o.visit(p[1]);res.add("null");}', '        else if(op.equals("back")){res.add(o.back(Integer.parseInt(p[1])));}', '        else if(op.equals("forward")){res.add(o.forward(Integer.parseInt(p[1])));}'));

attach('number-of-recent-calls', 'RecentCounter',
  ln("        if _op=='RecentCounter': _o=RecentCounter(); _res.append('null')", "        elif _op=='ping': _res.append(str(_o.ping(int(_p[1]))))"),
  ln("  if(_op==='RecentCounter'){_o=new RecentCounter();_res.push('null');}", "  else if(_op==='ping'){_res.push(String(_o.ping(+_p[1])));}"),
  ln('   if(_op=="RecentCounter"){_o=new RecentCounter();_res.push_back("null");}', '   else if(_op=="ping"){int _t;_is>>_t;_res.push_back(to_string(_o->ping(_t)));}'),
  ln('        if(op.equals("RecentCounter")){o=new RecentCounter();res.add("null");}', '        else if(op.equals("ping")){res.add(String.valueOf(o.ping(Integer.parseInt(p[1]))));}'));

attach('design-a-stack-with-increment-operation', 'CustomStack',
  ln("        if _op=='CustomStack': _o=CustomStack(int(_p[1])); _res.append('null')", "        elif _op=='push': _o.push(int(_p[1])); _res.append('null')", "        elif _op=='pop': _res.append(str(_o.pop()))", "        elif _op=='increment': _o.increment(int(_p[1]),int(_p[2])); _res.append('null')"),
  ln("  if(_op==='CustomStack'){_o=new CustomStack(+_p[1]);_res.push('null');}", "  else if(_op==='push'){_o.push(+_p[1]);_res.push('null');}", "  else if(_op==='pop'){_res.push(String(_o.pop()));}", "  else if(_op==='increment'){_o.increment(+_p[1],+_p[2]);_res.push('null');}"),
  ln('   if(_op=="CustomStack"){int _ms;_is>>_ms;_o=new CustomStack(_ms);_res.push_back("null");}', '   else if(_op=="push"){int _x;_is>>_x;_o->push(_x);_res.push_back("null");}', '   else if(_op=="pop"){_res.push_back(to_string(_o->pop()));}', '   else if(_op=="increment"){int _k,_v;_is>>_k>>_v;_o->increment(_k,_v);_res.push_back("null");}'),
  ln('        if(op.equals("CustomStack")){o=new CustomStack(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("push")){o.push(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("pop")){res.add(String.valueOf(o.pop()));}', '        else if(op.equals("increment")){o.increment(Integer.parseInt(p[1]),Integer.parseInt(p[2]));res.add("null");}'));

attach('range-sum-query-immutable', 'NumArray',
  ln("        if _op=='NumArray': _o=NumArray(list(map(int,_p[1:]))); _res.append('null')", "        elif _op=='sumRange': _res.append(str(_o.sumRange(int(_p[1]),int(_p[2]))))"),
  ln("  if(_op==='NumArray'){_o=new NumArray(_p.slice(1).map(Number));_res.push('null');}", "  else if(_op==='sumRange'){_res.push(String(_o.sumRange(+_p[1],+_p[2])));}"),
  ln('   if(_op=="NumArray"){vector<int> _v;int _x;while(_is>>_x)_v.push_back(_x);_o=new NumArray(_v);_res.push_back("null");}', '   else if(_op=="sumRange"){int _l,_r;_is>>_l>>_r;_res.push_back(to_string(_o->sumRange(_l,_r)));}'),
  ln('        if(op.equals("NumArray")){int[] _nums=new int[p.length-1];for(int _z=1;_z<p.length;_z++)_nums[_z-1]=Integer.parseInt(p[_z]);o=new NumArray(_nums);res.add("null");}', '        else if(op.equals("sumRange")){res.add(String.valueOf(o.sumRange(Integer.parseInt(p[1]),Integer.parseInt(p[2]))));}'));

attach('logger-rate-limiter', 'Logger',
  ln("        if _op=='Logger': _o=Logger(); _res.append('null')", "        elif _op=='shouldPrintMessage': _res.append('true' if _o.shouldPrintMessage(int(_p[1]),_p[2]) else 'false')"),
  ln("  if(_op==='Logger'){_o=new Logger();_res.push('null');}", "  else if(_op==='shouldPrintMessage'){_res.push(_o.shouldPrintMessage(+_p[1],_p[2])?'true':'false');}"),
  ln('   if(_op=="Logger"){_o=new Logger();_res.push_back("null");}', '   else if(_op=="shouldPrintMessage"){int _t;string _m;_is>>_t>>_m;_res.push_back(_o->shouldPrintMessage(_t,_m)?"true":"false");}'),
  ln('        if(op.equals("Logger")){o=new Logger();res.add("null");}', '        else if(op.equals("shouldPrintMessage")){res.add(o.shouldPrintMessage(Integer.parseInt(p[1]),p[2])?"true":"false");}'));

attach('design-hit-counter', 'HitCounter',
  ln("        if _op=='HitCounter': _o=HitCounter(); _res.append('null')", "        elif _op=='hit': _o.hit(int(_p[1])); _res.append('null')", "        elif _op=='getHits': _res.append(str(_o.getHits(int(_p[1]))))"),
  ln("  if(_op==='HitCounter'){_o=new HitCounter();_res.push('null');}", "  else if(_op==='hit'){_o.hit(+_p[1]);_res.push('null');}", "  else if(_op==='getHits'){_res.push(String(_o.getHits(+_p[1])));}"),
  ln('   if(_op=="HitCounter"){_o=new HitCounter();_res.push_back("null");}', '   else if(_op=="hit"){int _t;_is>>_t;_o->hit(_t);_res.push_back("null");}', '   else if(_op=="getHits"){int _t;_is>>_t;_res.push_back(to_string(_o->getHits(_t)));}'),
  ln('        if(op.equals("HitCounter")){o=new HitCounter();res.add("null");}', '        else if(op.equals("hit")){o.hit(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("getHits")){res.add(String.valueOf(o.getHits(Integer.parseInt(p[1]))));}'));

attach('max-stack', 'MaxStack',
  ln("        if _op=='MaxStack': _o=MaxStack(); _res.append('null')", "        elif _op=='push': _o.push(int(_p[1])); _res.append('null')", "        elif _op=='top': _res.append(str(_o.top()))", "        elif _op=='pop': _res.append(str(_o.pop()))", "        elif _op=='peekMax': _res.append(str(_o.peekMax()))", "        elif _op=='popMax': _res.append(str(_o.popMax()))"),
  ln("  if(_op==='MaxStack'){_o=new MaxStack();_res.push('null');}", "  else if(_op==='push'){_o.push(+_p[1]);_res.push('null');}", "  else if(_op==='top'){_res.push(String(_o.top()));}", "  else if(_op==='pop'){_res.push(String(_o.pop()));}", "  else if(_op==='peekMax'){_res.push(String(_o.peekMax()));}", "  else if(_op==='popMax'){_res.push(String(_o.popMax()));}"),
  ln('   if(_op=="MaxStack"){_o=new MaxStack();_res.push_back("null");}', '   else if(_op=="push"){int _x;_is>>_x;_o->push(_x);_res.push_back("null");}', '   else if(_op=="top"){_res.push_back(to_string(_o->top()));}', '   else if(_op=="pop"){_res.push_back(to_string(_o->pop()));}', '   else if(_op=="peekMax"){_res.push_back(to_string(_o->peekMax()));}', '   else if(_op=="popMax"){_res.push_back(to_string(_o->popMax()));}'),
  ln('        if(op.equals("MaxStack")){o=new MaxStack();res.add("null");}', '        else if(op.equals("push")){o.push(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("top")){res.add(String.valueOf(o.top()));}', '        else if(op.equals("pop")){res.add(String.valueOf(o.pop()));}', '        else if(op.equals("peekMax")){res.add(String.valueOf(o.peekMax()));}', '        else if(op.equals("popMax")){res.add(String.valueOf(o.popMax()));}'));

attach('find-median-from-data-stream', 'MedianFinder',
  ln("        if _op=='MedianFinder': _o=MedianFinder(); _res.append('null')", "        elif _op=='addNum': _o.addNum(int(_p[1])); _res.append('null')", "        elif _op=='findMedian': _res.append('%.1f' % _o.findMedian())"),
  ln("  if(_op==='MedianFinder'){_o=new MedianFinder();_res.push('null');}", "  else if(_op==='addNum'){_o.addNum(+_p[1]);_res.push('null');}", "  else if(_op==='findMedian'){_res.push(_o.findMedian().toFixed(1));}"),
  ln('   if(_op=="MedianFinder"){_o=new MedianFinder();_res.push_back("null");}', '   else if(_op=="addNum"){int _x;_is>>_x;_o->addNum(_x);_res.push_back("null");}', '   else if(_op=="findMedian"){char _b[32];snprintf(_b,sizeof(_b),"%.1f",_o->findMedian());_res.push_back(string(_b));}'),
  ln('        if(op.equals("MedianFinder")){o=new MedianFinder();res.add("null");}', '        else if(op.equals("addNum")){o.addNum(Integer.parseInt(p[1]));res.add("null");}', '        else if(op.equals("findMedian")){res.add(String.format(java.util.Locale.US,"%.1f",o.findMedian()));}'));

module.exports = { MORE22 };
