// Batch J: car fleet, merge triplets, network delay time.
const { T, randInt, randArr } = require('./gen.js');

function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function ED(o) {
  var h = '';
  if (o.intuition) h += '<h3>Intuition</h3>' + (Array.isArray(o.intuition) ? o.intuition.map(function (p) { return '<p>' + p + '</p>'; }).join('') : '<p>' + o.intuition + '</p>');
  if (o.approach) h += '<h3>Approach</h3><ol>' + o.approach.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ol>';
  if (o.code) h += '<h3>Solution</h3><pre><code>' + esc(o.code) + '</code></pre>';
  h += '<h3>Complexity</h3><ul><li><b>Time — ' + o.time + ':</b> ' + o.timeWhy + '</li><li><b>Space — ' + o.space + ':</b> ' + o.spaceWhy + '</li></ul>';
  if (o.pitfalls) h += '<h3>Common Pitfalls</h3><ul>' + o.pitfalls.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ul>';
  return h;
}

const MORE14 = [];

// ---- Car Fleet (INT_ARR_ARR_INT) ----
MORE14.push({ slug: 'car-fleet', title: 'Car Fleet', difficulty: 'medium', topics: ['Array', 'Stack', 'Sorting', 'Monotonic Stack'], type: 'INT_ARR_ARR_INT', langsrc: T.INT_ARR_ARR_INT('carFleet'),
  desc: '<p>Cars head to a destination at <code>target</code>. Car <code>i</code> starts at <code>position[i]</code> with constant <code>speed[i]</code>; a faster car catches up to a slower one ahead and then travels as a fleet at the slower speed. Return the number of car fleets that arrive.</p>',
  examples: [{ in: 'target = 12, position = [10,8,0,5,3], speed = [2,4,1,1,3]', out: '3' }, { in: 'target = 10, position = [3], speed = [3]', out: '1' }],
  constraints: ['0 &lt;= n &lt;= 10^5', '0 &lt; target &lt;= 10^6', 'All positions are unique.'],
  editorial: ED({ intuition: 'Process cars from the one closest to the target backwards. Compute each car\u2019s arrival time if unobstructed. A car that would arrive no later than the fleet ahead merges into it; otherwise it forms a new fleet.', approach: ['Sort cars by position descending.', 'For each car compute time = (target - position) / speed.', 'If its time is strictly greater than the current fleet\u2019s lead time, it is a new fleet (update the lead time); otherwise it joins the fleet ahead.'], code: 'def carFleet(self, target, position, speed):\n    cars = sorted(zip(position, speed), reverse=True)\n    fleets = 0\n    lead = -1.0\n    for p, s in cars:\n        t = (target - p) / s\n        if t > lead:\n            fleets += 1\n            lead = t\n    return fleets', time: 'O(n log n)', timeWhy: 'sorting by position dominates.', space: 'O(n)', spaceWhy: 'the sorted list.', pitfalls: ['A car catching up merges — only a strictly larger arrival time starts a new fleet.'] }),
  gen: function () { var o = [[12, [10, 8, 0, 5, 3], [2, 4, 1, 1, 3]], [10, [3], [3]], [100, [], []]]; for (var k = 0; k < 38; k++) { var target = randInt(10, 30), n = randInt(0, 6), used = {}, pos = [], sp = []; while (pos.length < n) { var p = randInt(0, target - 1); if (!used[p]) { used[p] = 1; pos.push(p); sp.push(randInt(1, 5)); } } o.push([target, pos, sp]); } return o; },
  ref: function (a) { var target = a[0], pos = a[1], sp = a[2]; var idx = pos.map(function (_, i) { return i; }).sort(function (x, y) { return pos[y] - pos[x]; }); var fleets = 0, lead = -1; for (var i = 0; i < idx.length; i++) { var t = (target - pos[idx[i]]) / sp[idx[i]]; if (t > lead) { fleets++; lead = t; } } return fleets; } });

// ---- Merge Triplets to Form Target Triplet (GRID_TRIP_BOOL) ----
MORE14.push({ slug: 'merge-triplets-to-form-target-triplet', title: 'Merge Triplets to Form Target Triplet', difficulty: 'medium', topics: ['Array', 'Greedy'], type: 'GRID_TRIP_BOOL', langsrc: T.GRID_TRIP_BOOL('mergeTriplets'),
  desc: '<p>You are given <code>triplets</code> and a <code>target</code> triplet. A merge replaces the running triplet with the element-wise maximum of it and a chosen triplet. Return <code>true</code> if some sequence of merges can produce exactly <code>target</code>.</p>',
  examples: [{ in: 'triplets = [[2,5,3],[1,8,4],[1,7,5]], target = [2,7,5]', out: 'true' }, { in: 'triplets = [[3,4,5],[4,5,6]], target = [3,2,5]', out: 'false' }],
  constraints: ['1 &lt;= triplets.length &lt;= 10^5', 'triplets[i].length == target.length == 3'],
  editorial: ED({ intuition: 'A triplet is only usable if none of its coordinates exceeds the target (otherwise a merge would overshoot). Among usable triplets, you just need each target coordinate to be hit exactly by at least one of them.', approach: ['Ignore any triplet with a coordinate greater than the corresponding target value.', 'For each usable triplet, mark which coordinates equal the target.', 'Return true iff all three coordinates get marked.'], code: 'def mergeTriplets(self, triplets, target):\n    good = set()\n    for t in triplets:\n        if t[0] <= target[0] and t[1] <= target[1] and t[2] <= target[2]:\n            for i in range(3):\n                if t[i] == target[i]:\n                    good.add(i)\n    return len(good) == 3', time: 'O(n)', timeWhy: 'a single pass over triplets.', space: 'O(1)', spaceWhy: 'a tiny set of at most 3 indices.', pitfalls: ['Only triplets that never exceed the target in any coordinate are safe to merge.'] }),
  gen: function () { var o = [[[[2, 5, 3], [1, 8, 4], [1, 7, 5]], [2, 7, 5]], [[[3, 4, 5], [4, 5, 6]], [3, 2, 5]]]; for (var k = 0; k < 38; k++) { var n = randInt(1, 6), trip = []; for (var i = 0; i < n; i++) trip.push([randInt(1, 5), randInt(1, 5), randInt(1, 5)]); o.push([trip, [randInt(1, 5), randInt(1, 5), randInt(1, 5)]]); } return o; },
  ref: function (a) { var triplets = a[0], target = a[1], good = {}; for (var i = 0; i < triplets.length; i++) { var t = triplets[i]; if (t[0] <= target[0] && t[1] <= target[1] && t[2] <= target[2]) for (var j = 0; j < 3; j++) if (t[j] === target[j]) good[j] = 1; } return good[0] && good[1] && good[2] ? true : false; } });

// ---- Network Delay Time (GRID_INT_INT_INT) ----
MORE14.push({ slug: 'network-delay-time', title: 'Network Delay Time', difficulty: 'medium', topics: ['Graph', 'Dijkstra', 'Heap', 'Shortest Path'], type: 'GRID_INT_INT_INT', langsrc: T.GRID_INT_INT_INT('networkDelayTime'),
  desc: '<p>You are given directed weighted edges <code>times</code> where <code>times[i] = [u, v, w]</code>, <code>n</code> nodes labeled 1..n, and a source <code>k</code>. Return the time for all nodes to receive a signal from <code>k</code>, or <code>-1</code> if some node is unreachable.</p>',
  examples: [{ in: 'times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2', out: '2' }, { in: 'times = [[1,2,1]], n = 2, k = 2', out: '-1' }],
  constraints: ['1 &lt;= n &lt;= 100', '1 &lt;= times.length &lt;= 6000', 'The graph is directed with positive weights.'],
  editorial: ED({ intuition: 'The signal reaches every node along the shortest weighted path from the source. The answer is the largest of those shortest distances (or -1 if any node is unreachable) — exactly what Dijkstra computes.', approach: ['Build an adjacency list and run Dijkstra from k with a min-heap keyed by distance.', 'Relax edges, recording the shortest distance to each node.', 'If any node stays at infinity, return -1; otherwise return the maximum distance.'], code: 'import heapq\n\ndef networkDelayTime(self, times, n, k):\n    adj = {i: [] for i in range(1, n+1)}\n    for u, v, w in times:\n        adj[u].append((v, w))\n    dist = {}\n    heap = [(0, k)]\n    while heap:\n        d, u = heapq.heappop(heap)\n        if u in dist:\n            continue\n        dist[u] = d\n        for v, w in adj[u]:\n            if v not in dist:\n                heapq.heappush(heap, (d + w, v))\n    if len(dist) < n:\n        return -1\n    return max(dist.values())', time: 'O(E log V)', timeWhy: 'each edge triggers a heap push.', space: 'O(V + E)', spaceWhy: 'adjacency list and heap.' }),
  gen: function () { var o = [[[[2, 1, 1], [2, 3, 1], [3, 4, 1]], 4, 2], [[[1, 2, 1]], 2, 2], [[[1, 2, 1], [2, 3, 2], [1, 3, 4]], 3, 1]]; for (var k = 0; k < 36; k++) { var n = randInt(1, 6), m = randInt(0, n + 2), times = []; for (var i = 0; i < m; i++) { var u = randInt(1, n), v = randInt(1, n); if (u !== v) times.push([u, v, randInt(1, 5)]); } o.push([times, n, randInt(1, n)]); } return o; },
  ref: function (a) { var times = a[0], n = a[1], k = a[2], adj = {}; for (var i = 1; i <= n; i++) adj[i] = []; times.forEach(function (e) { adj[e[0]].push([e[1], e[2]]); }); var dist = {}, heap = [[0, k]]; while (heap.length) { heap.sort(function (x, y) { return x[0] - y[0]; }); var top = heap.shift(), d = top[0], u = top[1]; if (dist[u] !== undefined) continue; dist[u] = d; adj[u].forEach(function (e) { if (dist[e[0]] === undefined) heap.push([d + e[1], e[0]]); }); } var cnt = 0, mx = 0; for (i = 1; i <= n; i++) { if (dist[i] === undefined) return -1; cnt++; mx = Math.max(mx, dist[i]); } return mx; } });

module.exports = { MORE14 };
