// Batch H: graph problems (adjacency / edges / grid).
const { T, randInt } = require('./gen.js');

function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function ED(o) {
  var h = '';
  if (o.intuition) h += '<h3>Intuition</h3>' + (Array.isArray(o.intuition) ? o.intuition.map(function (p) { return '<p>' + p + '</p>'; }).join('') : '<p>' + o.intuition + '</p>');
  if (o.approach) h += '<h3>Approach</h3><ol>' + o.approach.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ol>';
  if (o.code) h += '<h3>Solution</h3><pre><code>' + esc(o.code) + '</code></pre>';
  h += '<h3>Complexity</h3><ul><li><b>Time — ' + o.time + ':</b> ' + o.timeWhy + '</li><li><b>Space — ' + o.space + ':</b> ' + o.spaceWhy + '</li></ul>';
  if (o.pitfalls) h += '<h3>Common Pitfalls</h3><ul>' + o.pitfalls.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ul>';
  return h;
}
function shuffle(a) { for (var i = a.length - 1; i > 0; i--) { var j = randInt(0, i); var t = a[i]; a[i] = a[j]; a[j] = t; } return a; }
function rw(minL, maxL, al) { var L = randInt(minL, maxL), s = ''; for (var i = 0; i < L; i++) s += al[randInt(0, al.length - 1)]; return s; }
function dsuCount(n, edges) { var par = []; for (var i = 0; i < n; i++) par[i] = i; function find(x) { while (par[x] !== x) { par[x] = par[par[x]]; x = par[x]; } return x; } var comp = n; edges.forEach(function (e) { var ra = find(e[0]), rb = find(e[1]); if (ra !== rb) { par[ra] = rb; comp--; } }); return comp; }
var INF = 2147483647;

const MORE12 = [];

// ---- Course Schedule (INT_EDGES_BOOL) ----
MORE12.push({ slug: 'course-schedule', title: 'Course Schedule', difficulty: 'medium', topics: ['Graph', 'Topological Sort', 'DFS', 'BFS'], type: 'INT_EDGES_BOOL', langsrc: T.INT_EDGES_BOOL('canFinish'),
  desc: '<p>There are <code>n</code> courses labeled 0..n-1. <code>edges[i] = [a, b]</code> means you must take course <code>b</code> before course <code>a</code>. Return <code>true</code> if you can finish all courses.</p>',
  examples: [{ in: 'n = 2, edges = [[1,0]]', out: 'true' }, { in: 'n = 2, edges = [[1,0],[0,1]]', out: 'false' }],
  constraints: ['1 &lt;= n &lt;= 2000', '0 &lt;= edges.length &lt;= 5000'],
  editorial: ED({ intuition: 'You can finish all courses exactly when the prerequisite graph has no cycle. Topological sort (Kahn\u2019s algorithm) succeeds iff every node can be ordered, i.e. no cycle.', approach: ['Build an adjacency list and in-degree count (edge b -&gt; a).', 'Queue all zero in-degree courses; repeatedly remove one and decrement its neighbours.', 'If the number removed equals n, there is no cycle.'], code: 'from collections import deque\n\ndef canFinish(self, n, edges):\n    adj = [[] for _ in range(n)]\n    indeg = [0]*n\n    for a, b in edges:\n        adj[b].append(a); indeg[a] += 1\n    q = deque(i for i in range(n) if indeg[i] == 0)\n    seen = 0\n    while q:\n        u = q.popleft(); seen += 1\n        for v in adj[u]:\n            indeg[v] -= 1\n            if indeg[v] == 0: q.append(v)\n    return seen == n', time: 'O(V+E)', timeWhy: 'each node and edge processed once.', space: 'O(V+E)', spaceWhy: 'adjacency list and queue.' }),
  gen: function () { var o = [[2, [[1, 0]]], [2, [[1, 0], [0, 1]]], [1, []]]; for (var k = 0; k < 34; k++) { var n = randInt(1, 6), m = randInt(0, n + 2), edges = []; for (var i = 0; i < m; i++) { var a = randInt(0, n - 1), b = randInt(0, n - 1); edges.push([a, b]); } o.push([n, edges]); } return o; },
  ref: function (a) { var n = a[0], edges = a[1], adj = [], indeg = new Array(n).fill(0); for (var i = 0; i < n; i++) adj.push([]); edges.forEach(function (e) { adj[e[1]].push(e[0]); indeg[e[0]]++; }); var q = []; for (i = 0; i < n; i++) if (indeg[i] === 0) q.push(i); var seen = 0; while (q.length) { var u = q.shift(); seen++; adj[u].forEach(function (v) { if (--indeg[v] === 0) q.push(v); }); } return seen === n; } });

// ---- Number of Connected Components (INT_EDGES_INT) ----
MORE12.push({ slug: 'number-of-connected-components-in-an-undirected-graph', title: 'Number of Connected Components in an Undirected Graph', difficulty: 'medium', topics: ['Graph', 'Union Find', 'DFS', 'BFS'], type: 'INT_EDGES_INT', langsrc: T.INT_EDGES_INT('countComponents'),
  desc: '<p>Given <code>n</code> nodes labeled 0..n-1 and a list of undirected <code>edges</code>, return the number of connected components.</p>',
  examples: [{ in: 'n = 5, edges = [[0,1],[1,2],[3,4]]', out: '2' }, { in: 'n = 5, edges = [[0,1],[1,2],[2,3],[3,4]]', out: '1' }],
  constraints: ['1 &lt;= n &lt;= 2000', '0 &lt;= edges.length &lt;= 5000'],
  editorial: ED({ intuition: 'Start with n isolated components. Each edge that joins two different components reduces the count by one — that is exactly what union-find tracks.', approach: ['Initialize a DSU with each node its own parent and a component count of n.', 'For each edge, union the endpoints; if they were in different sets, decrement the count.', 'Return the final count.'], code: 'def countComponents(self, n, edges):\n    par = list(range(n))\n    def find(x):\n        while par[x] != x:\n            par[x] = par[par[x]]; x = par[x]\n        return x\n    comp = n\n    for a, b in edges:\n        ra, rb = find(a), find(b)\n        if ra != rb:\n            par[ra] = rb; comp -= 1\n    return comp', time: 'O((V+E) alpha)', timeWhy: 'near-constant union-find operations.', space: 'O(V)', spaceWhy: 'the parent array.' }),
  gen: function () { var o = [[5, [[0, 1], [1, 2], [3, 4]]], [5, [[0, 1], [1, 2], [2, 3], [3, 4]]], [1, []]]; for (var k = 0; k < 34; k++) { var n = randInt(1, 7), m = randInt(0, n), edges = []; for (var i = 0; i < m; i++) edges.push([randInt(0, n - 1), randInt(0, n - 1)]); o.push([n, edges]); } return o; },
  ref: function (a) { return dsuCount(a[0], a[1]); } });

// ---- Graph Valid Tree (INT_EDGES_BOOL) ----
MORE12.push({ slug: 'graph-valid-tree', title: 'Graph Valid Tree', difficulty: 'medium', topics: ['Graph', 'Union Find', 'DFS', 'BFS'], type: 'INT_EDGES_BOOL', langsrc: T.INT_EDGES_BOOL('validTree'),
  desc: '<p>Given <code>n</code> nodes labeled 0..n-1 and a list of undirected <code>edges</code>, return <code>true</code> if the graph is a valid tree (fully connected and acyclic).</p>',
  examples: [{ in: 'n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]', out: 'true' }, { in: 'n = 5, edges = [[0,1],[1,2],[2,3],[1,3],[1,4]]', out: 'false' }],
  constraints: ['1 &lt;= n &lt;= 2000', '0 &lt;= edges.length &lt;= 5000'],
  editorial: ED({ intuition: 'A graph is a tree iff it has exactly <code>n - 1</code> edges AND is connected. Those two conditions together forbid both cycles and disconnection.', approach: ['If the edge count is not n-1, it cannot be a tree.', 'Otherwise count connected components with union-find.', 'It is a valid tree iff there is exactly one component.'], code: 'def validTree(self, n, edges):\n    if len(edges) != n - 1:\n        return False\n    par = list(range(n))\n    def find(x):\n        while par[x] != x:\n            par[x] = par[par[x]]; x = par[x]\n        return x\n    comp = n\n    for a, b in edges:\n        ra, rb = find(a), find(b)\n        if ra == rb:\n            return False\n        par[ra] = rb; comp -= 1\n    return comp == 1', time: 'O((V+E) alpha)', timeWhy: 'union-find over the edges.', space: 'O(V)', spaceWhy: 'parent array.', pitfalls: ['The n-1 edge check alone is not enough — you also need connectivity.'] }),
  gen: function () { var o = [[5, [[0, 1], [0, 2], [0, 3], [1, 4]]], [5, [[0, 1], [1, 2], [2, 3], [1, 3], [1, 4]]], [1, []]]; for (var k = 0; k < 34; k++) { var n = randInt(1, 7); var edges = []; if (Math.random() < 0.5) { for (var i = 1; i < n; i++) edges.push([randInt(0, i - 1), i]); } else { var m = randInt(0, n + 1); for (i = 0; i < m; i++) edges.push([randInt(0, n - 1), randInt(0, n - 1)]); } o.push([n, edges]); } return o; },
  ref: function (a) { var n = a[0], edges = a[1]; if (edges.length !== n - 1) return false; return dsuCount(n, edges) === 1; } });

// ---- Redundant Connection (EDGES_ARR) ----
MORE12.push({ slug: 'redundant-connection', title: 'Redundant Connection', difficulty: 'medium', topics: ['Graph', 'Union Find'], type: 'EDGES_ARR', langsrc: T.EDGES_ARR('findRedundantConnection'),
  desc: '<p>A tree on nodes 1..n had one extra edge added, creating exactly one cycle. Given the <code>edges</code> in input order, return the edge that can be removed so the result is a tree. If several qualify, return the one that appears last in the input.</p>',
  examples: [{ in: 'edges = [[1,2],[1,3],[2,3]]', out: '[2,3]' }, { in: 'edges = [[1,2],[2,3],[3,4],[1,4],[1,5]]', out: '[1,4]' }],
  constraints: ['3 &lt;= n &lt;= 1000', 'The graph is a tree plus exactly one extra edge.'],
  editorial: ED({ intuition: 'Process edges in order with union-find. The first edge whose two endpoints are already connected is the one closing the cycle — and because there is exactly one extra edge, that is the answer.', approach: ['Initialize DSU over the nodes.', 'For each edge, if find(a) == find(b) the edge is redundant — return it.', 'Otherwise union them.'], code: 'def findRedundantConnection(self, edges):\n    par = list(range(len(edges) + 1))\n    def find(x):\n        while par[x] != x:\n            par[x] = par[par[x]]; x = par[x]\n        return x\n    for a, b in edges:\n        ra, rb = find(a), find(b)\n        if ra == rb:\n            return [a, b]\n        par[ra] = rb\n    return []', time: 'O(n alpha)', timeWhy: 'one near-constant union-find op per edge.', space: 'O(n)', spaceWhy: 'the parent array.' }),
  gen: function () { var o = [[[[1, 2], [1, 3], [2, 3]]], [[[1, 2], [2, 3], [3, 4], [1, 4], [1, 5]]]]; for (var k = 0; k < 38; k++) { var n = randInt(3, 7), edges = [], eset = {}; for (var i = 2; i <= n; i++) { var p = randInt(1, i - 1); edges.push([p, i]); eset[p + ',' + i] = 1; eset[i + ',' + p] = 1; } var tries = 0, ex = null; while (tries < 60) { var x = randInt(1, n), y = randInt(1, n); if (x !== y && !eset[x + ',' + y]) { ex = [x, y]; break; } tries++; } if (!ex) ex = [1, 2]; edges.push(ex); shuffle(edges); o.push([edges]); } return o; },
  ref: function (a) { var edges = a[0], maxN = 0; edges.forEach(function (e) { maxN = Math.max(maxN, e[0], e[1]); }); var par = []; for (var i = 0; i <= maxN; i++) par[i] = i; function find(x) { while (par[x] !== x) { par[x] = par[par[x]]; x = par[x]; } return x; } for (i = 0; i < edges.length; i++) { var ra = find(edges[i][0]), rb = find(edges[i][1]); if (ra === rb) return [edges[i][0], edges[i][1]]; par[ra] = rb; } return []; } });

// ---- Min Cost to Connect All Points (GRID_INT) ----
MORE12.push({ slug: 'min-cost-to-connect-all-points', title: 'Min Cost to Connect All Points', difficulty: 'medium', topics: ['Graph', 'Minimum Spanning Tree', 'Heap'], type: 'GRID_INT', langsrc: T.GRID_INT('minCostConnectPoints'),
  desc: '<p>You are given <code>points</code> where <code>points[i] = [x, y]</code>. The cost to connect two points is their Manhattan distance. Return the minimum cost to connect all points so every pair is reachable. (Input rows are the points.)</p>',
  examples: [{ in: 'points = [[0,0],[2,2],[3,10],[5,2],[7,0]]', out: '20' }, { in: 'points = [[3,12],[-2,5],[-4,1]]', out: '18' }],
  constraints: ['1 &lt;= points.length &lt;= 1000', '-10^6 &lt;= xi, yi &lt;= 10^6'],
  editorial: ED({ intuition: 'This is a minimum spanning tree on a complete graph where edge weights are Manhattan distances. Prim\u2019s algorithm grows the tree by repeatedly adding the cheapest edge to a new point.', approach: ['Start from any point; track the min distance from the growing tree to each outside point.', 'Repeatedly pick the closest outside point, add its distance to the total, and mark it in the tree.', 'Update the distances of remaining points against the newly added one.'], code: 'def minCostConnectPoints(self, points):\n    n = len(points)\n    in_mst = [False]*n\n    dist = [float("inf")]*n\n    dist[0] = 0\n    total = 0\n    for _ in range(n):\n        u = -1\n        for i in range(n):\n            if not in_mst[i] and (u == -1 or dist[i] < dist[u]):\n                u = i\n        in_mst[u] = True\n        total += dist[u]\n        for v in range(n):\n            if not in_mst[v]:\n                d = abs(points[u][0]-points[v][0]) + abs(points[u][1]-points[v][1])\n                dist[v] = min(dist[v], d)\n    return total', time: 'O(n^2)', timeWhy: 'dense Prim\u2019s over all point pairs.', space: 'O(n)', spaceWhy: 'the distance and in-tree arrays.' }),
  gen: function () { var o = [[[[0, 0], [2, 2], [3, 10], [5, 2], [7, 0]]], [[[3, 12], [-2, 5], [-4, 1]]], [[[0, 0]]]]; for (var k = 0; k < 34; k++) { var n = randInt(1, 6), pts = []; for (var i = 0; i < n; i++) pts.push([randInt(-10, 10), randInt(-10, 10)]); o.push([pts]); } return o; },
  ref: function (a) { var pts = a[0], n = pts.length; if (n <= 1) return 0; var inMst = new Array(n).fill(false), dist = new Array(n).fill(Infinity); dist[0] = 0; var total = 0; for (var it = 0; it < n; it++) { var u = -1; for (var i = 0; i < n; i++) if (!inMst[i] && (u === -1 || dist[i] < dist[u])) u = i; inMst[u] = true; total += dist[u]; for (var v = 0; v < n; v++) if (!inMst[v]) { var d = Math.abs(pts[u][0] - pts[v][0]) + Math.abs(pts[u][1] - pts[v][1]); if (d < dist[v]) dist[v] = d; } } return total; } });

// ---- Walls and Gates (GRID_GRID) ----
MORE12.push({ slug: 'walls-and-gates', title: 'Walls and Gates', difficulty: 'medium', topics: ['Graph', 'BFS', 'Matrix'], type: 'GRID_GRID', langsrc: T.GRID_GRID('wallsAndGates'),
  desc: '<p>Fill each empty room with the distance to its nearest gate. <code>-1</code> is a wall, <code>0</code> is a gate, and <code>2147483647</code> (INF) is an empty room. If a room cannot reach a gate, leave it as INF. Return the filled grid.</p>',
  examples: [{ in: 'rooms = [[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]]', out: '[[3,-1,0,1],[2,2,1,-1],[1,-1,2,-1],[0,-1,3,4]]' }],
  constraints: ['1 &lt;= m, n &lt;= 250', 'Each cell is -1, 0, or 2147483647.'],
  editorial: ED({ intuition: 'Rather than BFS from each room, do one multi-source BFS starting from all gates at once. The first time BFS reaches a room, that is its shortest distance to any gate.', approach: ['Enqueue every gate (value 0).', 'BFS outward; for each empty neighbour (INF), set its distance to current + 1 and enqueue it.', 'Walls and already-filled rooms are skipped.'], code: 'from collections import deque\n\ndef wallsAndGates(self, rooms):\n    R, C = len(rooms), len(rooms[0])\n    q = deque((r, c) for r in range(R) for c in range(C) if rooms[r][c] == 0)\n    while q:\n        r, c = q.popleft()\n        for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr, nc = r+dr, c+dc\n            if 0 <= nr < R and 0 <= nc < C and rooms[nr][nc] == 2147483647:\n                rooms[nr][nc] = rooms[r][c] + 1\n                q.append((nr, nc))\n    return rooms', time: 'O(m*n)', timeWhy: 'each room enqueued at most once.', space: 'O(m*n)', spaceWhy: 'the BFS queue.', pitfalls: ['Multi-source BFS from all gates avoids the O((mn)^2) cost of BFS-per-room.'] }),
  gen: function () { var o = [[[[INF, -1, 0, INF], [INF, INF, INF, -1], [INF, -1, INF, -1], [0, -1, INF, INF]]]]; for (var k = 0; k < 34; k++) { var R = randInt(1, 4), C = randInt(1, 4), g = []; for (var i = 0; i < R; i++) { var row = []; for (var j = 0; j < C; j++) { var t = Math.random(); row.push(t < 0.2 ? -1 : (t < 0.4 ? 0 : INF)); } g.push(row); } o.push([g]); } return o; },
  ref: function (a) { var g = a[0].map(function (r) { return r.slice(); }); var R = g.length, C = g[0].length, q = []; for (var i = 0; i < R; i++) for (var j = 0; j < C; j++) if (g[i][j] === 0) q.push([i, j]); var dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; while (q.length) { var nq = []; for (var k = 0; k < q.length; k++) { var r = q[k][0], c = q[k][1]; for (var d = 0; d < 4; d++) { var nr = r + dirs[d][0], nc = c + dirs[d][1]; if (nr >= 0 && nr < R && nc >= 0 && nc < C && g[nr][nc] === INF) { g[nr][nc] = g[r][c] + 1; nq.push([nr, nc]); } } } q = nq; } return g.map(function (row) { return row.join(' '); }).join('|'); } });

// ---- Surrounded Regions (CHARGRID_GRID) ----
MORE12.push({ slug: 'surrounded-regions', title: 'Surrounded Regions', difficulty: 'medium', topics: ['Graph', 'DFS', 'BFS', 'Matrix'], type: 'CHARGRID_GRID', langsrc: T.CHARGRID_GRID('solve'),
  desc: "<p>Given an <code>m x n</code> board of <code>'X'</code> and <code>'O'</code>, capture all regions of <code>'O'</code> that are fully surrounded by <code>'X'</code> (flip them to <code>'X'</code>). Any <code>'O'</code> connected to the border is safe. Return the resulting board.</p>",
  examples: [{ in: 'board = ["XXXX","XOOX","XXOX","XOXX"]', out: '["XXXX","XXXX","XXXX","XOXX"]' }],
  constraints: ['1 &lt;= m, n &lt;= 200', "board[i][j] is 'X' or 'O'."],
  editorial: ED({ intuition: 'An \u2018O\u2019 survives only if it can reach the border. So mark every border-connected \u2018O\u2019 as safe first; then every remaining \u2018O\u2019 is surrounded and gets flipped.', approach: ['DFS/BFS from every \u2018O\u2019 on the border, marking reachable \u2018O\u2019s as safe (temporary marker).', 'Scan the board: flip unmarked \u2018O\u2019 to \u2018X\u2019.', 'Restore the safe markers back to \u2018O\u2019.'], code: 'def solve(self, board):\n    if not board: return\n    R, C = len(board), len(board[0])\n    def dfs(r, c):\n        if r < 0 or r >= R or c < 0 or c >= C or board[r][c] != "O":\n            return\n        board[r][c] = "#"\n        dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\n    for r in range(R):\n        dfs(r, 0); dfs(r, C-1)\n    for c in range(C):\n        dfs(0, c); dfs(R-1, c)\n    for r in range(R):\n        for c in range(C):\n            if board[r][c] == "O": board[r][c] = "X"\n            elif board[r][c] == "#": board[r][c] = "O"', time: 'O(m*n)', timeWhy: 'each cell visited a constant number of times.', space: 'O(m*n)', spaceWhy: 'recursion/queue worst case.', pitfalls: ['Mark border-safe cells first; deciding capture per-cell without that global info is wrong.'] }),
  gen: function () { var o = [[['XXXX', 'XOOX', 'XXOX', 'XOXX']], [['OOO', 'OXO', 'OOO']]]; for (var k = 0; k < 36; k++) { var R = randInt(1, 4), C = randInt(1, 4), g = []; for (var i = 0; i < R; i++) { var s = ''; for (var j = 0; j < C; j++) s += (Math.random() < 0.5 ? 'X' : 'O'); g.push(s); } o.push([g]); } return o; },
  ref: function (a) { var g = a[0].map(function (s) { return s.split(''); }); var R = g.length, C = g[0].length; function dfs(r, c) { if (r < 0 || r >= R || c < 0 || c >= C || g[r][c] !== 'O') return; g[r][c] = '#'; dfs(r + 1, c); dfs(r - 1, c); dfs(r, c + 1); dfs(r, c - 1); } for (var r = 0; r < R; r++) { dfs(r, 0); dfs(r, C - 1); } for (var c = 0; c < C; c++) { dfs(0, c); dfs(R - 1, c); } for (r = 0; r < R; r++) for (c = 0; c < C; c++) { if (g[r][c] === 'O') g[r][c] = 'X'; else if (g[r][c] === '#') g[r][c] = 'O'; } return g.map(function (row) { return row.join(''); }).join('|'); } });

// ---- Word Ladder (STR_STR_ARRSTR_INT) ----
MORE12.push({ slug: 'word-ladder', title: 'Word Ladder', difficulty: 'hard', topics: ['Graph', 'BFS', 'Hash Table'], type: 'STR_STR_ARRSTR_INT', langsrc: T.STR_STR_ARRSTR_INT('ladderLength'),
  desc: '<p>Given <code>beginWord</code>, <code>endWord</code>, and a <code>wordList</code>, return the number of words in the shortest transformation sequence from begin to end (changing one letter at a time, each intermediate word in the list), or 0 if none. The count includes both endpoints.</p>',
  examples: [{ in: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]', out: '5' }, { in: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log"]', out: '0' }],
  constraints: ['1 &lt;= word length &lt;= 10', '1 &lt;= wordList.length &lt;= 5000', 'All words have the same length.'],
  editorial: ED({ intuition: 'Words are nodes; an edge connects two words differing by one letter. The shortest transformation is a shortest path, so BFS from beginWord finds it in the fewest steps.', approach: ['Put wordList in a set; if endWord is absent, return 0.', 'BFS from beginWord, tracking the level (sequence length).', 'From each word, try all one-letter changes; enqueue those in the set and not yet visited.'], code: 'from collections import deque\n\ndef ladderLength(self, beginWord, endWord, wordList):\n    words = set(wordList)\n    if endWord not in words:\n        return 0\n    q = deque([(beginWord, 1)])\n    seen = {beginWord}\n    while q:\n        w, d = q.popleft()\n        if w == endWord:\n            return d\n        for i in range(len(w)):\n            for c in "abcdefghijklmnopqrstuvwxyz":\n                nxt = w[:i] + c + w[i+1:]\n                if nxt in words and nxt not in seen:\n                    seen.add(nxt); q.append((nxt, d+1))\n    return 0', time: 'O(N * L * 26)', timeWhy: 'for each of N words, L positions times 26 letters.', space: 'O(N * L)', spaceWhy: 'the visited set and queue.' }),
  gen: function () {
    var o = [['hit', 'cog', ['hot', 'dot', 'dog', 'lot', 'log', 'cog']], ['hit', 'cog', ['hot', 'dot', 'dog', 'lot', 'log']]];
    for (var k = 0; k < 34; k++) { var L = 3, b = rw(L, L, 'abc'), e = rw(L, L, 'abc'), c = randInt(0, 6), w = []; for (var i = 0; i < c; i++) w.push(rw(L, L, 'abc')); o.push([b, e, w]); }
    return o;
  },
  ref: function (a) { var begin = a[0], end = a[1], words = {}; a[2].forEach(function (w) { words[w] = 1; }); if (!words[end]) return 0; var q = [[begin, 1]], seen = {}; seen[begin] = 1; var AL = 'abcdefghijklmnopqrstuvwxyz'; while (q.length) { var top = q.shift(), w = top[0], d = top[1]; if (w === end) return d; for (var i = 0; i < w.length; i++) for (var ci = 0; ci < 26; ci++) { var nxt = w.slice(0, i) + AL[ci] + w.slice(i + 1); if (words[nxt] && !seen[nxt]) { seen[nxt] = 1; q.push([nxt, d + 1]); } } } return 0; } });

module.exports = { MORE12 };
