// Batch E: mixed DP / stack / binary-search problems (reusing types).
const { T, randInt, randArr, ln } = require('./gen.js');

function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function ED(o) {
  var h = '';
  if (o.intuition) h += '<h3>Intuition</h3>' + (Array.isArray(o.intuition) ? o.intuition.map(function (p) { return '<p>' + p + '</p>'; }).join('') : '<p>' + o.intuition + '</p>');
  if (o.approach) h += '<h3>Approach</h3><ol>' + o.approach.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ol>';
  if (o.code) h += '<h3>Solution</h3><pre><code>' + esc(o.code) + '</code></pre>';
  h += '<h3>Complexity</h3><ul><li><b>Time — ' + o.time + ':</b> ' + o.timeWhy + '</li><li><b>Space — ' + o.space + ':</b> ' + o.spaceWhy + '</li></ul>';
  if (o.pitfalls) h += '<h3>Common Pitfalls</h3><ul>' + o.pitfalls.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ul>';
  return h;
}
function shuffle(a) { for (var i = a.length - 1; i > 0; i--) { var j = randInt(0, i); var t = a[i]; a[i] = a[j]; a[j] = t; } return a; }
function rw(minL, maxL, al) { var L = randInt(minL, maxL), s = ''; for (var i = 0; i < L; i++) s += al[randInt(0, al.length - 1)]; return s; }
function rotatedSorted(n) { var used = {}, vals = []; while (vals.length < n) { var v = randInt(-20, 20); if (!used[v]) { used[v] = 1; vals.push(v); } } vals.sort(function (a, b) { return a - b; }); var off = randInt(0, n - 1); return vals.slice(off).concat(vals.slice(0, off)); }

const MORE9 = [];

// ---- Daily Temperatures (ARR_ARR) ----
MORE9.push({ slug: 'daily-temperatures', title: 'Daily Temperatures', difficulty: 'medium', topics: ['Array', 'Stack', 'Monotonic Stack'], type: 'ARR_ARR', langsrc: T.ARR_ARR('dailyTemperatures'),
  desc: '<p>Given an array <code>temperatures</code>, return an array <code>answer</code> where <code>answer[i]</code> is the number of days you must wait after day <code>i</code> for a warmer temperature. If none, put 0.</p>',
  examples: [{ in: 'temperatures = [73,74,75,71,69,72,76,73]', out: '[1,1,4,2,1,1,0,0]' }, { in: 'temperatures = [30,40,50,60]', out: '[1,1,1,0]' }],
  constraints: ['1 &lt;= temperatures.length &lt;= 10^5', '30 &lt;= temperatures[i] &lt;= 100'],
  editorial: ED({ intuition: 'Keep a stack of days that are still "waiting" for a warmer day, with temperatures decreasing down the stack. When a warmer day arrives it resolves every colder day on top.', approach: ['Iterate with a stack of indices.', 'While the current temp exceeds the temp at the stack top, pop it and record the day gap.', 'Push the current index.'], code: 'def dailyTemperatures(self, temps):\n    res = [0] * len(temps)\n    stack = []\n    for i, t in enumerate(temps):\n        while stack and temps[stack[-1]] < t:\n            j = stack.pop()\n            res[j] = i - j\n        stack.append(i)\n    return res', time: 'O(n)', timeWhy: 'each index is pushed and popped at most once.', space: 'O(n)', spaceWhy: 'the stack.' }),
  gen: function () { var o = [[[73, 74, 75, 71, 69, 72, 76, 73]], [[30, 40, 50, 60]], [[90]]]; for (var k = 0; k < 40; k++) o.push([randArr(randInt(1, 12), 30, 40)]); return o; },
  ref: function (a) { var t = a[0], n = t.length, res = new Array(n).fill(0), st = []; for (var i = 0; i < n; i++) { while (st.length && t[st[st.length - 1]] < t[i]) { var j = st.pop(); res[j] = i - j; } st.push(i); } return res; } });

// ---- Evaluate Reverse Polish Notation (ARRSTR_INT) ----
MORE9.push({ slug: 'evaluate-reverse-polish-notation', title: 'Evaluate Reverse Polish Notation', difficulty: 'medium', topics: ['Array', 'Stack', 'Math'], type: 'ARRSTR_INT', langsrc: T.ARRSTR_INT('evalRPN'),
  desc: '<p>Evaluate an arithmetic expression in Reverse Polish Notation given as a list of <code>tokens</code>. Valid operators are <code>+ - * /</code>; division truncates toward zero.</p>',
  examples: [{ in: 'tokens = ["2","1","+","3","*"]', out: '9' }, { in: 'tokens = ["4","13","5","/","+"]', out: '6' }],
  constraints: ['1 &lt;= tokens.length &lt;= 10^4', 'Tokens are integers or one of + - * /.'],
  editorial: ED({ intuition: 'In postfix notation an operator applies to the two most recent results — exactly stack behaviour. Push numbers; on an operator, pop two and push the result.', approach: ['Scan tokens with a stack.', 'On a number, push it.', 'On an operator, pop the top two (order matters for - and /), compute, and push back.'], code: 'def evalRPN(self, tokens):\n    stack = []\n    for tok in tokens:\n        if tok in "+-*/" and len(tok) == 1:\n            b = stack.pop(); a = stack.pop()\n            if tok == "+": stack.append(a + b)\n            elif tok == "-": stack.append(a - b)\n            elif tok == "*": stack.append(a * b)\n            else: stack.append(int(a / b))\n        else:\n            stack.append(int(tok))\n    return stack[0]', time: 'O(n)', timeWhy: 'one pass over the tokens.', space: 'O(n)', spaceWhy: 'the operand stack.', pitfalls: ['Division truncates toward zero (use int(a/b) in Python, not floor division for negatives).'] }),
  gen: function () {
    var o = [[['2', '1', '+', '3', '*']], [['4', '13', '5', '/', '+']], [['5']]];
    var ops = ['+', '-', '*'];
    for (var k = 0; k < 40; k++) { var cnt = randInt(0, 4), toks = ['' + randInt(1, 9)]; for (var i = 0; i < cnt; i++) { toks.push('' + randInt(1, 9)); toks.push(ops[randInt(0, 2)]); } o.push([toks]); }
    return o;
  },
  ref: function (a) { var st = []; a[0].forEach(function (tok) { if ((tok === '+' || tok === '-' || tok === '*' || tok === '/')) { var b = st.pop(), x = st.pop(), r; if (tok === '+') r = x + b; else if (tok === '-') r = x - b; else if (tok === '*') r = x * b; else r = Math.trunc(x / b); st.push(r); } else st.push(parseInt(tok, 10)); }); return st[0]; } });

// ---- Largest Rectangle in Histogram (ARR_INT) ----
MORE9.push({ slug: 'largest-rectangle-in-histogram', title: 'Largest Rectangle in Histogram', difficulty: 'hard', topics: ['Array', 'Stack', 'Monotonic Stack'], type: 'ARR_INT', diagram: 'HIST', langsrc: T.ARR_INT('largestRectangleArea'),
  desc: '<p>Given an array <code>heights</code> of bar heights (each width 1), return the area of the largest rectangle that fits in the histogram.</p>',
  examples: [{ in: 'heights = [2,1,5,6,2,3]', out: '10' }, { in: 'heights = [2,4]', out: '4' }],
  constraints: ['1 &lt;= heights.length &lt;= 10^5', '0 &lt;= heights[i] &lt;= 10^4'],
  editorial: ED({ intuition: 'For each bar the widest rectangle of its height extends until a shorter bar on either side. A monotonic increasing stack lets you find, at the moment a bar is popped, exactly that left and right boundary.', approach: ['Keep a stack of indices with increasing heights.', 'When the current bar is shorter than the stack top, pop it; its height times the width between the new top and current index is a candidate area.', 'Use a trailing 0-height sentinel to flush the stack.'], code: 'def largestRectangleArea(self, heights):\n    stack = []\n    best = 0\n    for i, h in enumerate(heights + [0]):\n        while stack and heights[stack[-1]] > h:\n            height = heights[stack.pop()]\n            width = i if not stack else i - stack[-1] - 1\n            best = max(best, height * width)\n        stack.append(i)\n    return best', time: 'O(n)', timeWhy: 'each bar is pushed and popped once.', space: 'O(n)', spaceWhy: 'the stack.', pitfalls: ['Compute width from the index below the popped bar, not the popped index itself.'] }),
  gen: function () { var o = [[[2, 1, 5, 6, 2, 3]], [[2, 4]], [[0]], [[5, 5, 5]]]; for (var k = 0; k < 40; k++) o.push([randArr(randInt(1, 12), 0, 10)]); return o; },
  ref: function (a) { var h = a[0], n = h.length, st = [], best = 0; for (var i = 0; i <= n; i++) { var cur = i === n ? 0 : h[i]; while (st.length && h[st[st.length - 1]] > cur) { var height = h[st.pop()]; var width = st.length ? i - st[st.length - 1] - 1 : i; best = Math.max(best, height * width); } st.push(i); } return best; } });

// ---- Find Minimum in Rotated Sorted Array (ARR_INT) ----
MORE9.push({ slug: 'find-minimum-in-rotated-sorted-array', title: 'Find Minimum in Rotated Sorted Array', difficulty: 'medium', topics: ['Array', 'Binary Search'], type: 'ARR_INT', langsrc: T.ARR_INT('findMin'),
  desc: '<p>A sorted array of unique integers was rotated at some pivot. Given the array <code>nums</code>, return the minimum element in O(log n).</p>',
  examples: [{ in: 'nums = [3,4,5,1,2]', out: '1' }, { in: 'nums = [4,5,6,7,0,1,2]', out: '0' }],
  constraints: ['1 &lt;= nums.length &lt;= 5000', 'All integers are unique.', 'The array is a rotation of an ascending sort.'],
  editorial: ED({ intuition: 'Compare the middle element to the rightmost. If the middle is bigger, the rotation point (and thus the minimum) lies to its right; otherwise it is at the middle or to its left.', approach: ['Binary search with lo, hi.', 'If <code>nums[mid] &gt; nums[hi]</code>, the min is in <code>(mid, hi]</code>, so lo = mid + 1.', 'Else hi = mid. Converge to the minimum.'], code: 'def findMin(self, nums):\n    lo, hi = 0, len(nums) - 1\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if nums[mid] > nums[hi]:\n            lo = mid + 1\n        else:\n            hi = mid\n    return nums[lo]', time: 'O(log n)', timeWhy: 'the search space halves each step.', space: 'O(1)', spaceWhy: 'two pointers.', pitfalls: ['Compare against the right end, not the left, so a non-rotated array still works.'] }),
  gen: function () { var o = [[[3, 4, 5, 1, 2]], [[4, 5, 6, 7, 0, 1, 2]], [[11]], [[1, 2, 3]]]; for (var k = 0; k < 40; k++) o.push([rotatedSorted(randInt(1, 10))]); return o; },
  ref: function (a) { var n = a[0], lo = 0, hi = n.length - 1; while (lo < hi) { var mid = (lo + hi) >> 1; if (n[mid] > n[hi]) lo = mid + 1; else hi = mid; } return n[lo]; } });

// ---- Search in Rotated Sorted Array (ARR_TGT_INT) ----
MORE9.push({ slug: 'search-in-rotated-sorted-array', title: 'Search in Rotated Sorted Array', difficulty: 'medium', topics: ['Array', 'Binary Search'], type: 'ARR_TGT_INT', langsrc: T.ARR_TGT_INT('search'),
  desc: '<p>Given a rotated ascending array of distinct integers <code>nums</code> and a <code>target</code>, return its index or <code>-1</code>. Must run in O(log n).</p>',
  examples: [{ in: 'nums = [4,5,6,7,0,1,2], target = 0', out: '4' }, { in: 'nums = [4,5,6,7,0,1,2], target = 3', out: '-1' }],
  constraints: ['1 &lt;= nums.length &lt;= 5000', 'All values distinct.', 'nums is a rotation of an ascending array.'],
  editorial: ED({ intuition: 'At any midpoint, at least one half (left or right) is properly sorted. Detect which half is sorted, and check whether the target lies within that sorted range to decide where to continue.', approach: ['Binary search; compute mid.', 'If the left half is sorted and target is inside it, search left; else search right.', 'Symmetrically if the right half is sorted.'], code: 'def search(self, nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[lo] <= nums[mid]:\n            if nums[lo] <= target < nums[mid]:\n                hi = mid - 1\n            else:\n                lo = mid + 1\n        else:\n            if nums[mid] < target <= nums[hi]:\n                lo = mid + 1\n            else:\n                hi = mid - 1\n    return -1', time: 'O(log n)', timeWhy: 'standard binary search.', space: 'O(1)', spaceWhy: 'constant.', pitfalls: ['Use <= when testing which half is sorted to handle the two-element case.'] }),
  gen: function () { var o = [[[4, 5, 6, 7, 0, 1, 2], 0], [[4, 5, 6, 7, 0, 1, 2], 3], [[1], 1], [[1], 0]]; for (var k = 0; k < 40; k++) { var arr = rotatedSorted(randInt(1, 10)); var t = (Math.random() < 0.6) ? arr[randInt(0, arr.length - 1)] : randInt(-25, 25); o.push([arr, t]); } return o; },
  ref: function (a) { var n = a[0], t = a[1], lo = 0, hi = n.length - 1; while (lo <= hi) { var mid = (lo + hi) >> 1; if (n[mid] === t) return mid; if (n[lo] <= n[mid]) { if (n[lo] <= t && t < n[mid]) hi = mid - 1; else lo = mid + 1; } else { if (n[mid] < t && t <= n[hi]) lo = mid + 1; else hi = mid - 1; } } return -1; } });

// ---- Permutation in String (STR_STR_BOOL) ----
MORE9.push({ slug: 'permutation-in-string', title: 'Permutation in String', difficulty: 'medium', topics: ['String', 'Sliding Window', 'Hash Table'], type: 'STR_STR_BOOL', langsrc: T.STR_STR_BOOL('checkInclusion'),
  desc: "<p>Given two strings <code>s1</code> and <code>s2</code>, return <code>true</code> if <code>s2</code> contains a permutation of <code>s1</code> as a contiguous substring. (Here the first line is s1, the second is s2.)</p>",
  examples: [{ in: 's1 = "ab", s2 = "eidbaooo"', out: 'true' }, { in: 's1 = "ab", s2 = "eidboaoo"', out: 'false' }],
  constraints: ['1 &lt;= s1.length, s2.length &lt;= 10^4', 's1 and s2 consist of lowercase English letters.'],
  editorial: ED({ intuition: 'A permutation of s1 is any window of s2 with the same letter counts as s1. Slide a fixed-size window (length |s1|) over s2 and compare frequency vectors.', approach: ['Build the 26-length count of s1 and of the first window of s2.', 'Slide the window one char at a time, updating counts in O(1).', 'Return true whenever the counts match.'], code: 'def checkInclusion(self, s1, s2):\n    if len(s1) > len(s2):\n        return False\n    need = [0]*26; win = [0]*26\n    for c in s1: need[ord(c)-97] += 1\n    for i, c in enumerate(s2):\n        win[ord(c)-97] += 1\n        if i >= len(s1):\n            win[ord(s2[i-len(s1)])-97] -= 1\n        if win == need:\n            return True\n    return False', time: 'O(n)', timeWhy: 'each character enters and leaves the window once; comparison is O(26).', space: 'O(1)', spaceWhy: 'two fixed 26-length arrays.' }),
  gen: function () {
    var o = [['ab', 'eidbaooo'], ['ab', 'eidboaoo'], ['a', 'a']];
    for (var k = 0; k < 40; k++) { var s1 = rw(1, 4, 'abc'); var s2; if (Math.random() < 0.5) { var perm = shuffle(s1.split('')).join(''); s2 = rw(0, 3, 'abc') + perm + rw(0, 3, 'abc'); } else s2 = rw(1, 8, 'abc'); o.push([s1, s2]); }
    return o;
  },
  ref: function (a) { var s1 = a[0], s2 = a[1]; if (s1.length > s2.length) return false; var need = new Array(26).fill(0), win = new Array(26).fill(0); for (var i = 0; i < s1.length; i++) need[s1.charCodeAt(i) - 97]++; for (i = 0; i < s2.length; i++) { win[s2.charCodeAt(i) - 97]++; if (i >= s1.length) win[s2.charCodeAt(i - s1.length) - 97]--; if (i >= s1.length - 1) { var ok = true; for (var j = 0; j < 26; j++) if (win[j] !== need[j]) { ok = false; break; } if (ok) return true; } } return false; } });

// ---- Best Time to Buy and Sell Stock with Cooldown (ARR_INT) ----
MORE9.push({ slug: 'best-time-to-buy-and-sell-stock-with-cooldown', title: 'Best Time to Buy and Sell Stock with Cooldown', difficulty: 'medium', topics: ['Array', 'Dynamic Programming'], type: 'ARR_INT', langsrc: T.ARR_INT('maxProfit'),
  desc: '<p>Given daily stock <code>prices</code>, maximize profit with as many transactions as you like, but after you sell you must cooldown one day before buying again. Return the max profit.</p>',
  examples: [{ in: 'prices = [1,2,3,0,2]', out: '3', ex: 'buy, sell, cooldown, buy, sell.' }, { in: 'prices = [1]', out: '0' }],
  constraints: ['1 &lt;= prices.length &lt;= 5000', '0 &lt;= prices[i] &lt;= 1000'],
  editorial: ED({ intuition: 'Track three daily states: <code>hold</code> (currently own a share), <code>sold</code> (just sold today), and <code>rest</code> (idle, free to buy). The cooldown is enforced because you can only buy from <code>rest</code>, and selling moves you to <code>sold</code> which becomes rest tomorrow.', approach: ['hold = max(hold, rest - price) — keep holding or buy from rest.', 'sold = hold + price — sell what you held.', 'rest = max(rest, prev_sold) — stay idle or come off cooldown.'], code: 'def maxProfit(self, prices):\n    hold, sold, rest = float("-inf"), 0, 0\n    for p in prices:\n        prev_sold = sold\n        sold = hold + p\n        hold = max(hold, rest - p)\n        rest = max(rest, prev_sold)\n    return max(sold, rest)', time: 'O(n)', timeWhy: 'one pass, constant work per day.', space: 'O(1)', spaceWhy: 'three rolling variables.' }),
  gen: function () { var o = [[[1, 2, 3, 0, 2]], [[1]], [[1, 2, 4]], [[6, 1, 3, 2, 4, 7]]]; for (var k = 0; k < 40; k++) o.push([randArr(randInt(1, 12), 0, 12)]); return o; },
  ref: function (a) { var prices = a[0], hold = -Infinity, sold = 0, rest = 0; for (var i = 0; i < prices.length; i++) { var ps = sold; sold = hold + prices[i]; hold = Math.max(hold, rest - prices[i]); rest = Math.max(rest, ps); } return Math.max(sold, rest); } });

// ---- Burst Balloons (ARR_INT) ----
MORE9.push({ slug: 'burst-balloons', title: 'Burst Balloons', difficulty: 'hard', topics: ['Array', 'Dynamic Programming', 'Interval DP'], type: 'ARR_INT', langsrc: T.ARR_INT('maxCoins'),
  desc: '<p>You have <code>n</code> balloons with numbers in <code>nums</code>. Bursting balloon <code>i</code> gives <code>nums[i-1]*nums[i]*nums[i+1]</code> coins (treat out-of-range as 1). Return the maximum coins from bursting all balloons.</p>',
  examples: [{ in: 'nums = [3,1,5,8]', out: '167' }, { in: 'nums = [1,5]', out: '10' }],
  constraints: ['1 &lt;= n &lt;= 300', '0 &lt;= nums[i] &lt;= 100'],
  editorial: ED({ intuition: 'Deciding which balloon to burst <em>first</em> is hard because it changes neighbours. Flip it: consider which balloon is burst <em>last</em> in a range — then its neighbours are the fixed range boundaries, giving clean subproblems.', approach: ['Pad the array with 1 on both ends.', 'dp[i][j] = max coins bursting all balloons strictly between i and j.', 'For each last-burst k in (i, j): dp[i][j] = max(dp[i][k] + nums[i]*nums[k]*nums[j] + dp[k][j]).'], code: 'def maxCoins(self, nums):\n    nums = [1] + nums + [1]\n    n = len(nums)\n    dp = [[0]*n for _ in range(n)]\n    for length in range(2, n):\n        for i in range(n - length):\n            j = i + length\n            for k in range(i+1, j):\n                dp[i][j] = max(dp[i][j], dp[i][k] + nums[i]*nums[k]*nums[j] + dp[k][j])\n    return dp[0][n-1]', time: 'O(n^3)', timeWhy: 'over all O(n^2) ranges, an O(n) choice of the last balloon.', space: 'O(n^2)', spaceWhy: 'the interval DP table.', pitfalls: ['Think "last to burst," not "first," so the boundaries stay fixed.'] }),
  gen: function () { var o = [[[3, 1, 5, 8]], [[1, 5]], [[5]], [[9, 76, 64, 21]]]; for (var k = 0; k < 34; k++) o.push([randArr(randInt(1, 7), 0, 9)]); return o; },
  ref: function (a) { var nums = [1].concat(a[0], [1]), n = nums.length, dp = []; for (var i = 0; i < n; i++) dp.push(new Array(n).fill(0)); for (var len = 2; len < n; len++) for (i = 0; i < n - len; i++) { var j = i + len; for (var k = i + 1; k < j; k++) dp[i][j] = Math.max(dp[i][j], dp[i][k] + nums[i] * nums[k] * nums[j] + dp[k][j]); } return dp[0][n - 1]; } });

// ---- Regular Expression Matching (STR_STR_BOOL) ----
MORE9.push({ slug: 'regular-expression-matching', title: 'Regular Expression Matching', difficulty: 'hard', topics: ['String', 'Dynamic Programming', 'Recursion'], type: 'STR_STR_BOOL', langsrc: T.STR_STR_BOOL('isMatch'),
  desc: "<p>Given a string <code>s</code> (first line) and a pattern <code>p</code> (second line) supporting <code>.</code> (any single char) and <code>*</code> (zero or more of the preceding element), return <code>true</code> if the pattern matches the entire string.</p>",
  examples: [{ in: 's = "aa", p = "a*"', out: 'true' }, { in: 's = "ab", p = ".*"', out: 'true' }, { in: 's = "mississippi", p = "mis*is*p*."', out: 'false' }],
  constraints: ['1 &lt;= s.length &lt;= 20', '1 &lt;= p.length &lt;= 20', 'Each * has a valid preceding element.'],
  editorial: ED({ intuition: 'Let <code>dp[i][j]</code> mean "s[:i] matches p[:j]." A <code>*</code> either drops the preceding element (zero copies) or, if that element matches the current char, consumes one char and stays.', approach: ['Handle empty-string vs patterns like <code>a*b*</code> in the base row.', 'For a normal char or ".": dp[i][j] from dp[i-1][j-1] when they match.', 'For "*": dp[i][j] = dp[i][j-2] (zero) OR (preceding matches s[i-1] AND dp[i-1][j]).'], code: 'def isMatch(self, s, p):\n    dp = [[False]*(len(p)+1) for _ in range(len(s)+1)]\n    dp[0][0] = True\n    for j in range(1, len(p)+1):\n        if p[j-1] == "*":\n            dp[0][j] = dp[0][j-2]\n    for i in range(1, len(s)+1):\n        for j in range(1, len(p)+1):\n            if p[j-1] == "*":\n                dp[i][j] = dp[i][j-2] or (p[j-2] in (s[i-1], ".") and dp[i-1][j])\n            elif p[j-1] in (s[i-1], "."):\n                dp[i][j] = dp[i-1][j-1]\n    return dp[len(s)][len(p)]', time: 'O(m*n)', timeWhy: 'fill an (m+1) x (n+1) table.', space: 'O(m*n)', spaceWhy: 'the DP table.', pitfalls: ['For "*", the zero-copy branch looks back two positions (the char and the star).'] }),
  gen: function () {
    function genP() { var s = '', L = randInt(1, 4); for (var i = 0; i < L; i++) { s += 'ab.'[randInt(0, 2)]; if (Math.random() < 0.5) s += '*'; } return s; }
    var o = [['aa', 'a*'], ['ab', '.*'], ['mississippi', 'mis*is*p*.'], ['aa', 'a'], ['', 'a*']];
    for (var k = 0; k < 40; k++) o.push([rw(0, 4, 'ab'), genP()]);
    return o;
  },
  ref: function (a) { var s = a[0], p = a[1], m = s.length, n = p.length, dp = []; for (var i = 0; i <= m; i++) dp.push(new Array(n + 1).fill(false)); dp[0][0] = true; for (var j = 1; j <= n; j++) if (p[j - 1] === '*') dp[0][j] = dp[0][j - 2]; for (i = 1; i <= m; i++) for (j = 1; j <= n; j++) { if (p[j - 1] === '*') dp[i][j] = dp[i][j - 2] || ((p[j - 2] === s[i - 1] || p[j - 2] === '.') && dp[i - 1][j]); else if (p[j - 1] === s[i - 1] || p[j - 1] === '.') dp[i][j] = dp[i - 1][j - 1]; } return dp[m][n]; } });

// ---- Longest Common Subsequence (STR_STR_INT) ----
MORE9.push({ slug: 'longest-common-subsequence', title: 'Longest Common Subsequence', difficulty: 'medium', topics: ['String', 'Dynamic Programming'], type: 'STR_STR_INT', langsrc: T.STR_STR_INT('longestCommonSubsequence'),
  desc: '<p>Given two strings <code>text1</code> and <code>text2</code>, return the length of their longest common subsequence (characters in order, not necessarily contiguous). Return 0 if none.</p>',
  examples: [{ in: 'text1 = "abcde", text2 = "ace"', out: '3' }, { in: 'text1 = "abc", text2 = "def"', out: '0' }],
  constraints: ['1 &lt;= text1.length, text2.length &lt;= 1000', 'Inputs consist of lowercase English letters.'],
  editorial: ED({ intuition: 'Compare the two strings position by position. If the current characters match, the LCS grows by one from the diagonal; otherwise take the best of dropping one character from either string.', approach: ['dp[i][j] = LCS length of the first i chars of s and first j of t.', 'If s[i-1] == t[j-1]: dp[i][j] = dp[i-1][j-1] + 1.', 'Else dp[i][j] = max(dp[i-1][j], dp[i][j-1]).'], code: 'def longestCommonSubsequence(self, s, t):\n    dp = [[0]*(len(t)+1) for _ in range(len(s)+1)]\n    for i in range(1, len(s)+1):\n        for j in range(1, len(t)+1):\n            if s[i-1] == t[j-1]:\n                dp[i][j] = dp[i-1][j-1] + 1\n            else:\n                dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n    return dp[len(s)][len(t)]', time: 'O(m*n)', timeWhy: 'fill the full table.', space: 'O(m*n)', spaceWhy: 'the DP grid (reducible to O(min(m,n))).' }),
  gen: function () { var o = [['abcde', 'ace'], ['abc', 'def'], ['a', 'a'], ['bl', 'yby']]; for (var k = 0; k < 40; k++) o.push([rw(1, 7, 'abc'), rw(1, 7, 'abc')]); return o; },
  ref: function (a) { var s = a[0], t = a[1], m = s.length, n = t.length, dp = []; for (var i = 0; i <= m; i++) dp.push(new Array(n + 1).fill(0)); for (i = 1; i <= m; i++) for (var j = 1; j <= n; j++) dp[i][j] = s[i - 1] === t[j - 1] ? dp[i - 1][j - 1] + 1 : Math.max(dp[i - 1][j], dp[i][j - 1]); return dp[m][n]; } });

// ---- Edit Distance (STR_STR_INT) ----
MORE9.push({ slug: 'edit-distance', title: 'Edit Distance', difficulty: 'medium', topics: ['String', 'Dynamic Programming'], type: 'STR_STR_INT', langsrc: T.STR_STR_INT('minDistance'),
  desc: '<p>Given two strings <code>word1</code> and <code>word2</code>, return the minimum number of operations (insert, delete, or replace a character) to convert word1 into word2.</p>',
  examples: [{ in: 'word1 = "horse", word2 = "ros"', out: '3' }, { in: 'word1 = "intention", word2 = "execution"', out: '5' }],
  constraints: ['0 &lt;= word1.length, word2.length &lt;= 500', 'Inputs consist of lowercase English letters.'],
  editorial: ED({ intuition: 'dp[i][j] is the edit distance between the first i chars of word1 and first j of word2. If the current chars match, no new op is needed; otherwise you pay 1 for the cheapest of insert, delete, or replace.', approach: ['Base cases: converting to/from an empty string costs its length.', 'If chars equal: dp[i][j] = dp[i-1][j-1].', 'Else 1 + min(dp[i-1][j] delete, dp[i][j-1] insert, dp[i-1][j-1] replace).'], code: 'def minDistance(self, s, t):\n    m, n = len(s), len(t)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0] = i\n    for j in range(n+1): dp[0][j] = j\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            if s[i-1] == t[j-1]:\n                dp[i][j] = dp[i-1][j-1]\n            else:\n                dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n    return dp[m][n]', time: 'O(m*n)', timeWhy: 'fill the full table.', space: 'O(m*n)', spaceWhy: 'the DP grid.' }),
  gen: function () { var o = [['horse', 'ros'], ['intention', 'execution'], ['', 'abc'], ['ab', 'ab']]; for (var k = 0; k < 40; k++) o.push([rw(0, 7, 'abc'), rw(0, 7, 'abc')]); return o; },
  ref: function (a) { var s = a[0], t = a[1], m = s.length, n = t.length, dp = []; for (var i = 0; i <= m; i++) { dp.push(new Array(n + 1).fill(0)); dp[i][0] = i; } for (var j = 0; j <= n; j++) dp[0][j] = j; for (i = 1; i <= m; i++) for (j = 1; j <= n; j++) dp[i][j] = s[i - 1] === t[j - 1] ? dp[i - 1][j - 1] : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]); return dp[m][n]; } });

// ---- Distinct Subsequences (STR_STR_INT) ----
MORE9.push({ slug: 'distinct-subsequences', title: 'Distinct Subsequences', difficulty: 'hard', topics: ['String', 'Dynamic Programming'], type: 'STR_STR_INT', langsrc: T.STR_STR_INT('numDistinct'),
  desc: '<p>Given two strings <code>s</code> and <code>t</code>, return the number of distinct subsequences of <code>s</code> that equal <code>t</code>. The answer fits in a 32-bit integer.</p>',
  examples: [{ in: 's = "rabbbit", t = "rabbit"', out: '3' }, { in: 's = "babgbag", t = "bag"', out: '5' }],
  constraints: ['1 &lt;= s.length, t.length &lt;= 1000', 'Inputs consist of English letters.'],
  editorial: ED({ intuition: 'dp[i][j] counts how many subsequences of the first i chars of s equal the first j chars of t. When the current chars match you may either use s[i-1] to cover t[j-1] or skip it; when they differ you can only skip it.', approach: ['dp[i][0] = 1 (empty t is matched by exactly one subsequence).', 'If s[i-1] == t[j-1]: dp[i][j] = dp[i-1][j-1] + dp[i-1][j].', 'Else dp[i][j] = dp[i-1][j].'], code: 'def numDistinct(self, s, t):\n    m, n = len(s), len(t)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0] = 1\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            dp[i][j] = dp[i-1][j]\n            if s[i-1] == t[j-1]:\n                dp[i][j] += dp[i-1][j-1]\n    return dp[m][n]', time: 'O(m*n)', timeWhy: 'fill the table.', space: 'O(m*n)', spaceWhy: 'the DP grid (reducible to O(n)).' }),
  gen: function () { var o = [['rabbbit', 'rabbit'], ['babgbag', 'bag'], ['a', 'a'], ['aa', 'a']]; for (var k = 0; k < 40; k++) o.push([rw(1, 7, 'ab'), rw(1, 4, 'ab')]); return o; },
  ref: function (a) { var s = a[0], t = a[1], m = s.length, n = t.length, dp = []; for (var i = 0; i <= m; i++) { dp.push(new Array(n + 1).fill(0)); dp[i][0] = 1; } for (i = 1; i <= m; i++) for (var j = 1; j <= n; j++) { dp[i][j] = dp[i - 1][j]; if (s[i - 1] === t[j - 1]) dp[i][j] += dp[i - 1][j - 1]; } return dp[m][n]; } });

// ---- Coin Change II (ARR_INT_INT) ----
MORE9.push({ slug: 'coin-change-ii', title: 'Coin Change II', difficulty: 'medium', topics: ['Array', 'Dynamic Programming'], type: 'ARR_INT_INT', langsrc: T.ARR_INT_INT('change'),
  desc: '<p>You are given coin denominations <code>nums</code> and a target amount <code>k</code>. Return the number of distinct combinations that make up the amount (order does not matter). Return 0 if impossible.</p>',
  examples: [{ in: 'nums = [1,2,5], k = 5', out: '4' }, { in: 'nums = [2], k = 3', out: '0' }],
  constraints: ['1 &lt;= nums.length &lt;= 300', '1 &lt;= nums[i] &lt;= 5000', '0 &lt;= k &lt;= 5000'],
  editorial: ED({ intuition: 'To count <em>combinations</em> (not permutations), iterate coins in the outer loop so each coin is considered once — this prevents counting the same multiset in different orders.', approach: ['dp[a] = number of ways to make amount a; dp[0] = 1.', 'For each coin, for each amount a from coin to k: dp[a] += dp[a-coin].', 'The coin-outer ordering is what enforces combinations.'], code: 'def change(self, coins, amount):\n    dp = [0]*(amount+1)\n    dp[0] = 1\n    for coin in coins:\n        for a in range(coin, amount+1):\n            dp[a] += dp[a-coin]\n    return dp[amount]', time: 'O(coins*amount)', timeWhy: 'each coin sweeps the amount array.', space: 'O(amount)', spaceWhy: 'the 1-D dp array.', pitfalls: ['Coins outer, amount inner — swapping the loops counts ordered permutations instead.'] }),
  gen: function () { var o = [[[1, 2, 5], 5], [[2], 3], [[1], 0], [[3, 5, 7], 12]]; for (var k = 0; k < 36; k++) { var m = randInt(1, 4), used = {}, coins = []; while (coins.length < m) { var c = randInt(1, 8); if (!used[c]) { used[c] = 1; coins.push(c); } } o.push([coins, randInt(0, 15)]); } return o; },
  ref: function (a) { var coins = a[0], amount = a[1], dp = new Array(amount + 1).fill(0); dp[0] = 1; coins.forEach(function (coin) { for (var x = coin; x <= amount; x++) dp[x] += dp[x - coin]; }); return dp[amount]; } });

// ---- Target Sum (ARR_INT_INT) ----
MORE9.push({ slug: 'target-sum', title: 'Target Sum', difficulty: 'medium', topics: ['Array', 'Dynamic Programming', 'Backtracking'], type: 'ARR_INT_INT', langsrc: T.ARR_INT_INT('findTargetSumWays'),
  desc: '<p>Given an array <code>nums</code> and an integer target <code>k</code>, assign a <code>+</code> or <code>-</code> to each number and count the assignments whose sum equals <code>k</code>.</p>',
  examples: [{ in: 'nums = [1,1,1,1,1], k = 3', out: '5' }, { in: 'nums = [1], k = 1', out: '1' }],
  constraints: ['1 &lt;= nums.length &lt;= 20', '0 &lt;= nums[i] &lt;= 1000', '-1000 &lt;= k &lt;= 1000'],
  editorial: ED({ intuition: 'Group numbers into a positive set P and negative set N. Then <code>sum(P) - sum(N) = k</code> and <code>sum(P) + sum(N) = total</code>, so <code>sum(P) = (total + k) / 2</code>. Counting assignments becomes a subset-sum count.', approach: ['If (total + k) is odd or |k| &gt; total, there are 0 ways.', 'Let target = (total + k) / 2; count subsets summing to target with a 0/1-knapsack dp.', 'dp[s] += dp[s - num] for each num.'], code: 'def findTargetSumWays(self, nums, k):\n    total = sum(nums)\n    if (total + k) % 2 or abs(k) > total:\n        return 0\n    target = (total + k) // 2\n    dp = [0]*(target+1)\n    dp[0] = 1\n    for num in nums:\n        for s in range(target, num-1, -1):\n            dp[s] += dp[s-num]\n    return dp[target]', time: 'O(n*sum)', timeWhy: 'subset-sum dp over all numbers.', space: 'O(sum)', spaceWhy: 'the 1-D dp array.', pitfalls: ['Guard the parity and range of (total + k) before dividing by 2.'] }),
  gen: function () { var o = [[[1, 1, 1, 1, 1], 3], [[1], 1], [[1], 2], [[0, 0, 1], 1]]; for (var k = 0; k < 36; k++) { var n = randInt(1, 8), arr = randArr(n, 0, 5); var total = arr.reduce(function (x, y) { return x + y; }, 0); o.push([arr, randInt(-total, total)]); } return o; },
  ref: function (a) { var nums = a[0], k = a[1], total = nums.reduce(function (x, y) { return x + y; }, 0); if ((total + k) % 2 !== 0 || Math.abs(k) > total) return 0; var target = (total + k) / 2, dp = new Array(target + 1).fill(0); dp[0] = 1; nums.forEach(function (num) { for (var s = target; s >= num; s--) dp[s] += dp[s - num]; }); return dp[target]; } });

module.exports = { MORE9 };
