// Batch B: grid / matrix problems.
const { T, randInt, ln } = require('./gen.js');

function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function ED(o) {
  var h = '';
  if (o.intuition) h += '<h3>Intuition</h3>' + (Array.isArray(o.intuition) ? o.intuition.map(function (p) { return '<p>' + p + '</p>'; }).join('') : '<p>' + o.intuition + '</p>');
  if (o.approach) h += '<h3>Approach</h3><ol>' + o.approach.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ol>';
  if (o.code) h += '<h3>Solution</h3><pre><code>' + esc(o.code) + '</code></pre>';
  h += '<h3>Complexity</h3><ul><li><b>Time — ' + o.time + ':</b> ' + o.timeWhy + '</li><li><b>Space — ' + o.space + ':</b> ' + o.spaceWhy + '</li></ul>';
  if (o.pitfalls) h += '<h3>Common Pitfalls</h3><ul>' + o.pitfalls.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ul>';
  return h;
}
function intGrid(R, C, lo, hi) { var g = []; for (var i = 0; i < R; i++) { var row = []; for (var j = 0; j < C; j++) row.push(randInt(lo, hi)); g.push(row); } return g; }

const MORE6 = [];

// ---- Number of Islands (CHARGRID_INT) ----
MORE6.push({ slug: 'number-of-islands', title: 'Number of Islands', difficulty: 'medium', topics: ['Graph', 'DFS', 'BFS', 'Union Find', 'Matrix'], type: 'CHARGRID_INT', langsrc: T.CHARGRID_INT('numIslands'),
  desc: "<p>Given an <code>m x n</code> grid of <code>'1'</code> (land) and <code>'0'</code> (water), return the number of islands. An island is surrounded by water and formed by connecting adjacent land cells horizontally or vertically.</p>",
  examples: [{ in: 'grid = ["11110","11010","11000","00000"]', out: '1' }, { in: 'grid = ["11000","11000","00100","00011"]', out: '3' }],
  constraints: ['1 &lt;= m, n &lt;= 300', "grid[i][j] is '0' or '1'."],
  editorial: ED({ intuition: 'Each island is a connected component of land cells. Walk the grid; every time you hit an unvisited land cell you have found a new island, so you flood-fill (sink) the whole component before continuing.', approach: ['Scan every cell.', "When you find a '1', increment the count and run DFS/BFS to turn all connected land into water so it is not counted again.", 'The flood fill visits the 4 orthogonal neighbours.'], code: "def numIslands(self, grid):\n    R, C = len(grid), len(grid[0])\n    def sink(r, c):\n        if r < 0 or r >= R or c < 0 or c >= C or grid[r][c] != '1':\n            return\n        grid[r][c] = '0'\n        sink(r+1, c); sink(r-1, c); sink(r, c+1); sink(r, c-1)\n    count = 0\n    for r in range(R):\n        for c in range(C):\n            if grid[r][c] == '1':\n                count += 1\n                sink(r, c)\n    return count", time: 'O(m*n)', timeWhy: 'each cell is visited a constant number of times.', space: 'O(m*n)', spaceWhy: 'recursion/queue depth in the worst case of one giant island.', pitfalls: ['Mark cells visited (sink them) as you go, or you will count the same island many times.'] }),
  gen: function () { var o = [[['11110', '11010', '11000', '00000']], [['11000', '11000', '00100', '00011']], [['0']], [['1']]]; for (var k = 0; k < 34; k++) { var R = randInt(1, 5), C = randInt(1, 5), g = []; for (var i = 0; i < R; i++) { var s = ''; for (var j = 0; j < C; j++) s += (Math.random() < 0.55 ? '1' : '0'); g.push(s); } o.push([g]); } return o; },
  ref: function (a) { var grid = a[0].map(function (s) { return s.split(''); }); var R = grid.length, C = grid[0].length; function sink(r, c) { if (r < 0 || r >= R || c < 0 || c >= C || grid[r][c] !== '1') return; grid[r][c] = '0'; sink(r + 1, c); sink(r - 1, c); sink(r, c + 1); sink(r, c - 1); } var count = 0; for (var r = 0; r < R; r++) for (var c = 0; c < C; c++) if (grid[r][c] === '1') { count++; sink(r, c); } return count; } });

// ---- Max Area of Island (GRID_INT) ----
MORE6.push({ slug: 'max-area-of-island', title: 'Max Area of Island', difficulty: 'medium', topics: ['Graph', 'DFS', 'BFS', 'Matrix'], type: 'GRID_INT', langsrc: T.GRID_INT('maxAreaOfIsland'),
  desc: '<p>Given an <code>m x n</code> binary grid, return the area (number of cells) of the largest island. Cells connect horizontally or vertically. If there is no island, return 0.</p>',
  examples: [{ in: 'grid = [[0,0,1,0],[1,1,1,0],[0,1,0,0]]', out: '5' }, { in: 'grid = [[0,0,0],[0,0,0]]', out: '0' }],
  constraints: ['1 &lt;= m, n &lt;= 50', 'grid[i][j] is 0 or 1.'],
  editorial: ED({ intuition: 'Same flood-fill as counting islands, except instead of counting components you sum the cells in each component and track the maximum.', approach: ['For each unvisited land cell, DFS returns the size of its component.', 'DFS sinks the cell (set to 0) and adds 1 plus the sizes of its four neighbours.', 'Keep the maximum size seen.'], code: 'def maxAreaOfIsland(self, grid):\n    R, C = len(grid), len(grid[0])\n    def dfs(r, c):\n        if r < 0 or r >= R or c < 0 or c >= C or grid[r][c] == 0:\n            return 0\n        grid[r][c] = 0\n        return 1 + dfs(r+1,c) + dfs(r-1,c) + dfs(r,c+1) + dfs(r,c-1)\n    return max((dfs(r, c) for r in range(R) for c in range(C)), default=0)', time: 'O(m*n)', timeWhy: 'each cell is visited once.', space: 'O(m*n)', spaceWhy: 'recursion depth.' }),
  gen: function () { var o = [[[[0, 0, 1, 0], [1, 1, 1, 0], [0, 1, 0, 0]]], [[[0, 0, 0], [0, 0, 0]]], [[[1]]]]; for (var k = 0; k < 35; k++) o.push([intGrid(randInt(1, 5), randInt(1, 5), 0, 1).map(function (r) { return r.map(function () { return Math.random() < 0.5 ? 1 : 0; }); })]); return o; },
  ref: function (a) { var g = a[0].map(function (r) { return r.slice(); }); var R = g.length, C = g[0].length; function dfs(r, c) { if (r < 0 || r >= R || c < 0 || c >= C || g[r][c] === 0) return 0; g[r][c] = 0; return 1 + dfs(r + 1, c) + dfs(r - 1, c) + dfs(r, c + 1) + dfs(r, c - 1); } var best = 0; for (var r = 0; r < R; r++) for (var c = 0; c < C; c++) best = Math.max(best, dfs(r, c)); return best; } });

// ---- Rotting Oranges (GRID_INT) ----
MORE6.push({ slug: 'rotting-oranges', title: 'Rotting Oranges', difficulty: 'medium', topics: ['Graph', 'BFS', 'Matrix'], type: 'GRID_INT', langsrc: T.GRID_INT('orangesRotting'),
  desc: '<p>In an <code>m x n</code> grid each cell is <code>0</code> (empty), <code>1</code> (fresh orange), or <code>2</code> (rotten). Every minute, a fresh orange adjacent (4-directionally) to a rotten one becomes rotten. Return the minutes until no fresh orange remains, or <code>-1</code> if impossible.</p>',
  examples: [{ in: 'grid = [[2,1,1],[1,1,0],[0,1,1]]', out: '4' }, { in: 'grid = [[2,1,1],[0,1,1],[1,0,1]]', out: '-1' }],
  constraints: ['1 &lt;= m, n &lt;= 10', 'grid[i][j] is 0, 1, or 2.'],
  editorial: ED({ intuition: 'Rot spreads outward one layer per minute from ALL currently-rotten oranges simultaneously — that is textbook multi-source BFS. The number of BFS levels is the answer.', approach: ['Push every rotten orange into the initial queue and count fresh oranges.', 'Process the queue level by level; each level is one minute, rotting fresh neighbours.', 'If any fresh remain at the end, return -1; else return the elapsed minutes.'], code: 'from collections import deque\n\ndef orangesRotting(self, grid):\n    R, C = len(grid), len(grid[0])\n    q = deque()\n    fresh = 0\n    for r in range(R):\n        for c in range(C):\n            if grid[r][c] == 2: q.append((r, c))\n            elif grid[r][c] == 1: fresh += 1\n    minutes = 0\n    dirs = [(1,0),(-1,0),(0,1),(0,-1)]\n    while q and fresh:\n        for _ in range(len(q)):\n            r, c = q.popleft()\n            for dr, dc in dirs:\n                nr, nc = r+dr, c+dc\n                if 0 <= nr < R and 0 <= nc < C and grid[nr][nc] == 1:\n                    grid[nr][nc] = 2\n                    fresh -= 1\n                    q.append((nr, nc))\n        minutes += 1\n    return minutes if fresh == 0 else -1', time: 'O(m*n)', timeWhy: 'each cell enters the queue at most once.', space: 'O(m*n)', spaceWhy: 'the BFS queue.', pitfalls: ['A grid with zero fresh oranges answers 0, not -1 — check before subtracting.'] }),
  gen: function () { var o = [[[[2, 1, 1], [1, 1, 0], [0, 1, 1]]], [[[2, 1, 1], [0, 1, 1], [1, 0, 1]]], [[[0]]], [[[2, 2], [1, 1]]]]; for (var k = 0; k < 35; k++) o.push([intGrid(randInt(1, 4), randInt(1, 4), 0, 2)]); return o; },
  ref: function (a) { var g = a[0].map(function (r) { return r.slice(); }); var R = g.length, C = g[0].length, q = [], fresh = 0; for (var r = 0; r < R; r++) for (var c = 0; c < C; c++) { if (g[r][c] === 2) q.push([r, c]); else if (g[r][c] === 1) fresh++; } var minutes = 0, dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; while (q.length && fresh) { var nq = []; for (var i = 0; i < q.length; i++) { var cur = q[i]; for (var d = 0; d < 4; d++) { var nr = cur[0] + dirs[d][0], nc = cur[1] + dirs[d][1]; if (nr >= 0 && nr < R && nc >= 0 && nc < C && g[nr][nc] === 1) { g[nr][nc] = 2; fresh--; nq.push([nr, nc]); } } } q = nq; minutes++; } return fresh === 0 ? minutes : -1; } });

// ---- Spiral Matrix (GRID_ARR) ----
MORE6.push({ slug: 'spiral-matrix', title: 'Spiral Matrix', difficulty: 'medium', topics: ['Array', 'Matrix', 'Simulation'], type: 'GRID_ARR', langsrc: T.GRID_ARR('spiralOrder'),
  desc: '<p>Given an <code>m x n</code> matrix, return all elements in spiral order (clockwise starting from the top-left).</p>',
  examples: [{ in: 'matrix = [[1,2,3],[4,5,6],[7,8,9]]', out: '[1,2,3,6,9,8,7,4,5]' }, { in: 'matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]', out: '[1,2,3,4,8,12,11,10,9,5,6,7]' }],
  constraints: ['1 &lt;= m, n &lt;= 10', '-100 &lt;= matrix[i][j] &lt;= 100'],
  editorial: ED({ intuition: 'Peel the matrix like an onion: walk the top row, right column, bottom row, left column, then shrink the boundaries inward and repeat.', approach: ['Track four boundaries: top, bottom, left, right.', 'Traverse top row left-to-right, right column top-to-bottom, bottom row right-to-left, left column bottom-to-top.', 'After each edge, move the corresponding boundary inward; stop when boundaries cross.'], code: 'def spiralOrder(self, matrix):\n    res = []\n    top, bottom = 0, len(matrix) - 1\n    left, right = 0, len(matrix[0]) - 1\n    while top <= bottom and left <= right:\n        for c in range(left, right + 1): res.append(matrix[top][c])\n        top += 1\n        for r in range(top, bottom + 1): res.append(matrix[r][right])\n        right -= 1\n        if top <= bottom:\n            for c in range(right, left - 1, -1): res.append(matrix[bottom][c])\n            bottom -= 1\n        if left <= right:\n            for r in range(bottom, top - 1, -1): res.append(matrix[r][left])\n            left += 1\n    return res', time: 'O(m*n)', timeWhy: 'each element is appended exactly once.', space: 'O(1)', spaceWhy: 'aside from the output, only boundary counters.', pitfalls: ['Re-check top <= bottom and left <= right before the bottom row and left column to avoid double-visiting on non-square matrices.'] }),
  gen: function () { var o = [[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]], [[[7]]], [[[1, 2], [3, 4]]]]; var v = 1; for (var k = 0; k < 35; k++) { var R = randInt(1, 5), C = randInt(1, 5), g = [], val = 1; for (var i = 0; i < R; i++) { var row = []; for (var j = 0; j < C; j++) row.push(val++); g.push(row); } o.push([g]); } return o; },
  ref: function (a) { var m = a[0], res = [], top = 0, bottom = m.length - 1, left = 0, right = m[0].length - 1; while (top <= bottom && left <= right) { for (var c = left; c <= right; c++) res.push(m[top][c]); top++; for (var r = top; r <= bottom; r++) res.push(m[r][right]); right--; if (top <= bottom) { for (c = right; c >= left; c--) res.push(m[bottom][c]); bottom--; } if (left <= right) { for (r = bottom; r >= top; r--) res.push(m[r][left]); left++; } } return res; } });

// ---- Longest Increasing Path in a Matrix (GRID_INT) ----
MORE6.push({ slug: 'longest-increasing-path-in-a-matrix', title: 'Longest Increasing Path in a Matrix', difficulty: 'hard', topics: ['Graph', 'DFS', 'Dynamic Programming', 'Matrix', 'Memoization'], type: 'GRID_INT', langsrc: T.GRID_INT('longestIncreasingPath'),
  desc: '<p>Given an <code>m x n</code> integer matrix, return the length of the longest strictly increasing path. From a cell you may move up, down, left, or right (no diagonals or wrap-around).</p>',
  examples: [{ in: 'matrix = [[9,9,4],[6,6,8],[2,1,1]]', out: '4', ex: 'The path [1,2,6,9].' }, { in: 'matrix = [[3,4,5],[3,2,6],[2,2,1]]', out: '4' }],
  constraints: ['1 &lt;= m, n &lt;= 200', '0 &lt;= matrix[i][j] &lt;= 2^31 - 1'],
  editorial: ED({ intuition: 'Because you can only step to strictly larger values, the graph of moves is a DAG — no cycles. So the longest path from each cell is well-defined and can be memoized.', approach: ['Define <code>dfs(r,c)</code> = longest increasing path starting at that cell.', 'It is 1 plus the max <code>dfs</code> over neighbours with a strictly greater value.', 'Cache each result; the answer is the max over all starting cells.'], code: 'def longestIncreasingPath(self, matrix):\n    R, C = len(matrix), len(matrix[0])\n    memo = [[0]*C for _ in range(R)]\n    def dfs(r, c):\n        if memo[r][c]: return memo[r][c]\n        best = 1\n        for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr, nc = r+dr, c+dc\n            if 0 <= nr < R and 0 <= nc < C and matrix[nr][nc] > matrix[r][c]:\n                best = max(best, 1 + dfs(nr, nc))\n        memo[r][c] = best\n        return best\n    return max(dfs(r, c) for r in range(R) for c in range(C))', time: 'O(m*n)', timeWhy: 'each cell is computed once thanks to memoization.', space: 'O(m*n)', spaceWhy: 'the memo table plus recursion stack.', pitfalls: ['Without memoization this is exponential — the cache is what makes it linear in cells.'] }),
  gen: function () { var o = [[[[9, 9, 4], [6, 6, 8], [2, 1, 1]]], [[[3, 4, 5], [3, 2, 6], [2, 2, 1]]], [[[1]]]]; for (var k = 0; k < 35; k++) o.push([intGrid(randInt(1, 4), randInt(1, 4), 0, 9)]); return o; },
  ref: function (a) { var m = a[0], R = m.length, C = m[0].length, memo = []; for (var i = 0; i < R; i++) memo.push(new Array(C).fill(0)); var dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; function dfs(r, c) { if (memo[r][c]) return memo[r][c]; var best = 1; for (var d = 0; d < 4; d++) { var nr = r + dirs[d][0], nc = c + dirs[d][1]; if (nr >= 0 && nr < R && nc >= 0 && nc < C && m[nr][nc] > m[r][c]) best = Math.max(best, 1 + dfs(nr, nc)); } memo[r][c] = best; return best; } var ans = 0; for (r = 0; r < R; r++) for (c = 0; c < C; c++) ans = Math.max(ans, dfs(r, c)); return ans; } });

// ---- Swim in Rising Water (GRID_INT) ----
MORE6.push({ slug: 'swim-in-rising-water', title: 'Swim in Rising Water', difficulty: 'hard', topics: ['Graph', 'Binary Search', 'Heap', 'Matrix'], type: 'GRID_INT', langsrc: T.GRID_INT('swimInWater'),
  desc: '<p>You are given an <code>n x n</code> grid where <code>grid[i][j]</code> is the elevation at that cell. At time <code>t</code> the water level is <code>t</code>, and you can move between two adjacent cells if both elevations are at most <code>t</code>. Starting at the top-left, return the least time to reach the bottom-right.</p>',
  examples: [{ in: 'grid = [[0,2],[1,3]]', out: '3' }, { in: 'grid = [[0,1,2,3,4],[24,23,22,21,5],[12,13,14,15,16],[11,17,18,19,20],[10,9,8,7,6]]', out: '16' }],
  constraints: ['1 &lt;= n &lt;= 50', 'grid holds a permutation of 0 .. n^2 - 1'],
  editorial: ED({ intuition: 'The cost of a path is the maximum elevation on it, and you want the path that minimizes that maximum. This is a shortest-path where "distance" is a max, so a Dijkstra-style min-heap keyed by the running max works.', approach: ['Use a min-heap of <code>(elevation-so-far, r, c)</code> starting at the top-left.', 'Always pop the cell reachable with the smallest peak elevation.', 'When you pop the bottom-right, that peak is the answer. Alternatively binary search t + BFS.'], code: 'import heapq\n\ndef swimInWater(self, grid):\n    n = len(grid)\n    seen = {(0, 0)}\n    heap = [(grid[0][0], 0, 0)]\n    while heap:\n        t, r, c = heapq.heappop(heap)\n        if r == n-1 and c == n-1:\n            return t\n        for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr, nc = r+dr, c+dc\n            if 0 <= nr < n and 0 <= nc < n and (nr, nc) not in seen:\n                seen.add((nr, nc))\n                heapq.heappush(heap, (max(t, grid[nr][nc]), nr, nc))', time: 'O(n^2 log n)', timeWhy: 'each cell is pushed once; heap ops are log of the number of cells.', space: 'O(n^2)', spaceWhy: 'the visited set and heap.', pitfalls: ['The path cost is the max cell on the path, not the sum — carry <code>max(t, elevation)</code> in the heap.'] }),
  gen: function () { var o = [[[[0, 2], [1, 3]]], [[[0, 1, 2, 3, 4], [24, 23, 22, 21, 5], [12, 13, 14, 15, 16], [11, 17, 18, 19, 20], [10, 9, 8, 7, 6]]], [[[0]]]]; for (var k = 0; k < 35; k++) { var n = randInt(1, 4), perm = []; for (var i = 0; i < n * n; i++) perm.push(i); for (var s = perm.length - 1; s > 0; s--) { var j = randInt(0, s); var tmp = perm[s]; perm[s] = perm[j]; perm[j] = tmp; } var g = []; for (i = 0; i < n; i++) g.push(perm.slice(i * n, i * n + n)); o.push([g]); } return o; },
  ref: function (a) { var g = a[0], n = g.length, seen = []; for (var i = 0; i < n; i++) seen.push(new Array(n).fill(false)); var heap = [[g[0][0], 0, 0]]; seen[0][0] = true; var dirs = [[1, 0], [-1, 0], [0, 1], [0, -1]]; while (heap.length) { heap.sort(function (x, y) { return x[0] - y[0]; }); var top = heap.shift(); var t = top[0], r = top[1], c = top[2]; if (r === n - 1 && c === n - 1) return t; for (var d = 0; d < 4; d++) { var nr = r + dirs[d][0], nc = c + dirs[d][1]; if (nr >= 0 && nr < n && nc >= 0 && nc < n && !seen[nr][nc]) { seen[nr][nc] = true; heap.push([Math.max(t, g[nr][nc]), nr, nc]); } } } return g[0][0]; } });

// ---- Search a 2D Matrix (GRID_TGT_BOOL) ----
MORE6.push({ slug: 'search-a-2d-matrix', title: 'Search a 2D Matrix', difficulty: 'medium', topics: ['Array', 'Binary Search', 'Matrix'], type: 'GRID_TGT_BOOL', langsrc: T.GRID_TGT_BOOL('searchMatrix'),
  desc: '<p>You are given an <code>m x n</code> matrix where each row is sorted ascending and the first integer of each row is greater than the last integer of the previous row. Return <code>true</code> if <code>target</code> is present.</p>',
  examples: [{ in: 'matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3', out: 'true' }, { in: 'matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13', out: 'false' }],
  constraints: ['1 &lt;= m, n &lt;= 100', '-10^4 &lt;= matrix[i][j], target &lt;= 10^4'],
  editorial: ED({ intuition: 'The two sorting guarantees mean the whole matrix is one sorted sequence read row by row. So you can binary search it as if it were a flat array of length m*n, mapping an index back to (row, col).', approach: ['Binary search over indices 0 .. m*n - 1.', 'Map mid to <code>matrix[mid // n][mid % n]</code>.', 'Compare and move lo/hi as in ordinary binary search.'], code: 'def searchMatrix(self, matrix, target):\n    m, n = len(matrix), len(matrix[0])\n    lo, hi = 0, m * n - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        val = matrix[mid // n][mid % n]\n        if val == target:\n            return True\n        if val < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return False', time: 'O(log(m*n))', timeWhy: 'a single binary search over all cells.', space: 'O(1)', spaceWhy: 'constant extra space.', pitfalls: ['Use the column count n (not m) to decode mid into row and column.'] }),
  gen: function () {
    var o = [[[[1, 3, 5, 7], [10, 11, 16, 20], [23, 30, 34, 60]], 3], [[[1, 3, 5, 7], [10, 11, 16, 20], [23, 30, 34, 60]], 13], [[[1]], 1], [[[1]], 2]];
    for (var k = 0; k < 36; k++) {
      var R = randInt(1, 4), C = randInt(1, 4), cur = randInt(-10, 5), flat = [];
      for (var i = 0; i < R * C; i++) { flat.push(cur); cur += randInt(1, 4); }
      var g = []; for (i = 0; i < R; i++) g.push(flat.slice(i * C, i * C + C));
      var t = (Math.random() < 0.6) ? flat[randInt(0, flat.length - 1)] : randInt(-12, cur + 2);
      o.push([g, t]);
    }
    return o;
  },
  ref: function (a) { var m = a[0], t = a[1], R = m.length, C = m[0].length, lo = 0, hi = R * C - 1; while (lo <= hi) { var mid = (lo + hi) >> 1, val = m[Math.floor(mid / C)][mid % C]; if (val === t) return true; if (val < t) lo = mid + 1; else hi = mid - 1; } return false; } });

module.exports = { MORE6 };
