// Batch G: backtracking / combinatorial (canonical list outputs).
const { T, randInt, randArr } = require('./gen.js');

function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function ED(o) {
  var h = '';
  if (o.intuition) h += '<h3>Intuition</h3>' + (Array.isArray(o.intuition) ? o.intuition.map(function (p) { return '<p>' + p + '</p>'; }).join('') : '<p>' + o.intuition + '</p>');
  if (o.approach) h += '<h3>Approach</h3><ol>' + o.approach.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ol>';
  if (o.code) h += '<h3>Solution</h3><pre><code>' + esc(o.code) + '</code></pre>';
  h += '<h3>Complexity</h3><ul><li><b>Time — ' + o.time + ':</b> ' + o.timeWhy + '</li><li><b>Space — ' + o.space + ':</b> ' + o.spaceWhy + '</li></ul>';
  if (o.pitfalls) h += '<h3>Common Pitfalls</h3><ul>' + o.pitfalls.map(function (s) { return '<li>' + s + '</li>'; }).join('') + '</ul>';
  return h;
}
function cmpArr(a, b) { for (var i = 0; i < Math.min(a.length, b.length); i++) { if (a[i] < b[i]) return -1; if (a[i] > b[i]) return 1; } return a.length - b.length; }
function canonI(res, sw) { var r = res.map(function (x) { return sw ? x.slice().sort(function (p, q) { return p - q; }) : x.slice(); }); r.sort(cmpArr); return r.map(function (x) { return x.join(' '); }).join('|'); }
function canonS(res, sw) { var r = res.map(function (x) { return sw ? x.slice().sort() : x.slice(); }); r.sort(cmpArr); return r.map(function (x) { return x.join(' '); }).join('|'); }
function rw(minL, maxL, al) { var L = randInt(minL, maxL), s = ''; for (var i = 0; i < L; i++) s += al[randInt(0, al.length - 1)]; return s; }

const MORE11 = [];

// ---- Subsets (ARR_LISTS) ----
MORE11.push({ slug: 'subsets', title: 'Subsets', difficulty: 'medium', topics: ['Array', 'Backtracking', 'Bit Manipulation'], type: 'ARR_LISTS', langsrc: T.ARR_LISTS('subsets'),
  desc: '<p>Given an array <code>nums</code> of unique integers, return all possible subsets (the power set). The result may be in any order; this judge compares them order-independently.</p>',
  examples: [{ in: 'nums = [1,2,3]', out: '[[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]' }, { in: 'nums = [0]', out: '[[],[0]]' }],
  constraints: ['1 &lt;= nums.length &lt;= 10', 'All numbers are unique.'],
  editorial: ED({ intuition: 'Each element is either in a subset or not — that binary choice over n elements generates all 2^n subsets. Backtracking explores the include/exclude tree.', approach: ['DFS carrying the current index and partial subset.', 'At each index, record the current subset, then try adding each later element.', 'Alternatively enumerate bitmasks 0..2^n-1.'], code: 'def subsets(self, nums):\n    res = []\n    def dfs(start, path):\n        res.append(path[:])\n        for i in range(start, len(nums)):\n            path.append(nums[i])\n            dfs(i + 1, path)\n            path.pop()\n    dfs(0, [])\n    return res', time: 'O(n * 2^n)', timeWhy: 'there are 2^n subsets, each copied in O(n).', space: 'O(n)', spaceWhy: 'recursion depth (excluding output).' }),
  gen: function () { var o = [[[1, 2, 3]], [[0]], [[]]]; for (var k = 0; k < 30; k++) { var n = randInt(0, 5), used = {}, arr = []; while (arr.length < n) { var v = randInt(-9, 9); if (!used[v]) { used[v] = 1; arr.push(v); } } o.push([arr]); } return o; },
  ref: function (a) { var nums = a[0], n = nums.length, res = []; for (var m = 0; m < (1 << n); m++) { var sub = []; for (var j = 0; j < n; j++) if (m & (1 << j)) sub.push(nums[j]); res.push(sub); } return canonI(res, true); } });

// ---- Subsets II (ARR_LISTS) ----
MORE11.push({ slug: 'subsets-ii', title: 'Subsets II', difficulty: 'medium', topics: ['Array', 'Backtracking', 'Bit Manipulation'], type: 'ARR_LISTS', langsrc: T.ARR_LISTS('subsetsWithDup'),
  desc: '<p>Given an integer array <code>nums</code> that may contain duplicates, return all possible <strong>unique</strong> subsets. The result may be in any order.</p>',
  examples: [{ in: 'nums = [1,2,2]', out: '[[],[1],[2],[1,2],[2,2],[1,2,2]]' }, { in: 'nums = [0]', out: '[[],[0]]' }],
  constraints: ['1 &lt;= nums.length &lt;= 10', '-10 &lt;= nums[i] &lt;= 10'],
  editorial: ED({ intuition: 'Duplicates cause repeated subsets. Sort first so equal values are adjacent, then at each recursion level skip a value identical to the previous choice at that same level.', approach: ['Sort nums.', 'DFS recording each partial subset; iterate candidates from start.', 'Skip <code>nums[i] == nums[i-1]</code> when <code>i &gt; start</code> to avoid duplicate subsets.'], code: 'def subsetsWithDup(self, nums):\n    nums.sort()\n    res = []\n    def dfs(start, path):\n        res.append(path[:])\n        for i in range(start, len(nums)):\n            if i > start and nums[i] == nums[i-1]:\n                continue\n            path.append(nums[i])\n            dfs(i + 1, path)\n            path.pop()\n    dfs(0, [])\n    return res', time: 'O(n * 2^n)', timeWhy: 'up to 2^n subsets copied in O(n).', space: 'O(n)', spaceWhy: 'recursion depth.', pitfalls: ['Skip only when i &gt; start; skipping at i == start would drop valid subsets.'] }),
  gen: function () { var o = [[[1, 2, 2]], [[0]], [[2, 2, 2]]]; for (var k = 0; k < 30; k++) o.push([randArr(randInt(1, 5), 1, 3)]); return o; },
  ref: function (a) { var nums = a[0], n = nums.length, seen = {}, res = []; for (var m = 0; m < (1 << n); m++) { var sub = []; for (var j = 0; j < n; j++) if (m & (1 << j)) sub.push(nums[j]); sub.sort(function (x, y) { return x - y; }); var key = sub.join(','); if (!seen[key]) { seen[key] = 1; res.push(sub); } } return canonI(res, true); } });

// ---- Permutations (ARR_LISTS_PERM) ----
MORE11.push({ slug: 'permutations', title: 'Permutations', difficulty: 'medium', topics: ['Array', 'Backtracking'], type: 'ARR_LISTS_PERM', langsrc: T.ARR_LISTS_PERM('permute'),
  desc: '<p>Given an array <code>nums</code> of distinct integers, return all possible permutations in any order.</p>',
  examples: [{ in: 'nums = [1,2,3]', out: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]' }, { in: 'nums = [1]', out: '[[1]]' }],
  constraints: ['1 &lt;= nums.length &lt;= 6', 'All integers are unique.'],
  editorial: ED({ intuition: 'Build a permutation position by position, choosing each unused element in turn. Backtracking with a used-marker explores all n! orderings.', approach: ['Track which elements are used.', 'At each step append an unused element and recurse.', 'When the path length equals n, record it, then backtrack.'], code: 'def permute(self, nums):\n    res = []\n    def dfs(path, used):\n        if len(path) == len(nums):\n            res.append(path[:]); return\n        for i in range(len(nums)):\n            if used[i]: continue\n            used[i] = True; path.append(nums[i])\n            dfs(path, used)\n            path.pop(); used[i] = False\n    dfs([], [False]*len(nums))\n    return res', time: 'O(n * n!)', timeWhy: 'n! permutations, each built in O(n).', space: 'O(n)', spaceWhy: 'recursion depth and used array.' }),
  gen: function () { var o = [[[1, 2, 3]], [[1]], [[1, 2]]]; for (var k = 0; k < 26; k++) { var n = randInt(1, 4), used = {}, arr = []; while (arr.length < n) { var v = randInt(-9, 9); if (!used[v]) { used[v] = 1; arr.push(v); } } o.push([arr]); } return o; },
  ref: function (a) { var res = []; (function perm(cur, rem) { if (!rem.length) { res.push(cur.slice()); return; } for (var i = 0; i < rem.length; i++) perm(cur.concat([rem[i]]), rem.slice(0, i).concat(rem.slice(i + 1))); })([], a[0]); return canonI(res, false); } });

// ---- Combination Sum (ARR_INT_LISTS) ----
MORE11.push({ slug: 'combination-sum', title: 'Combination Sum', difficulty: 'medium', topics: ['Array', 'Backtracking'], type: 'ARR_INT_LISTS', langsrc: T.ARR_INT_LISTS('combinationSum'),
  desc: '<p>Given distinct positive integers <code>candidates</code> and a <code>target</code>, return all unique combinations that sum to target. A candidate may be reused unlimited times.</p>',
  examples: [{ in: 'candidates = [2,3,6,7], target = 7', out: '[[2,2,3],[7]]' }, { in: 'candidates = [2,3,5], target = 8', out: '[[2,2,2,2],[2,3,3],[3,5]]' }],
  constraints: ['1 &lt;= candidates.length &lt;= 30', 'All candidates are distinct positive integers.', '1 &lt;= target &lt;= 40'],
  editorial: ED({ intuition: 'Explore combinations by choosing candidates in non-decreasing index order (so each combination is generated once), subtracting from the remaining target and allowing reuse of the current index.', approach: ['DFS with (start index, remaining).', 'When remaining hits 0, record the path; if it goes negative, prune.', 'Recurse with the same index i (reuse) to allow repeats.'], code: 'def combinationSum(self, candidates, target):\n    res = []\n    candidates.sort()\n    def dfs(start, rem, path):\n        if rem == 0:\n            res.append(path[:]); return\n        for i in range(start, len(candidates)):\n            if candidates[i] > rem: break\n            path.append(candidates[i])\n            dfs(i, rem - candidates[i], path)\n            path.pop()\n    dfs(0, target, [])\n    return res', time: 'O(2^t)', timeWhy: 'exponential in target/candidate ratio; pruned by the break.', space: 'O(target)', spaceWhy: 'recursion depth.', pitfalls: ['Recurse with i (not i+1) to permit reuse; pass i+1 and you forbid repeats.'] }),
  gen: function () { var o = [[[2, 3, 6, 7], 7], [[2, 3, 5], 8], [[2], 1]]; for (var k = 0; k < 30; k++) { var m = randInt(1, 4), used = {}, c = []; while (c.length < m) { var v = randInt(2, 7); if (!used[v]) { used[v] = 1; c.push(v); } } o.push([c, randInt(1, 12)]); } return o; },
  ref: function (a) { var c = a[0].slice().sort(function (x, y) { return x - y; }), res = []; (function bt(start, rem, cur) { if (rem === 0) { res.push(cur.slice()); return; } if (rem < 0) return; for (var i = start; i < c.length; i++) { if (c[i] > rem) break; cur.push(c[i]); bt(i, rem - c[i], cur); cur.pop(); } })(0, a[1], []); return canonI(res, true); } });

// ---- Combination Sum II (ARR_INT_LISTS) ----
MORE11.push({ slug: 'combination-sum-ii', title: 'Combination Sum II', difficulty: 'medium', topics: ['Array', 'Backtracking'], type: 'ARR_INT_LISTS', langsrc: T.ARR_INT_LISTS('combinationSum2'),
  desc: '<p>Given <code>candidates</code> (which may contain duplicates) and a <code>target</code>, return all unique combinations summing to target. Each candidate may be used at most once.</p>',
  examples: [{ in: 'candidates = [10,1,2,7,6,1,5], target = 8', out: '[[1,1,6],[1,2,5],[1,7],[2,6]]' }, { in: 'candidates = [2,5,2,1,2], target = 5', out: '[[1,2,2],[5]]' }],
  constraints: ['1 &lt;= candidates.length &lt;= 100', '1 &lt;= candidates[i] &lt;= 50', '1 &lt;= target &lt;= 30'],
  editorial: ED({ intuition: 'Like Combination Sum, but each item is used once and duplicates must not produce duplicate combinations. Sort, advance the index each pick, and skip equal values at the same depth.', approach: ['Sort candidates.', 'DFS advancing to i+1 (each used once).', 'Skip <code>candidates[i] == candidates[i-1]</code> when i &gt; start to dedupe.'], code: 'def combinationSum2(self, candidates, target):\n    candidates.sort()\n    res = []\n    def dfs(start, rem, path):\n        if rem == 0:\n            res.append(path[:]); return\n        for i in range(start, len(candidates)):\n            if i > start and candidates[i] == candidates[i-1]:\n                continue\n            if candidates[i] > rem:\n                break\n            path.append(candidates[i])\n            dfs(i + 1, rem - candidates[i], path)\n            path.pop()\n    dfs(0, target, [])\n    return res', time: 'O(2^n)', timeWhy: 'subset exploration with pruning.', space: 'O(n)', spaceWhy: 'recursion depth.', pitfalls: ['Advance to i+1 (single use) and skip duplicates only at i &gt; start.'] }),
  gen: function () { var o = [[[10, 1, 2, 7, 6, 1, 5], 8], [[2, 5, 2, 1, 2], 5], [[1], 1]]; for (var k = 0; k < 30; k++) o.push([randArr(randInt(1, 6), 1, 5), randInt(1, 12)]); return o; },
  ref: function (a) { var c = a[0].slice().sort(function (x, y) { return x - y; }), res = []; (function bt(start, rem, cur) { if (rem === 0) { res.push(cur.slice()); return; } if (rem < 0) return; for (var i = start; i < c.length; i++) { if (i > start && c[i] === c[i - 1]) continue; if (c[i] > rem) break; cur.push(c[i]); bt(i + 1, rem - c[i], cur); cur.pop(); } })(0, a[1], []); return canonI(res, true); } });

// ---- Palindrome Partitioning (STR_LISTSTR) ----
MORE11.push({ slug: 'palindrome-partitioning', title: 'Palindrome Partitioning', difficulty: 'medium', topics: ['String', 'Backtracking', 'Dynamic Programming'], type: 'STR_LISTSTR', langsrc: T.STR_LISTSTR('partition'),
  desc: '<p>Given a string <code>s</code>, partition it so that every substring of the partition is a palindrome. Return all possible palindrome partitionings, in any order.</p>',
  examples: [{ in: 's = "aab"', out: '[["a","a","b"],["aa","b"]]' }, { in: 's = "a"', out: '[["a"]]' }],
  constraints: ['1 &lt;= s.length &lt;= 16', 's contains only lowercase English letters.'],
  editorial: ED({ intuition: 'Try every prefix of the remaining string; whenever the prefix is a palindrome, fix it as the next piece and recurse on the rest. Each full split into palindromes is one answer.', approach: ['DFS from a start index.', 'For each end &gt;= start, if s[start..end] is a palindrome, add it and recurse from end+1.', 'When start reaches the end of the string, record the current partition.'], code: 'def partition(self, s):\n    res = []\n    def isPal(l, r):\n        while l < r:\n            if s[l] != s[r]: return False\n            l += 1; r -= 1\n        return True\n    def dfs(start, path):\n        if start == len(s):\n            res.append(path[:]); return\n        for end in range(start, len(s)):\n            if isPal(start, end):\n                path.append(s[start:end+1])\n                dfs(end + 1, path)\n                path.pop()\n    dfs(0, [])\n    return res', time: 'O(n * 2^n)', timeWhy: 'up to 2^n partitions, each checked/copied in O(n).', space: 'O(n)', spaceWhy: 'recursion depth.' }),
  gen: function () { var o = [['aab'], ['a'], ['aaa'], ['abba']]; for (var k = 0; k < 30; k++) o.push([rw(1, 6, 'ab')]); return o; },
  ref: function (a) { var s = a[0], res = []; function isPal(l, r) { while (l < r) { if (s[l] !== s[r]) return false; l++; r--; } return true; } (function dfs(start, path) { if (start === s.length) { res.push(path.slice()); return; } for (var end = start; end < s.length; end++) if (isPal(start, end)) { path.push(s.slice(start, end + 1)); dfs(end + 1, path); path.pop(); } })(0, []); return canonS(res, false); } });

// ---- Generate Parentheses (INT_ARRSTR) ----
MORE11.push({ slug: 'generate-parentheses', title: 'Generate Parentheses', difficulty: 'medium', topics: ['String', 'Backtracking', 'Dynamic Programming'], type: 'INT_ARRSTR', langsrc: T.INT_ARRSTR('generateParenthesis'),
  desc: '<p>Given <code>n</code> pairs of parentheses, return all combinations of well-formed parentheses, in any order.</p>',
  examples: [{ in: 'n = 3', out: '["((()))","(()())","(())()","()(())","()()()"]' }, { in: 'n = 1', out: '["()"]' }],
  constraints: ['1 &lt;= n &lt;= 8'],
  editorial: ED({ intuition: 'Build the string one character at a time. You may add "(" while you still have opens left, and ")" only while it would not exceed the number of opens placed — this guarantees validity by construction.', approach: ['DFS carrying counts of open and close brackets used.', 'Add "(" if open &lt; n; add ")" if close &lt; open.', 'When the string reaches length 2n it is a valid answer.'], code: 'def generateParenthesis(self, n):\n    res = []\n    def dfs(cur, open, close):\n        if len(cur) == 2 * n:\n            res.append(cur); return\n        if open < n:\n            dfs(cur + "(", open + 1, close)\n        if close < open:\n            dfs(cur + ")", open, close + 1)\n    dfs("", 0, 0)\n    return res', time: 'O(4^n / sqrt(n))', timeWhy: 'the count of valid strings is the nth Catalan number.', space: 'O(n)', spaceWhy: 'recursion depth.', pitfalls: ['Only close when close &lt; open, or you produce invalid strings like ")(".'] }),
  gen: function () { var o = []; for (var n = 1; n <= 7; n++) o.push([n]); for (var k = 0; k < 20; k++) o.push([randInt(1, 6)]); return o; },
  ref: function (a) { var n = a[0], res = []; (function dfs(cur, open, close) { if (cur.length === 2 * n) { res.push(cur); return; } if (open < n) dfs(cur + '(', open + 1, close); if (close < open) dfs(cur + ')', open, close + 1); })('', 0, 0); return res.slice().sort().join(' '); } });

// ---- Letter Combinations of a Phone Number (STR_ARRSTR) ----
MORE11.push({ slug: 'letter-combinations-of-a-phone-number', title: 'Letter Combinations of a Phone Number', difficulty: 'medium', topics: ['String', 'Backtracking', 'Hash Table'], type: 'STR_ARRSTR', langsrc: T.STR_ARRSTR('letterCombinations'),
  desc: '<p>Given a string of <code>digits</code> from 2-9, return all letter combinations the number could spell (phone keypad mapping). Return an empty result for an empty input. Order does not matter.</p>',
  examples: [{ in: 'digits = "23"', out: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' }, { in: 'digits = ""', out: '[]' }],
  constraints: ['0 &lt;= digits.length &lt;= 4', 'digits[i] is in the range 2-9.'],
  editorial: ED({ intuition: 'Each digit maps to a set of letters; the answer is the Cartesian product across digits. Grow the set of prefixes one digit at a time.', approach: ['Map digits to their letters.', 'Start with an empty prefix; for each digit, extend every current prefix by each mapped letter.', 'Return the accumulated combinations (empty input gives an empty list).'], code: 'def letterCombinations(self, digits):\n    if not digits:\n        return []\n    m = {"2":"abc","3":"def","4":"ghi","5":"jkl","6":"mno","7":"pqrs","8":"tuv","9":"wxyz"}\n    res = [""]\n    for d in digits:\n        res = [p + c for p in res for c in m[d]]\n    return res', time: 'O(4^n)', timeWhy: 'up to 4 letters per digit across n digits.', space: 'O(4^n)', spaceWhy: 'the output list.', pitfalls: ['Return [] (not [""]) for an empty input.'] }),
  gen: function () { var o = [['23'], [''], ['2'], ['79']]; for (var k = 0; k < 30; k++) o.push([rw(0, 3, '23456789')]); return o; },
  ref: function (a) { var digits = a[0]; if (!digits.length) return ''; var m = { '2': 'abc', '3': 'def', '4': 'ghi', '5': 'jkl', '6': 'mno', '7': 'pqrs', '8': 'tuv', '9': 'wxyz' }; var res = ['']; for (var i = 0; i < digits.length; i++) { var next = []; for (var p = 0; p < res.length; p++) for (var c = 0; c < m[digits[i]].length; c++) next.push(res[p] + m[digits[i]][c]); res = next; } return res.slice().sort().join(' '); } });

// ---- 3Sum (ARR_LISTS) ----
MORE11.push({ slug: '3sum', title: '3Sum', difficulty: 'medium', topics: ['Array', 'Two Pointers', 'Sorting'], type: 'ARR_LISTS', langsrc: T.ARR_LISTS('threeSum'),
  desc: '<p>Given an integer array <code>nums</code>, return all unique triplets <code>[a, b, c]</code> that sum to 0. The result may be in any order and must not contain duplicate triplets.</p>',
  examples: [{ in: 'nums = [-1,0,1,2,-1,-4]', out: '[[-1,-1,2],[-1,0,1]]' }, { in: 'nums = [0,0,0]', out: '[[0,0,0]]' }],
  constraints: ['3 &lt;= nums.length &lt;= 3000', '-10^5 &lt;= nums[i] &lt;= 10^5'],
  editorial: ED({ intuition: 'Sort the array; then for each fixed first element, the remaining two-sum-to-target reduces to a two-pointer scan. Sorting also makes it easy to skip duplicates.', approach: ['Sort nums.', 'For each index i (skipping duplicate values), two-pointer over the rest looking for sum 0.', 'On a hit, record the triplet and advance both pointers past duplicates.'], code: 'def threeSum(self, nums):\n    nums.sort()\n    res = []\n    for i in range(len(nums)):\n        if i > 0 and nums[i] == nums[i-1]:\n            continue\n        l, r = i + 1, len(nums) - 1\n        while l < r:\n            s = nums[i] + nums[l] + nums[r]\n            if s == 0:\n                res.append([nums[i], nums[l], nums[r]])\n                l += 1; r -= 1\n                while l < r and nums[l] == nums[l-1]: l += 1\n                while l < r and nums[r] == nums[r+1]: r -= 1\n            elif s < 0:\n                l += 1\n            else:\n                r -= 1\n    return res', time: 'O(n^2)', timeWhy: 'an O(n) two-pointer scan for each of n first elements.', space: 'O(1)', spaceWhy: 'ignoring the output and sort.', pitfalls: ['Skip duplicate values at i and after each match to avoid duplicate triplets.'] }),
  gen: function () { var o = [[[-1, 0, 1, 2, -1, -4]], [[0, 0, 0]], [[1, 2, -3]], [[0, 0, 0, 0]]]; for (var k = 0; k < 30; k++) o.push([randArr(randInt(3, 8), -4, 4)]); return o; },
  ref: function (a) { var nums = a[0].slice().sort(function (x, y) { return x - y; }), n = nums.length, res = []; for (var i = 0; i < n; i++) { if (i > 0 && nums[i] === nums[i - 1]) continue; var l = i + 1, r = n - 1; while (l < r) { var s = nums[i] + nums[l] + nums[r]; if (s === 0) { res.push([nums[i], nums[l], nums[r]]); l++; r--; while (l < r && nums[l] === nums[l - 1]) l++; while (l < r && nums[r] === nums[r + 1]) r--; } else if (s < 0) l++; else r--; } } return canonI(res, true); } });

// ---- Group Anagrams (ARRSTR_LISTSTR) ----
MORE11.push({ slug: 'group-anagrams', title: 'Group Anagrams', difficulty: 'medium', topics: ['Array', 'String', 'Hash Table', 'Sorting'], type: 'ARRSTR_LISTSTR', langsrc: T.ARRSTR_LISTSTR('groupAnagrams'),
  desc: '<p>Given an array of strings <code>strs</code>, group the anagrams together. Return the groups in any order.</p>',
  examples: [{ in: 'strs = ["eat","tea","tan","ate","nat","bat"]', out: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }, { in: 'strs = [""]', out: '[[""]]' }],
  constraints: ['1 &lt;= strs.length &lt;= 10^4', '0 &lt;= strs[i].length &lt;= 100', 'strs[i] consists of lowercase English letters.'],
  editorial: ED({ intuition: 'Two words are anagrams exactly when their sorted letters match. Use that sorted form as a hash-map key and bucket words together.', approach: ['For each word, compute a canonical key (sorted characters or a 26-length count).', 'Append the word to the list under that key.', 'Return the map values.'], code: 'def groupAnagrams(self, strs):\n    groups = {}\n    for w in strs:\n        key = "".join(sorted(w))\n        groups.setdefault(key, []).append(w)\n    return list(groups.values())', time: 'O(n * k log k)', timeWhy: 'sorting each of n words of length up to k.', space: 'O(n * k)', spaceWhy: 'storing all words in the map.' }),
  gen: function () { var o = [[['eat', 'tea', 'tan', 'ate', 'nat', 'bat']]]; for (var k = 0; k < 32; k++) { var c = randInt(1, 6), w = []; for (var i = 0; i < c; i++) w.push(rw(1, 3, 'abc')); o.push([w]); } return o; },
  ref: function (a) { var strs = a[0], map = {}; strs.forEach(function (w) { var key = w.split('').sort().join(''); (map[key] = map[key] || []).push(w); }); var res = Object.keys(map).map(function (key) { return map[key]; }); return canonS(res, true); } });

module.exports = { MORE11 };
