// Known-correct solutions for Batch G (backtracking / combinatorial).
const SOL = {
  'subsets': {
    python: '        res=[]\n        def dfs(start,path):\n            res.append(path[:])\n            for i in range(start,len(nums)):\n                path.append(nums[i]); dfs(i+1,path); path.pop()\n        dfs(0,[])\n        return res',
    javascript: '    const res=[]; function dfs(start,path){res.push(path.slice());for(let i=start;i<nums.length;i++){path.push(nums[i]);dfs(i+1,path);path.pop();}} dfs(0,[]); return res;',
    cpp: '        vector<vector<int>> res; vector<int> path; function<void(int)> dfs=[&](int start){res.push_back(path);for(int i=start;i<(int)nums.size();i++){path.push_back(nums[i]);dfs(i+1);path.pop_back();}}; dfs(0); return res;',
    java: '        List<List<Integer>> res=new ArrayList<>(); dfs(nums,0,new ArrayList<>(),res); return res;\n    }\n    void dfs(int[] nums,int start,List<Integer> path,List<List<Integer>> res){res.add(new ArrayList<>(path));for(int i=start;i<nums.length;i++){path.add(nums[i]);dfs(nums,i+1,path,res);path.remove(path.size()-1);}',
  },
  'subsets-ii': {
    python: '        nums.sort()\n        res=[]\n        def dfs(start,path):\n            res.append(path[:])\n            for i in range(start,len(nums)):\n                if i>start and nums[i]==nums[i-1]: continue\n                path.append(nums[i]); dfs(i+1,path); path.pop()\n        dfs(0,[])\n        return res',
    javascript: '    nums.sort((a,b)=>a-b); const res=[]; function dfs(start,path){res.push(path.slice());for(let i=start;i<nums.length;i++){if(i>start&&nums[i]===nums[i-1])continue;path.push(nums[i]);dfs(i+1,path);path.pop();}} dfs(0,[]); return res;',
    cpp: '        sort(nums.begin(),nums.end()); vector<vector<int>> res; vector<int> path; function<void(int)> dfs=[&](int start){res.push_back(path);for(int i=start;i<(int)nums.size();i++){if(i>start&&nums[i]==nums[i-1])continue;path.push_back(nums[i]);dfs(i+1);path.pop_back();}}; dfs(0); return res;',
    java: '        Arrays.sort(nums); List<List<Integer>> res=new ArrayList<>(); dfs(nums,0,new ArrayList<>(),res); return res;\n    }\n    void dfs(int[] nums,int start,List<Integer> path,List<List<Integer>> res){res.add(new ArrayList<>(path));for(int i=start;i<nums.length;i++){if(i>start&&nums[i]==nums[i-1])continue;path.add(nums[i]);dfs(nums,i+1,path,res);path.remove(path.size()-1);}',
  },
  'permutations': {
    python: '        res=[]\n        used=[False]*len(nums)\n        def dfs(path):\n            if len(path)==len(nums): res.append(path[:]); return\n            for i in range(len(nums)):\n                if used[i]: continue\n                used[i]=True; path.append(nums[i]); dfs(path); path.pop(); used[i]=False\n        dfs([])\n        return res',
    javascript: '    const res=[],used=new Array(nums.length).fill(false); function dfs(path){if(path.length===nums.length){res.push(path.slice());return;}for(let i=0;i<nums.length;i++){if(used[i])continue;used[i]=true;path.push(nums[i]);dfs(path);path.pop();used[i]=false;}} dfs([]); return res;',
    cpp: '        vector<vector<int>> res; vector<int> path; vector<char> used(nums.size(),0); function<void()> dfs=[&](){if(path.size()==nums.size()){res.push_back(path);return;}for(int i=0;i<(int)nums.size();i++){if(used[i])continue;used[i]=1;path.push_back(nums[i]);dfs();path.pop_back();used[i]=0;}}; dfs(); return res;',
    java: '        List<List<Integer>> res=new ArrayList<>(); dfs(nums,new boolean[nums.length],new ArrayList<>(),res); return res;\n    }\n    void dfs(int[] nums,boolean[] used,List<Integer> path,List<List<Integer>> res){if(path.size()==nums.length){res.add(new ArrayList<>(path));return;}for(int i=0;i<nums.length;i++){if(used[i])continue;used[i]=true;path.add(nums[i]);dfs(nums,used,path,res);path.remove(path.size()-1);used[i]=false;}',
  },
  'combination-sum': {
    python: '        candidates.sort()\n        res=[]\n        def dfs(start,rem,path):\n            if rem==0: res.append(path[:]); return\n            for i in range(start,len(candidates)):\n                if candidates[i]>rem: break\n                path.append(candidates[i]); dfs(i,rem-candidates[i],path); path.pop()\n        dfs(0,target,[])\n        return res',
    javascript: '    candidates.sort((a,b)=>a-b); const res=[]; function dfs(start,rem,path){if(rem===0){res.push(path.slice());return;}for(let i=start;i<candidates.length;i++){if(candidates[i]>rem)break;path.push(candidates[i]);dfs(i,rem-candidates[i],path);path.pop();}} dfs(0,target,[]); return res;',
    cpp: '        sort(candidates.begin(),candidates.end()); vector<vector<int>> res; vector<int> path; function<void(int,int)> dfs=[&](int start,int rem){if(rem==0){res.push_back(path);return;}for(int i=start;i<(int)candidates.size();i++){if(candidates[i]>rem)break;path.push_back(candidates[i]);dfs(i,rem-candidates[i]);path.pop_back();}}; dfs(0,target); return res;',
    java: '        Arrays.sort(candidates); List<List<Integer>> res=new ArrayList<>(); dfs(candidates,0,target,new ArrayList<>(),res); return res;\n    }\n    void dfs(int[] c,int start,int rem,List<Integer> path,List<List<Integer>> res){if(rem==0){res.add(new ArrayList<>(path));return;}for(int i=start;i<c.length;i++){if(c[i]>rem)break;path.add(c[i]);dfs(c,i,rem-c[i],path,res);path.remove(path.size()-1);}',
  },
  'combination-sum-ii': {
    python: '        candidates.sort()\n        res=[]\n        def dfs(start,rem,path):\n            if rem==0: res.append(path[:]); return\n            for i in range(start,len(candidates)):\n                if i>start and candidates[i]==candidates[i-1]: continue\n                if candidates[i]>rem: break\n                path.append(candidates[i]); dfs(i+1,rem-candidates[i],path); path.pop()\n        dfs(0,target,[])\n        return res',
    javascript: '    candidates.sort((a,b)=>a-b); const res=[]; function dfs(start,rem,path){if(rem===0){res.push(path.slice());return;}for(let i=start;i<candidates.length;i++){if(i>start&&candidates[i]===candidates[i-1])continue;if(candidates[i]>rem)break;path.push(candidates[i]);dfs(i+1,rem-candidates[i],path);path.pop();}} dfs(0,target,[]); return res;',
    cpp: '        sort(candidates.begin(),candidates.end()); vector<vector<int>> res; vector<int> path; function<void(int,int)> dfs=[&](int start,int rem){if(rem==0){res.push_back(path);return;}for(int i=start;i<(int)candidates.size();i++){if(i>start&&candidates[i]==candidates[i-1])continue;if(candidates[i]>rem)break;path.push_back(candidates[i]);dfs(i+1,rem-candidates[i]);path.pop_back();}}; dfs(0,target); return res;',
    java: '        Arrays.sort(candidates); List<List<Integer>> res=new ArrayList<>(); dfs(candidates,0,target,new ArrayList<>(),res); return res;\n    }\n    void dfs(int[] c,int start,int rem,List<Integer> path,List<List<Integer>> res){if(rem==0){res.add(new ArrayList<>(path));return;}for(int i=start;i<c.length;i++){if(i>start&&c[i]==c[i-1])continue;if(c[i]>rem)break;path.add(c[i]);dfs(c,i+1,rem-c[i],path,res);path.remove(path.size()-1);}',
  },
  'palindrome-partitioning': {
    python: '        res=[]\n        def isPal(l,r):\n            while l<r:\n                if s[l]!=s[r]: return False\n                l+=1; r-=1\n            return True\n        def dfs(start,path):\n            if start==len(s): res.append(path[:]); return\n            for end in range(start,len(s)):\n                if isPal(start,end):\n                    path.append(s[start:end+1]); dfs(end+1,path); path.pop()\n        dfs(0,[])\n        return res',
    javascript: '    const res=[]; function isPal(l,r){while(l<r){if(s[l]!==s[r])return false;l++;r--;}return true;} function dfs(start,path){if(start===s.length){res.push(path.slice());return;}for(let end=start;end<s.length;end++)if(isPal(start,end)){path.push(s.slice(start,end+1));dfs(end+1,path);path.pop();}} dfs(0,[]); return res;',
    cpp: '        vector<vector<string>> res; vector<string> path; function<bool(int,int)> isPal=[&](int l,int r){while(l<r){if(s[l]!=s[r])return false;l++;r--;}return true;}; function<void(int)> dfs=[&](int start){if(start==(int)s.size()){res.push_back(path);return;}for(int end=start;end<(int)s.size();end++)if(isPal(start,end)){path.push_back(s.substr(start,end-start+1));dfs(end+1);path.pop_back();}}; dfs(0); return res;',
    java: '        List<List<String>> res=new ArrayList<>(); dfs(s,0,new ArrayList<>(),res); return res;\n    }\n    boolean isPal(String s,int l,int r){while(l<r){if(s.charAt(l)!=s.charAt(r))return false;l++;r--;}return true;}\n    void dfs(String s,int start,List<String> path,List<List<String>> res){if(start==s.length()){res.add(new ArrayList<>(path));return;}for(int end=start;end<s.length();end++)if(isPal(s,start,end)){path.add(s.substring(start,end+1));dfs(s,end+1,path,res);path.remove(path.size()-1);}',
  },
  'generate-parentheses': {
    python: "        res=[]\n        def dfs(cur,op,cl):\n            if len(cur)==2*n: res.append(cur); return\n            if op<n: dfs(cur+'(',op+1,cl)\n            if cl<op: dfs(cur+')',op,cl+1)\n        dfs('',0,0)\n        return res",
    javascript: "    const res=[]; function dfs(cur,op,cl){if(cur.length===2*n){res.push(cur);return;}if(op<n)dfs(cur+'(',op+1,cl);if(cl<op)dfs(cur+')',op,cl+1);} dfs('',0,0); return res;",
    cpp: '        vector<string> res; function<void(string,int,int)> dfs=[&](string cur,int op,int cl){if((int)cur.size()==2*n){res.push_back(cur);return;}if(op<n)dfs(cur+"(",op+1,cl);if(cl<op)dfs(cur+")",op,cl+1);}; dfs("",0,0); return res;',
    java: '        List<String> res=new ArrayList<>(); dfs("",0,0,n,res); return res;\n    }\n    void dfs(String cur,int op,int cl,int n,List<String> res){if(cur.length()==2*n){res.add(cur);return;}if(op<n)dfs(cur+"(",op+1,cl,n,res);if(cl<op)dfs(cur+")",op,cl+1,n,res);',
  },
  'letter-combinations-of-a-phone-number': {
    python: "        if not digits: return []\n        m={'2':'abc','3':'def','4':'ghi','5':'jkl','6':'mno','7':'pqrs','8':'tuv','9':'wxyz'}\n        res=['']\n        for d in digits:\n            res=[p+c for p in res for c in m[d]]\n        return res",
    javascript: "    if(!digits.length)return []; const m={'2':'abc','3':'def','4':'ghi','5':'jkl','6':'mno','7':'pqrs','8':'tuv','9':'wxyz'}; let res=['']; for(const d of digits){const next=[];for(const p of res)for(const c of m[d])next.push(p+c);res=next;} return res;",
    cpp: '        if(digits.empty())return {}; map<char,string> m={{\'2\',"abc"},{\'3\',"def"},{\'4\',"ghi"},{\'5\',"jkl"},{\'6\',"mno"},{\'7\',"pqrs"},{\'8\',"tuv"},{\'9\',"wxyz"}}; vector<string> res={""}; for(char d:digits){vector<string> next;for(auto&p:res)for(char c:m[d])next.push_back(p+c);res=next;} return res;',
    java: '        List<String> res=new ArrayList<>(); if(digits.isEmpty())return res; String[] m={"","","abc","def","ghi","jkl","mno","pqrs","tuv","wxyz"}; res.add(""); for(char d:digits.toCharArray()){List<String> next=new ArrayList<>();for(String p:res)for(char c:m[d-\'0\'].toCharArray())next.add(p+c);res=next;} return res;',
  },
  '3sum': {
    python: '        nums.sort()\n        res=[]\n        n=len(nums)\n        for i in range(n):\n            if i>0 and nums[i]==nums[i-1]: continue\n            l,r=i+1,n-1\n            while l<r:\n                s=nums[i]+nums[l]+nums[r]\n                if s==0:\n                    res.append([nums[i],nums[l],nums[r]]); l+=1; r-=1\n                    while l<r and nums[l]==nums[l-1]: l+=1\n                    while l<r and nums[r]==nums[r+1]: r-=1\n                elif s<0: l+=1\n                else: r-=1\n        return res',
    javascript: '    nums.sort((a,b)=>a-b); const res=[],n=nums.length; for(let i=0;i<n;i++){if(i>0&&nums[i]===nums[i-1])continue;let l=i+1,r=n-1;while(l<r){const s=nums[i]+nums[l]+nums[r];if(s===0){res.push([nums[i],nums[l],nums[r]]);l++;r--;while(l<r&&nums[l]===nums[l-1])l++;while(l<r&&nums[r]===nums[r+1])r--;}else if(s<0)l++;else r--;}} return res;',
    cpp: '        sort(nums.begin(),nums.end()); vector<vector<int>> res; int n=nums.size(); for(int i=0;i<n;i++){if(i>0&&nums[i]==nums[i-1])continue;int l=i+1,r=n-1;while(l<r){int s=nums[i]+nums[l]+nums[r];if(s==0){res.push_back({nums[i],nums[l],nums[r]});l++;r--;while(l<r&&nums[l]==nums[l-1])l++;while(l<r&&nums[r]==nums[r+1])r--;}else if(s<0)l++;else r--;}} return res;',
    java: '        Arrays.sort(nums); List<List<Integer>> res=new ArrayList<>(); int n=nums.length; for(int i=0;i<n;i++){if(i>0&&nums[i]==nums[i-1])continue;int l=i+1,r=n-1;while(l<r){int s=nums[i]+nums[l]+nums[r];if(s==0){res.add(Arrays.asList(nums[i],nums[l],nums[r]));l++;r--;while(l<r&&nums[l]==nums[l-1])l++;while(l<r&&nums[r]==nums[r+1])r--;}else if(s<0)l++;else r--;}} return res;',
  },
  'group-anagrams': {
    python: "        groups={}\n        for w in strs:\n            key=''.join(sorted(w))\n            groups.setdefault(key,[]).append(w)\n        return list(groups.values())",
    javascript: "    const groups={}; for(const w of strs){const key=w.split('').sort().join('');(groups[key]=groups[key]||[]).push(w);} return Object.keys(groups).map(k=>groups[k]);",
    cpp: '        map<string,vector<string>> groups; for(auto& w:strs){string key=w;sort(key.begin(),key.end());groups[key].push_back(w);} vector<vector<string>> res; for(auto& kv:groups)res.push_back(kv.second); return res;',
    java: '        Map<String,List<String>> groups=new HashMap<>(); for(String w:strs){char[] c=w.toCharArray();Arrays.sort(c);String key=new String(c);groups.computeIfAbsent(key,z->new ArrayList<>()).add(w);} return new ArrayList<>(groups.values());',
  },
};
module.exports = { SOL };
