// Full-class solutions for design (OPS) problems. Marked FULL (display as-is).
const FULL = true;
const SOL = {
  'min-stack': {
    python: 'class MinStack:\n    def __init__(self):\n        self.st = []\n        self.mins = []\n    def push(self, val):\n        self.st.append(val)\n        self.mins.append(val if not self.mins else min(val, self.mins[-1]))\n    def pop(self):\n        self.st.pop(); self.mins.pop()\n    def top(self):\n        return self.st[-1]\n    def getMin(self):\n        return self.mins[-1]',
    javascript: 'class MinStack {\n  constructor() { this.st = []; this.mins = []; }\n  push(val) {\n    this.st.push(val);\n    this.mins.push(this.mins.length ? Math.min(val, this.mins[this.mins.length - 1]) : val);\n  }\n  pop() { this.st.pop(); this.mins.pop(); }\n  top() { return this.st[this.st.length - 1]; }\n  getMin() { return this.mins[this.mins.length - 1]; }\n}',
    cpp: 'class MinStack {\n    vector<int> st, mins;\npublic:\n    MinStack() {}\n    void push(int val) {\n        st.push_back(val);\n        mins.push_back(mins.empty() ? val : min(val, mins.back()));\n    }\n    void pop() { st.pop_back(); mins.pop_back(); }\n    int top() { return st.back(); }\n    int getMin() { return mins.back(); }\n};',
    java: 'class MinStack {\n    Deque<Integer> st = new ArrayDeque<>();\n    Deque<Integer> mins = new ArrayDeque<>();\n    public MinStack() {}\n    public void push(int val) {\n        st.push(val);\n        mins.push(mins.isEmpty() ? val : Math.min(val, mins.peek()));\n    }\n    public void pop() { st.pop(); mins.pop(); }\n    public int top() { return st.peek(); }\n    public int getMin() { return mins.peek(); }\n}',
  },
  'implement-trie-prefix-tree': {
    python: 'class Trie:\n    def __init__(self):\n        self.ch = {}\n        self.end = False\n    def insert(self, word):\n        node = self\n        for c in word:\n            node = node.ch.setdefault(c, Trie())\n        node.end = True\n    def _find(self, word):\n        node = self\n        for c in word:\n            if c not in node.ch:\n                return None\n            node = node.ch[c]\n        return node\n    def search(self, word):\n        n = self._find(word)\n        return n is not None and n.end\n    def startsWith(self, prefix):\n        return self._find(prefix) is not None',
    javascript: 'class Trie {\n  constructor() { this.ch = {}; this.end = false; }\n  insert(w) { let n = this; for (const c of w) { if (!n.ch[c]) n.ch[c] = new Trie(); n = n.ch[c]; } n.end = true; }\n  _find(w) { let n = this; for (const c of w) { if (!n.ch[c]) return null; n = n.ch[c]; } return n; }\n  search(w) { const n = this._find(w); return n !== null && n.end; }\n  startsWith(p) { return this._find(p) !== null; }\n}',
    cpp: 'struct Trie {\n    map<char, Trie*> ch;\n    bool end = false;\n    Trie() {}\n    void insert(string w) { Trie* n = this; for (char c : w) { if (!n->ch.count(c)) n->ch[c] = new Trie(); n = n->ch[c]; } n->end = true; }\n    Trie* find(string w) { Trie* n = this; for (char c : w) { if (!n->ch.count(c)) return nullptr; n = n->ch[c]; } return n; }\n    bool search(string w) { Trie* n = find(w); return n && n->end; }\n    bool startsWith(string p) { return find(p) != nullptr; }\n};',
    java: 'class Trie {\n    Map<Character, Trie> ch = new HashMap<>();\n    boolean end = false;\n    public Trie() {}\n    public void insert(String w) { Trie n = this; for (char c : w.toCharArray()) { n.ch.putIfAbsent(c, new Trie()); n = n.ch.get(c); } n.end = true; }\n    Trie find(String w) { Trie n = this; for (char c : w.toCharArray()) { if (!n.ch.containsKey(c)) return null; n = n.ch.get(c); } return n; }\n    public boolean search(String w) { Trie n = find(w); return n != null && n.end; }\n    public boolean startsWith(String p) { return find(p) != null; }\n}',
  },
  'design-add-and-search-words-data-structure': {
    python: 'class WordDictionary:\n    def __init__(self):\n        self.ch = {}\n        self.end = False\n    def addWord(self, word):\n        node = self\n        for c in word:\n            node = node.ch.setdefault(c, WordDictionary())\n        node.end = True\n    def search(self, word):\n        def dfs(node, i):\n            if i == len(word):\n                return node.end\n            c = word[i]\n            if c == ".":\n                return any(dfs(x, i + 1) for x in node.ch.values())\n            return c in node.ch and dfs(node.ch[c], i + 1)\n        return dfs(self, 0)',
    javascript: 'class WordDictionary {\n  constructor() { this.ch = {}; this.end = false; }\n  addWord(w) { let n = this; for (const c of w) { if (!n.ch[c]) n.ch[c] = new WordDictionary(); n = n.ch[c]; } n.end = true; }\n  search(w) {\n    const dfs = (n, i) => {\n      if (i === w.length) return n.end;\n      const c = w[i];\n      if (c === ".") return Object.values(n.ch).some(x => dfs(x, i + 1));\n      return n.ch[c] !== undefined && dfs(n.ch[c], i + 1);\n    };\n    return dfs(this, 0);\n  }\n}',
    cpp: 'struct WordDictionary {\n    map<char, WordDictionary*> ch;\n    bool end = false;\n    WordDictionary() {}\n    void addWord(string w) { WordDictionary* n = this; for (char c : w) { if (!n->ch.count(c)) n->ch[c] = new WordDictionary(); n = n->ch[c]; } n->end = true; }\n    bool search(string w) {\n        function<bool(WordDictionary*, int)> dfs = [&](WordDictionary* n, int i) -> bool {\n            if (i == (int)w.size()) return n->end;\n            char c = w[i];\n            if (c == \'.\') { for (auto& kv : n->ch) if (dfs(kv.second, i + 1)) return true; return false; }\n            return n->ch.count(c) && dfs(n->ch[c], i + 1);\n        };\n        return dfs(this, 0);\n    }\n};',
    java: 'class WordDictionary {\n    Map<Character, WordDictionary> ch = new HashMap<>();\n    boolean end = false;\n    public WordDictionary() {}\n    public void addWord(String w) { WordDictionary n = this; for (char c : w.toCharArray()) { n.ch.putIfAbsent(c, new WordDictionary()); n = n.ch.get(c); } n.end = true; }\n    public boolean search(String w) { return dfs(this, w, 0); }\n    boolean dfs(WordDictionary n, String w, int i) {\n        if (i == w.length()) return n.end;\n        char c = w.charAt(i);\n        if (c == \'.\') { for (WordDictionary x : n.ch.values()) if (dfs(x, w, i + 1)) return true; return false; }\n        return n.ch.containsKey(c) && dfs(n.ch.get(c), w, i + 1);\n    }\n}',
  },
  'time-based-key-value-store': {
    python: 'class TimeMap:\n    def __init__(self):\n        self.store = {}\n    def set(self, key, value, timestamp):\n        self.store.setdefault(key, []).append((timestamp, value))\n    def get(self, key, timestamp):\n        arr = self.store.get(key, [])\n        best = ""\n        for t, v in arr:\n            if t <= timestamp:\n                best = v\n        return best',
    javascript: 'class TimeMap {\n  constructor() { this.store = {}; }\n  set(key, value, timestamp) { (this.store[key] = this.store[key] || []).push([timestamp, value]); }\n  get(key, timestamp) {\n    const arr = this.store[key] || [];\n    let best = "";\n    for (const [t, v] of arr) if (t <= timestamp) best = v;\n    return best;\n  }\n}',
    cpp: 'class TimeMap {\n    map<string, vector<pair<int, string>>> store;\npublic:\n    TimeMap() {}\n    void set(string key, string value, int timestamp) { store[key].push_back({timestamp, value}); }\n    string get(string key, int timestamp) {\n        string best = "";\n        for (auto& pr : store[key]) if (pr.first <= timestamp) best = pr.second;\n        return best;\n    }\n};',
    java: 'class TimeMap {\n    Map<String, List<Object[]>> store = new HashMap<>();\n    public TimeMap() {}\n    public void set(String key, String value, int timestamp) { store.computeIfAbsent(key, z -> new ArrayList<>()).add(new Object[]{timestamp, value}); }\n    public String get(String key, int timestamp) {\n        String best = "";\n        for (Object[] pr : store.getOrDefault(key, new ArrayList<>())) if ((int) pr[0] <= timestamp) best = (String) pr[1];\n        return best;\n    }\n}',
  },
  'lru-cache': {
    python: 'from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity):\n        self.cap = capacity\n        self.cache = OrderedDict()\n    def get(self, key):\n        if key not in self.cache:\n            return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n    def put(self, key, value):\n        if key in self.cache:\n            self.cache.move_to_end(key)\n        self.cache[key] = value\n        if len(self.cache) > self.cap:\n            self.cache.popitem(last=False)',
    javascript: 'class LRUCache {\n  constructor(capacity) { this.cap = capacity; this.map = new Map(); }\n  get(key) {\n    if (!this.map.has(key)) return -1;\n    const v = this.map.get(key);\n    this.map.delete(key); this.map.set(key, v);\n    return v;\n  }\n  put(key, value) {\n    if (this.map.has(key)) this.map.delete(key);\n    this.map.set(key, value);\n    if (this.map.size > this.cap) this.map.delete(this.map.keys().next().value);\n  }\n}',
    cpp: 'class LRUCache {\n    int cap;\n    list<pair<int,int>> lru;\n    unordered_map<int, list<pair<int,int>>::iterator> mp;\npublic:\n    LRUCache(int capacity) : cap(capacity) {}\n    int get(int key) {\n        if (!mp.count(key)) return -1;\n        lru.splice(lru.begin(), lru, mp[key]);\n        return mp[key]->second;\n    }\n    void put(int key, int value) {\n        if (mp.count(key)) { mp[key]->second = value; lru.splice(lru.begin(), lru, mp[key]); return; }\n        if ((int)lru.size() >= cap) { mp.erase(lru.back().first); lru.pop_back(); }\n        lru.push_front({key, value});\n        mp[key] = lru.begin();\n    }\n};',
    java: 'class LRUCache {\n    int cap;\n    LinkedHashMap<Integer, Integer> map = new LinkedHashMap<>();\n    public LRUCache(int capacity) { cap = capacity; }\n    public int get(int key) {\n        if (!map.containsKey(key)) return -1;\n        int v = map.remove(key); map.put(key, v);\n        return v;\n    }\n    public void put(int key, int value) {\n        if (map.containsKey(key)) map.remove(key);\n        map.put(key, value);\n        if (map.size() > cap) map.remove(map.keySet().iterator().next());\n    }\n}',
  },
};
module.exports = { SOL, FULL };
