// Known-correct solutions for Batch H (graph) problems.
const SOL = {
  'course-schedule': {
    python: '        adj=[[] for _ in range(n)]\n        indeg=[0]*n\n        for a,b in edges:\n            adj[b].append(a); indeg[a]+=1\n        from collections import deque\n        q=deque(i for i in range(n) if indeg[i]==0)\n        seen=0\n        while q:\n            u=q.popleft(); seen+=1\n            for v in adj[u]:\n                indeg[v]-=1\n                if indeg[v]==0: q.append(v)\n        return seen==n',
    javascript: '    const adj=Array.from({length:n},()=>[]),indeg=new Array(n).fill(0); for(const e of edges){adj[e[1]].push(e[0]);indeg[e[0]]++;} const q=[]; for(let i=0;i<n;i++)if(indeg[i]===0)q.push(i); let seen=0; while(q.length){const u=q.shift();seen++;for(const v of adj[u]){if(--indeg[v]===0)q.push(v);}} return seen===n;',
    cpp: '        vector<vector<int>> adj(n); vector<int> indeg(n,0); for(auto& e:edges){adj[e[1]].push_back(e[0]);indeg[e[0]]++;} queue<int> q; for(int i=0;i<n;i++)if(indeg[i]==0)q.push(i); int seen=0; while(!q.empty()){int u=q.front();q.pop();seen++;for(int v:adj[u])if(--indeg[v]==0)q.push(v);} return seen==n;',
    java: '        List<List<Integer>> adj=new ArrayList<>(); for(int i=0;i<n;i++)adj.add(new ArrayList<>()); int[] indeg=new int[n]; for(int[] e:edges){adj.get(e[1]).add(e[0]);indeg[e[0]]++;} Deque<Integer> q=new ArrayDeque<>(); for(int i=0;i<n;i++)if(indeg[i]==0)q.add(i); int seen=0; while(!q.isEmpty()){int u=q.poll();seen++;for(int v:adj.get(u))if(--indeg[v]==0)q.add(v);} return seen==n;',
  },
  'number-of-connected-components-in-an-undirected-graph': {
    python: '        par=list(range(n))\n        def find(x):\n            while par[x]!=x:\n                par[x]=par[par[x]]; x=par[x]\n            return x\n        comp=n\n        for a,b in edges:\n            ra,rb=find(a),find(b)\n            if ra!=rb: par[ra]=rb; comp-=1\n        return comp',
    javascript: '    const par=[]; for(let i=0;i<n;i++)par[i]=i; function find(x){while(par[x]!==x){par[x]=par[par[x]];x=par[x];}return x;} let comp=n; for(const e of edges){const ra=find(e[0]),rb=find(e[1]); if(ra!==rb){par[ra]=rb;comp--;}} return comp;',
    cpp: '        vector<int> par(n); for(int i=0;i<n;i++)par[i]=i; function<int(int)> find=[&](int x){while(par[x]!=x){par[x]=par[par[x]];x=par[x];}return x;}; int comp=n; for(auto& e:edges){int ra=find(e[0]),rb=find(e[1]); if(ra!=rb){par[ra]=rb;comp--;}} return comp;',
    java: '        int[] par=new int[n]; for(int i=0;i<n;i++)par[i]=i; int comp=n; for(int[] e:edges){int ra=find(par,e[0]),rb=find(par,e[1]); if(ra!=rb){par[ra]=rb;comp--;}} return comp;\n    }\n    int find(int[] par,int x){while(par[x]!=x){par[x]=par[par[x]];x=par[x];}return x;',
  },
  'graph-valid-tree': {
    python: '        if len(edges)!=n-1: return False\n        par=list(range(n))\n        def find(x):\n            while par[x]!=x:\n                par[x]=par[par[x]]; x=par[x]\n            return x\n        comp=n\n        for a,b in edges:\n            ra,rb=find(a),find(b)\n            if ra==rb: return False\n            par[ra]=rb; comp-=1\n        return comp==1',
    javascript: '    if(edges.length!==n-1)return false; const par=[]; for(let i=0;i<n;i++)par[i]=i; function find(x){while(par[x]!==x){par[x]=par[par[x]];x=par[x];}return x;} let comp=n; for(const e of edges){const ra=find(e[0]),rb=find(e[1]); if(ra===rb)return false; par[ra]=rb;comp--;} return comp===1;',
    cpp: '        if((int)edges.size()!=n-1)return false; vector<int> par(n); for(int i=0;i<n;i++)par[i]=i; function<int(int)> find=[&](int x){while(par[x]!=x){par[x]=par[par[x]];x=par[x];}return x;}; int comp=n; for(auto& e:edges){int ra=find(e[0]),rb=find(e[1]); if(ra==rb)return false; par[ra]=rb;comp--;} return comp==1;',
    java: '        if(edges.length!=n-1)return false; int[] par=new int[n]; for(int i=0;i<n;i++)par[i]=i; int comp=n; for(int[] e:edges){int ra=find(par,e[0]),rb=find(par,e[1]); if(ra==rb)return false; par[ra]=rb;comp--;} return comp==1;\n    }\n    int find(int[] par,int x){while(par[x]!=x){par[x]=par[par[x]];x=par[x];}return x;',
  },
  'redundant-connection': {
    python: '        par=list(range(len(edges)+1))\n        def find(x):\n            while par[x]!=x:\n                par[x]=par[par[x]]; x=par[x]\n            return x\n        for a,b in edges:\n            ra,rb=find(a),find(b)\n            if ra==rb: return [a,b]\n            par[ra]=rb\n        return []',
    javascript: '    const par=[]; for(let i=0;i<=edges.length;i++)par[i]=i; function find(x){while(par[x]!==x){par[x]=par[par[x]];x=par[x];}return x;} for(const e of edges){const ra=find(e[0]),rb=find(e[1]); if(ra===rb)return [e[0],e[1]]; par[ra]=rb;} return [];',
    cpp: '        int mx=edges.size()+1; vector<int> par(mx+1); for(int i=0;i<=mx;i++)par[i]=i; function<int(int)> find=[&](int x){while(par[x]!=x){par[x]=par[par[x]];x=par[x];}return x;}; for(auto& e:edges){int ra=find(e[0]),rb=find(e[1]); if(ra==rb)return vector<int>{e[0],e[1]}; par[ra]=rb;} return {};',
    java: '        int mx=edges.length+1; int[] par=new int[mx+1]; for(int i=0;i<=mx;i++)par[i]=i; for(int[] e:edges){int ra=find(par,e[0]),rb=find(par,e[1]); if(ra==rb)return new int[]{e[0],e[1]}; par[ra]=rb;} return new int[]{};\n    }\n    int find(int[] par,int x){while(par[x]!=x){par[x]=par[par[x]];x=par[x];}return x;',
  },
  'min-cost-to-connect-all-points': {
    python: "        pts=grid; n=len(pts)\n        if n<=1: return 0\n        in_mst=[False]*n; dist=[float('inf')]*n; dist[0]=0; total=0\n        for _ in range(n):\n            u=-1\n            for i in range(n):\n                if not in_mst[i] and (u==-1 or dist[i]<dist[u]): u=i\n            in_mst[u]=True; total+=dist[u]\n            for v in range(n):\n                if not in_mst[v]:\n                    d=abs(pts[u][0]-pts[v][0])+abs(pts[u][1]-pts[v][1])\n                    if d<dist[v]: dist[v]=d\n        return total",
    javascript: '    const pts=grid,n=pts.length; if(n<=1)return 0; const inMst=new Array(n).fill(false),dist=new Array(n).fill(Infinity); dist[0]=0; let total=0; for(let it=0;it<n;it++){let u=-1; for(let i=0;i<n;i++)if(!inMst[i]&&(u===-1||dist[i]<dist[u]))u=i; inMst[u]=true; total+=dist[u]; for(let v=0;v<n;v++)if(!inMst[v]){const d=Math.abs(pts[u][0]-pts[v][0])+Math.abs(pts[u][1]-pts[v][1]); if(d<dist[v])dist[v]=d;}} return total;',
    cpp: '        auto& pts=grid; int n=pts.size(); if(n<=1)return 0; vector<char> inMst(n,0); vector<long long> dist(n,LLONG_MAX); dist[0]=0; long long total=0; for(int it=0;it<n;it++){int u=-1; for(int i=0;i<n;i++)if(!inMst[i]&&(u==-1||dist[i]<dist[u]))u=i; inMst[u]=1; total+=dist[u]; for(int v=0;v<n;v++)if(!inMst[v]){long long d=abs(pts[u][0]-pts[v][0])+abs(pts[u][1]-pts[v][1]); if(d<dist[v])dist[v]=d;}} return (int)total;',
    java: '        int[][] pts=grid; int n=pts.length; if(n<=1)return 0; boolean[] inMst=new boolean[n]; long[] dist=new long[n]; Arrays.fill(dist,Long.MAX_VALUE); dist[0]=0; long total=0; for(int it=0;it<n;it++){int u=-1; for(int i=0;i<n;i++)if(!inMst[i]&&(u==-1||dist[i]<dist[u]))u=i; inMst[u]=true; total+=dist[u]; for(int v=0;v<n;v++)if(!inMst[v]){long d=Math.abs(pts[u][0]-pts[v][0])+Math.abs(pts[u][1]-pts[v][1]); if(d<dist[v])dist[v]=d;}} return (int)total;',
  },
  'walls-and-gates': {
    python: '        R,C=len(grid),len(grid[0])\n        from collections import deque\n        q=deque((r,c) for r in range(R) for c in range(C) if grid[r][c]==0)\n        while q:\n            r,c=q.popleft()\n            for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n                nr,nc=r+dr,c+dc\n                if 0<=nr<R and 0<=nc<C and grid[nr][nc]==2147483647:\n                    grid[nr][nc]=grid[r][c]+1; q.append((nr,nc))\n        return grid',
    javascript: '    const R=grid.length,C=grid[0].length,q=[]; for(let r=0;r<R;r++)for(let c=0;c<C;c++)if(grid[r][c]===0)q.push([r,c]); let idx=0; while(idx<q.length){const cur=q[idx++],r=cur[0],c=cur[1]; for(const d of [[1,0],[-1,0],[0,1],[0,-1]]){const nr=r+d[0],nc=c+d[1]; if(nr>=0&&nr<R&&nc>=0&&nc<C&&grid[nr][nc]===2147483647){grid[nr][nc]=grid[r][c]+1;q.push([nr,nc]);}}} return grid;',
    cpp: '        int R=grid.size(),C=grid[0].size(); queue<pair<int,int>> q; for(int r=0;r<R;r++)for(int c=0;c<C;c++)if(grid[r][c]==0)q.push({r,c}); int dr[]={1,-1,0,0},dc[]={0,0,1,-1}; while(!q.empty()){auto cur=q.front();q.pop(); for(int d=0;d<4;d++){int nr=cur.first+dr[d],nc=cur.second+dc[d]; if(nr>=0&&nr<R&&nc>=0&&nc<C&&grid[nr][nc]==2147483647){grid[nr][nc]=grid[cur.first][cur.second]+1;q.push({nr,nc});}}} return grid;',
    java: '        int R=grid.length,C=grid[0].length; Deque<int[]> q=new ArrayDeque<>(); for(int r=0;r<R;r++)for(int c=0;c<C;c++)if(grid[r][c]==0)q.add(new int[]{r,c}); int[] dr={1,-1,0,0},dc={0,0,1,-1}; while(!q.isEmpty()){int[] cur=q.poll(); for(int d=0;d<4;d++){int nr=cur[0]+dr[d],nc=cur[1]+dc[d]; if(nr>=0&&nr<R&&nc>=0&&nc<C&&grid[nr][nc]==2147483647){grid[nr][nc]=grid[cur[0]][cur[1]]+1;q.add(new int[]{nr,nc});}}} return grid;',
  },
  'surrounded-regions': {
    python: "        if not board: return\n        R,C=len(board),len(board[0])\n        def dfs(r,c):\n            if r<0 or r>=R or c<0 or c>=C or board[r][c]!='O': return\n            board[r][c]='#'\n            dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\n        for r in range(R):\n            dfs(r,0); dfs(r,C-1)\n        for c in range(C):\n            dfs(0,c); dfs(R-1,c)\n        for r in range(R):\n            for c in range(C):\n                if board[r][c]=='O': board[r][c]='X'\n                elif board[r][c]=='#': board[r][c]='O'",
    javascript: "    const R=board.length,C=board[0].length; function dfs(r,c){if(r<0||r>=R||c<0||c>=C||board[r][c]!=='O')return;board[r][c]='#';dfs(r+1,c);dfs(r-1,c);dfs(r,c+1);dfs(r,c-1);} for(let r=0;r<R;r++){dfs(r,0);dfs(r,C-1);} for(let c=0;c<C;c++){dfs(0,c);dfs(R-1,c);} for(let r=0;r<R;r++)for(let c=0;c<C;c++){if(board[r][c]==='O')board[r][c]='X';else if(board[r][c]==='#')board[r][c]='O';}",
    cpp: "        int R=board.size(),C=board[0].size(); function<void(int,int)> dfs=[&](int r,int c){if(r<0||r>=R||c<0||c>=C||board[r][c]!='O')return;board[r][c]='#';dfs(r+1,c);dfs(r-1,c);dfs(r,c+1);dfs(r,c-1);}; for(int r=0;r<R;r++){dfs(r,0);dfs(r,C-1);} for(int c=0;c<C;c++){dfs(0,c);dfs(R-1,c);} for(int r=0;r<R;r++)for(int c=0;c<C;c++){if(board[r][c]=='O')board[r][c]='X';else if(board[r][c]=='#')board[r][c]='O';}",
    java: "        int R=board.length,C=board[0].length; for(int r=0;r<R;r++){dfs(board,r,0);dfs(board,r,C-1);} for(int c=0;c<C;c++){dfs(board,0,c);dfs(board,R-1,c);} for(int r=0;r<R;r++)for(int c=0;c<C;c++){if(board[r][c]=='O')board[r][c]='X';else if(board[r][c]=='#')board[r][c]='O';}\n    }\n    void dfs(char[][] board,int r,int c){int R=board.length,C=board[0].length; if(r<0||r>=R||c<0||c>=C||board[r][c]!='O')return; board[r][c]='#'; dfs(board,r+1,c);dfs(board,r-1,c);dfs(board,r,c+1);dfs(board,r,c-1);",
  },
  'word-ladder': {
    python: "        words=set(wordList)\n        if endWord not in words: return 0\n        from collections import deque\n        q=deque([(beginWord,1)]); seen={beginWord}\n        while q:\n            w,d=q.popleft()\n            if w==endWord: return d\n            for i in range(len(w)):\n                for c in 'abcdefghijklmnopqrstuvwxyz':\n                    nxt=w[:i]+c+w[i+1:]\n                    if nxt in words and nxt not in seen:\n                        seen.add(nxt); q.append((nxt,d+1))\n        return 0",
    javascript: "    const words=new Set(wordList); if(!words.has(endWord))return 0; const q=[[beginWord,1]],seen=new Set([beginWord]); let idx=0; while(idx<q.length){const cur=q[idx++],w=cur[0],d=cur[1]; if(w===endWord)return d; for(let i=0;i<w.length;i++)for(let c=97;c<123;c++){const nxt=w.slice(0,i)+String.fromCharCode(c)+w.slice(i+1); if(words.has(nxt)&&!seen.has(nxt)){seen.add(nxt);q.push([nxt,d+1]);}}} return 0;",
    cpp: "        unordered_set<string> words(wordList.begin(),wordList.end()); if(!words.count(endWord))return 0; queue<pair<string,int>> q; q.push({beginWord,1}); unordered_set<string> seen; seen.insert(beginWord); while(!q.empty()){auto cur=q.front();q.pop();string w=cur.first;int d=cur.second; if(w==endWord)return d; for(int i=0;i<(int)w.size();i++){string nx=w; for(char c='a';c<='z';c++){nx[i]=c; if(words.count(nx)&&!seen.count(nx)){seen.insert(nx);q.push({nx,d+1});}}}} return 0;",
    java: "        Set<String> words=new HashSet<>(wordList); if(!words.contains(endWord))return 0; Deque<Object[]> q=new ArrayDeque<>(); q.add(new Object[]{beginWord,1}); Set<String> seen=new HashSet<>(); seen.add(beginWord); while(!q.isEmpty()){Object[] cur=q.poll();String w=(String)cur[0];int d=(int)cur[1]; if(w.equals(endWord))return d; char[] arr=w.toCharArray(); for(int i=0;i<arr.length;i++){char old=arr[i]; for(char c='a';c<='z';c++){arr[i]=c;String nx=new String(arr); if(words.contains(nx)&&!seen.contains(nx)){seen.add(nx);q.add(new Object[]{nx,d+1});}} arr[i]=old;}} return 0;",
  },
};
module.exports = { SOL };
