// Known-correct solutions for Batch B (grid) problems.
const SOL = {
  'number-of-islands': {
    python: "        R,C=len(grid),len(grid[0])\n        def sink(r,c):\n            if r<0 or r>=R or c<0 or c>=C or grid[r][c]!='1': return\n            grid[r][c]='0'\n            sink(r+1,c);sink(r-1,c);sink(r,c+1);sink(r,c-1)\n        cnt=0\n        for r in range(R):\n            for c in range(C):\n                if grid[r][c]=='1':\n                    cnt+=1; sink(r,c)\n        return cnt",
    javascript: "    const R=grid.length,C=grid[0].length; function sink(r,c){if(r<0||r>=R||c<0||c>=C||grid[r][c]!=='1')return;grid[r][c]='0';sink(r+1,c);sink(r-1,c);sink(r,c+1);sink(r,c-1);} let cnt=0; for(let r=0;r<R;r++)for(let c=0;c<C;c++)if(grid[r][c]==='1'){cnt++;sink(r,c);} return cnt;",
    cpp: "        int R=grid.size(),C=grid[0].size(),cnt=0; function<void(int,int)> sink=[&](int r,int c){if(r<0||r>=R||c<0||c>=C||grid[r][c]!='1')return;grid[r][c]='0';sink(r+1,c);sink(r-1,c);sink(r,c+1);sink(r,c-1);}; for(int r=0;r<R;r++)for(int c=0;c<C;c++)if(grid[r][c]=='1'){cnt++;sink(r,c);} return cnt;",
    java: "        int R=grid.length,C=grid[0].length,cnt=0; for(int r=0;r<R;r++)for(int c=0;c<C;c++)if(grid[r][c]=='1'){cnt++;sink(grid,r,c);} return cnt;\n    }\n    void sink(char[][] grid,int r,int c){int R=grid.length,C=grid[0].length; if(r<0||r>=R||c<0||c>=C||grid[r][c]!='1')return; grid[r][c]='0'; sink(grid,r+1,c);sink(grid,r-1,c);sink(grid,r,c+1);sink(grid,r,c-1);",
  },
  'max-area-of-island': {
    python: '        R,C=len(grid),len(grid[0])\n        def dfs(r,c):\n            if r<0 or r>=R or c<0 or c>=C or grid[r][c]==0: return 0\n            grid[r][c]=0\n            return 1+dfs(r+1,c)+dfs(r-1,c)+dfs(r,c+1)+dfs(r,c-1)\n        best=0\n        for r in range(R):\n            for c in range(C):\n                best=max(best,dfs(r,c))\n        return best',
    javascript: '    const R=grid.length,C=grid[0].length; function dfs(r,c){if(r<0||r>=R||c<0||c>=C||grid[r][c]===0)return 0;grid[r][c]=0;return 1+dfs(r+1,c)+dfs(r-1,c)+dfs(r,c+1)+dfs(r,c-1);} let best=0; for(let r=0;r<R;r++)for(let c=0;c<C;c++)best=Math.max(best,dfs(r,c)); return best;',
    cpp: '        int R=grid.size(),C=grid[0].size(),best=0; function<int(int,int)> dfs=[&](int r,int c){if(r<0||r>=R||c<0||c>=C||grid[r][c]==0)return 0;grid[r][c]=0;return 1+dfs(r+1,c)+dfs(r-1,c)+dfs(r,c+1)+dfs(r,c-1);}; for(int r=0;r<R;r++)for(int c=0;c<C;c++)best=max(best,dfs(r,c)); return best;',
    java: '        int R=grid.length,C=grid[0].length,best=0; for(int r=0;r<R;r++)for(int c=0;c<C;c++)best=Math.max(best,dfs(grid,r,c)); return best;\n    }\n    int dfs(int[][] grid,int r,int c){int R=grid.length,C=grid[0].length; if(r<0||r>=R||c<0||c>=C||grid[r][c]==0)return 0; grid[r][c]=0; return 1+dfs(grid,r+1,c)+dfs(grid,r-1,c)+dfs(grid,r,c+1)+dfs(grid,r,c-1);',
  },
  'rotting-oranges': {
    python: '        from collections import deque\n        R,C=len(grid),len(grid[0])\n        q=deque(); fresh=0\n        for r in range(R):\n            for c in range(C):\n                if grid[r][c]==2: q.append((r,c))\n                elif grid[r][c]==1: fresh+=1\n        minutes=0\n        dirs=[(1,0),(-1,0),(0,1),(0,-1)]\n        while q and fresh:\n            for _ in range(len(q)):\n                r,c=q.popleft()\n                for dr,dc in dirs:\n                    nr,nc=r+dr,c+dc\n                    if 0<=nr<R and 0<=nc<C and grid[nr][nc]==1:\n                        grid[nr][nc]=2; fresh-=1; q.append((nr,nc))\n            minutes+=1\n        return minutes if fresh==0 else -1',
    javascript: '    const R=grid.length,C=grid[0].length; let q=[],fresh=0; for(let r=0;r<R;r++)for(let c=0;c<C;c++){if(grid[r][c]===2)q.push([r,c]);else if(grid[r][c]===1)fresh++;} let minutes=0; const dirs=[[1,0],[-1,0],[0,1],[0,-1]]; while(q.length&&fresh){const nq=[];for(const cell of q){for(const d of dirs){const nr=cell[0]+d[0],nc=cell[1]+d[1];if(nr>=0&&nr<R&&nc>=0&&nc<C&&grid[nr][nc]===1){grid[nr][nc]=2;fresh--;nq.push([nr,nc]);}}}q=nq;minutes++;} return fresh===0?minutes:-1;',
    cpp: '        int R=grid.size(),C=grid[0].size(); queue<pair<int,int>> q; int fresh=0; for(int r=0;r<R;r++)for(int c=0;c<C;c++){if(grid[r][c]==2)q.push({r,c});else if(grid[r][c]==1)fresh++;} int minutes=0; int dr[]={1,-1,0,0},dc[]={0,0,1,-1}; while(!q.empty()&&fresh){int sz=q.size();for(int i=0;i<sz;i++){auto cur=q.front();q.pop();for(int d=0;d<4;d++){int nr=cur.first+dr[d],nc=cur.second+dc[d];if(nr>=0&&nr<R&&nc>=0&&nc<C&&grid[nr][nc]==1){grid[nr][nc]=2;fresh--;q.push({nr,nc});}}}minutes++;} return fresh==0?minutes:-1;',
    java: '        int R=grid.length,C=grid[0].length; Deque<int[]> q=new ArrayDeque<>(); int fresh=0; for(int r=0;r<R;r++)for(int c=0;c<C;c++){if(grid[r][c]==2)q.add(new int[]{r,c});else if(grid[r][c]==1)fresh++;} int minutes=0; int[] dr={1,-1,0,0},dc={0,0,1,-1}; while(!q.isEmpty()&&fresh>0){int sz=q.size();for(int i=0;i<sz;i++){int[] cur=q.poll();for(int d=0;d<4;d++){int nr=cur[0]+dr[d],nc=cur[1]+dc[d];if(nr>=0&&nr<R&&nc>=0&&nc<C&&grid[nr][nc]==1){grid[nr][nc]=2;fresh--;q.add(new int[]{nr,nc});}}}minutes++;} return fresh==0?minutes:-1;',
  },
  'spiral-matrix': {
    python: '        res=[]\n        top,bottom=0,len(matrix)-1\n        left,right=0,len(matrix[0])-1\n        while top<=bottom and left<=right:\n            for c in range(left,right+1): res.append(matrix[top][c])\n            top+=1\n            for r in range(top,bottom+1): res.append(matrix[r][right])\n            right-=1\n            if top<=bottom:\n                for c in range(right,left-1,-1): res.append(matrix[bottom][c])\n                bottom-=1\n            if left<=right:\n                for r in range(bottom,top-1,-1): res.append(matrix[r][left])\n                left+=1\n        return res',
    javascript: '    const res=[]; let top=0,bottom=matrix.length-1,left=0,right=matrix[0].length-1; while(top<=bottom&&left<=right){for(let c=left;c<=right;c++)res.push(matrix[top][c]);top++;for(let r=top;r<=bottom;r++)res.push(matrix[r][right]);right--;if(top<=bottom){for(let c=right;c>=left;c--)res.push(matrix[bottom][c]);bottom--;}if(left<=right){for(let r=bottom;r>=top;r--)res.push(matrix[r][left]);left++;}} return res;',
    cpp: '        vector<int> res; int top=0,bottom=matrix.size()-1,left=0,right=matrix[0].size()-1; while(top<=bottom&&left<=right){for(int c=left;c<=right;c++)res.push_back(matrix[top][c]);top++;for(int r=top;r<=bottom;r++)res.push_back(matrix[r][right]);right--;if(top<=bottom){for(int c=right;c>=left;c--)res.push_back(matrix[bottom][c]);bottom--;}if(left<=right){for(int r=bottom;r>=top;r--)res.push_back(matrix[r][left]);left++;}} return res;',
    java: '        List<Integer> res=new ArrayList<>(); int top=0,bottom=matrix.length-1,left=0,right=matrix[0].length-1; while(top<=bottom&&left<=right){for(int c=left;c<=right;c++)res.add(matrix[top][c]);top++;for(int r=top;r<=bottom;r++)res.add(matrix[r][right]);right--;if(top<=bottom){for(int c=right;c>=left;c--)res.add(matrix[bottom][c]);bottom--;}if(left<=right){for(int r=bottom;r>=top;r--)res.add(matrix[r][left]);left++;}} return res;',
  },
  'longest-increasing-path-in-a-matrix': {
    python: '        R,C=len(grid),len(grid[0])\n        memo=[[0]*C for _ in range(R)]\n        def dfs(r,c):\n            if memo[r][c]: return memo[r][c]\n            best=1\n            for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n                nr,nc=r+dr,c+dc\n                if 0<=nr<R and 0<=nc<C and grid[nr][nc]>grid[r][c]:\n                    best=max(best,1+dfs(nr,nc))\n            memo[r][c]=best\n            return best\n        return max(dfs(r,c) for r in range(R) for c in range(C))',
    javascript: '    const R=grid.length,C=grid[0].length,memo=[]; for(let i=0;i<R;i++)memo.push(new Array(C).fill(0)); const dirs=[[1,0],[-1,0],[0,1],[0,-1]]; function dfs(r,c){if(memo[r][c])return memo[r][c];let best=1;for(const d of dirs){const nr=r+d[0],nc=c+d[1];if(nr>=0&&nr<R&&nc>=0&&nc<C&&grid[nr][nc]>grid[r][c])best=Math.max(best,1+dfs(nr,nc));}memo[r][c]=best;return best;} let ans=0; for(let r=0;r<R;r++)for(let c=0;c<C;c++)ans=Math.max(ans,dfs(r,c)); return ans;',
    cpp: '        int R=grid.size(),C=grid[0].size(); vector<vector<int>> memo(R,vector<int>(C,0)); int dr[]={1,-1,0,0},dc[]={0,0,1,-1}; function<int(int,int)> dfs=[&](int r,int c)->int{if(memo[r][c])return memo[r][c];int best=1;for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<R&&nc>=0&&nc<C&&grid[nr][nc]>grid[r][c])best=max(best,1+dfs(nr,nc));}memo[r][c]=best;return best;}; int ans=0; for(int r=0;r<R;r++)for(int c=0;c<C;c++)ans=max(ans,dfs(r,c)); return ans;',
    java: '        int R=grid.length,C=grid[0].length; int[][] memo=new int[R][C]; int ans=0; for(int r=0;r<R;r++)for(int c=0;c<C;c++)ans=Math.max(ans,dfs(grid,memo,r,c)); return ans;\n    }\n    int dfs(int[][] g,int[][] memo,int r,int c){if(memo[r][c]!=0)return memo[r][c];int R=g.length,C=g[0].length;int best=1;int[] dr={1,-1,0,0},dc={0,0,1,-1};for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<R&&nc>=0&&nc<C&&g[nr][nc]>g[r][c])best=Math.max(best,1+dfs(g,memo,nr,nc));}memo[r][c]=best;return best;',
  },
  'swim-in-rising-water': {
    python: '        import heapq\n        n=len(grid)\n        seen={(0,0)}\n        heap=[(grid[0][0],0,0)]\n        while heap:\n            t,r,c=heapq.heappop(heap)\n            if r==n-1 and c==n-1: return t\n            for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n                nr,nc=r+dr,c+dc\n                if 0<=nr<n and 0<=nc<n and (nr,nc) not in seen:\n                    seen.add((nr,nc)); heapq.heappush(heap,(max(t,grid[nr][nc]),nr,nc))\n        return grid[0][0]',
    javascript: '    const n=grid.length,seen=[]; for(let i=0;i<n;i++)seen.push(new Array(n).fill(false)); const heap=[[grid[0][0],0,0]]; seen[0][0]=true; const dirs=[[1,0],[-1,0],[0,1],[0,-1]]; while(heap.length){heap.sort((x,y)=>x[0]-y[0]);const top=heap.shift();const t=top[0],r=top[1],c=top[2];if(r===n-1&&c===n-1)return t;for(const d of dirs){const nr=r+d[0],nc=c+d[1];if(nr>=0&&nr<n&&nc>=0&&nc<n&&!seen[nr][nc]){seen[nr][nc]=true;heap.push([Math.max(t,grid[nr][nc]),nr,nc]);}}} return grid[0][0];',
    cpp: '        int n=grid.size(); vector<vector<char>> seen(n,vector<char>(n,0)); priority_queue<array<int,3>,vector<array<int,3>>,greater<array<int,3>>> pq; pq.push({grid[0][0],0,0}); seen[0][0]=1; int dr[]={1,-1,0,0},dc[]={0,0,1,-1}; while(!pq.empty()){auto cur=pq.top();pq.pop();int t=cur[0],r=cur[1],c=cur[2];if(r==n-1&&c==n-1)return t;for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<n&&nc>=0&&nc<n&&!seen[nr][nc]){seen[nr][nc]=1;pq.push({max(t,grid[nr][nc]),nr,nc});}}} return grid[0][0];',
    java: '        int n=grid.length; boolean[][] seen=new boolean[n][n]; PriorityQueue<int[]> pq=new PriorityQueue<>((x,y)->x[0]-y[0]); pq.add(new int[]{grid[0][0],0,0}); seen[0][0]=true; int[] dr={1,-1,0,0},dc={0,0,1,-1}; while(!pq.isEmpty()){int[] cur=pq.poll();int t=cur[0],r=cur[1],c=cur[2];if(r==n-1&&c==n-1)return t;for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<n&&nc>=0&&nc<n&&!seen[nr][nc]){seen[nr][nc]=true;pq.add(new int[]{Math.max(t,grid[nr][nc]),nr,nc});}}} return grid[0][0];',
  },
  'search-a-2d-matrix': {
    python: '        m,n=len(matrix),len(matrix[0])\n        lo,hi=0,m*n-1\n        while lo<=hi:\n            mid=(lo+hi)//2\n            val=matrix[mid//n][mid%n]\n            if val==target: return True\n            if val<target: lo=mid+1\n            else: hi=mid-1\n        return False',
    javascript: '    const m=matrix.length,n=matrix[0].length; let lo=0,hi=m*n-1; while(lo<=hi){const mid=(lo+hi)>>1,val=matrix[Math.floor(mid/n)][mid%n];if(val===target)return true;if(val<target)lo=mid+1;else hi=mid-1;} return false;',
    cpp: '        int m=matrix.size(),n=matrix[0].size(),lo=0,hi=m*n-1; while(lo<=hi){int mid=(lo+hi)/2,val=matrix[mid/n][mid%n];if(val==target)return true;if(val<target)lo=mid+1;else hi=mid-1;} return false;',
    java: '        int m=matrix.length,n=matrix[0].length,lo=0,hi=m*n-1; while(lo<=hi){int mid=(lo+hi)/2,val=matrix[mid/n][mid%n];if(val==target)return true;if(val<target)lo=mid+1;else hi=mid-1;} return false;',
  },
};
module.exports = { SOL };
