// Known-correct solutions for Batch I problems.
const SOL = {
  'valid-sudoku': {
    python: '        rows=[set() for _ in range(9)]\n        cols=[set() for _ in range(9)]\n        boxes=[set() for _ in range(9)]\n        for r in range(9):\n            for c in range(9):\n                v=board[r][c]\n                if v==".": continue\n                b=(r//3)*3+c//3\n                if v in rows[r] or v in cols[c] or v in boxes[b]: return False\n                rows[r].add(v); cols[c].add(v); boxes[b].add(v)\n        return True',
    javascript: "    const rows=[],cols=[],boxes=[]; for(let i=0;i<9;i++){rows.push(new Set());cols.push(new Set());boxes.push(new Set());} for(let r=0;r<9;r++)for(let c=0;c<9;c++){const v=board[r][c]; if(v==='.')continue; const b=((r/3)|0)*3+((c/3)|0); if(rows[r].has(v)||cols[c].has(v)||boxes[b].has(v))return false; rows[r].add(v);cols[c].add(v);boxes[b].add(v);} return true;",
    cpp: "        vector<set<char>> rows(9),cols(9),boxes(9); for(int r=0;r<9;r++)for(int c=0;c<9;c++){char v=board[r][c]; if(v=='.')continue; int b=(r/3)*3+c/3; if(rows[r].count(v)||cols[c].count(v)||boxes[b].count(v))return false; rows[r].insert(v);cols[c].insert(v);boxes[b].insert(v);} return true;",
    java: "        Set<Character>[] rows=new HashSet[9],cols=new HashSet[9],boxes=new HashSet[9]; for(int i=0;i<9;i++){rows[i]=new HashSet<>();cols[i]=new HashSet<>();boxes[i]=new HashSet<>();} for(int r=0;r<9;r++)for(int c=0;c<9;c++){char v=board[r][c]; if(v=='.')continue; int b=(r/3)*3+c/3; if(rows[r].contains(v)||cols[c].contains(v)||boxes[b].contains(v))return false; rows[r].add(v);cols[c].add(v);boxes[b].add(v);} return true;",
  },
  'hand-of-straights': {
    python: '        if len(hand)%k: return False\n        from collections import Counter\n        count=Counter(hand)\n        for v in sorted(count):\n            c=count[v]\n            if c>0:\n                for i in range(v,v+k):\n                    if count[i]<c: return False\n                    count[i]-=c\n        return True',
    javascript: '    if(hand.length%k)return false; const cnt={}; hand.forEach(x=>cnt[x]=(cnt[x]||0)+1); const keys=Object.keys(cnt).map(Number).sort((a,b)=>a-b); for(const v of keys){const c=cnt[v]; if(c>0){for(let i=v;i<v+k;i++){if((cnt[i]||0)<c)return false; cnt[i]-=c;}}} return true;',
    cpp: '        if(hand.size()%k)return false; map<int,int> cnt; for(int x:hand)cnt[x]++; for(auto& kv:cnt){int v=kv.first,c=cnt[v]; if(c>0){for(int i=v;i<v+k;i++){if(cnt[i]<c)return false; cnt[i]-=c;}}} return true;',
    java: '        if(hand.length%k!=0)return false; TreeMap<Integer,Integer> cnt=new TreeMap<>(); for(int x:hand)cnt.merge(x,1,Integer::sum); for(int v:new ArrayList<>(cnt.keySet())){int c=cnt.getOrDefault(v,0); if(c>0){for(int i=v;i<v+k;i++){if(cnt.getOrDefault(i,0)<c)return false; cnt.put(i,cnt.get(i)-c);}}} return true;',
  },
  'interleaving-string': {
    python: '        m,n=len(s1),len(s2)\n        if m+n!=len(s3): return False\n        dp=[[False]*(n+1) for _ in range(m+1)]\n        dp[0][0]=True\n        for i in range(m+1):\n            for j in range(n+1):\n                if i>0 and s1[i-1]==s3[i+j-1] and dp[i-1][j]: dp[i][j]=True\n                if j>0 and s2[j-1]==s3[i+j-1] and dp[i][j-1]: dp[i][j]=True\n        return dp[m][n]',
    javascript: '    const m=s1.length,n=s2.length; if(m+n!==s3.length)return false; const dp=[]; for(let i=0;i<=m;i++)dp.push(new Array(n+1).fill(false)); dp[0][0]=true; for(let i=0;i<=m;i++)for(let j=0;j<=n;j++){if(i>0&&s1[i-1]===s3[i+j-1]&&dp[i-1][j])dp[i][j]=true;if(j>0&&s2[j-1]===s3[i+j-1]&&dp[i][j-1])dp[i][j]=true;} return dp[m][n];',
    cpp: '        int m=s1.size(),n=s2.size(); if(m+n!=(int)s3.size())return false; vector<vector<char>> dp(m+1,vector<char>(n+1,0)); dp[0][0]=1; for(int i=0;i<=m;i++)for(int j=0;j<=n;j++){if(i>0&&s1[i-1]==s3[i+j-1]&&dp[i-1][j])dp[i][j]=1;if(j>0&&s2[j-1]==s3[i+j-1]&&dp[i][j-1])dp[i][j]=1;} return dp[m][n];',
    java: '        int m=s1.length(),n=s2.length(); if(m+n!=s3.length())return false; boolean[][] dp=new boolean[m+1][n+1]; dp[0][0]=true; for(int i=0;i<=m;i++)for(int j=0;j<=n;j++){if(i>0&&s1.charAt(i-1)==s3.charAt(i+j-1)&&dp[i-1][j])dp[i][j]=true;if(j>0&&s2.charAt(j-1)==s3.charAt(i+j-1)&&dp[i][j-1])dp[i][j]=true;} return dp[m][n];',
  },
  'word-search': {
    python: '        R,C=len(board),len(board[0])\n        def dfs(r,c,k):\n            if k==len(word): return True\n            if r<0 or r>=R or c<0 or c>=C or board[r][c]!=word[k]: return False\n            tmp=board[r][c]; board[r][c]="#"\n            found=dfs(r+1,c,k+1) or dfs(r-1,c,k+1) or dfs(r,c+1,k+1) or dfs(r,c-1,k+1)\n            board[r][c]=tmp\n            return found\n        for r in range(R):\n            for c in range(C):\n                if dfs(r,c,0): return True\n        return False',
    javascript: "    const R=board.length,C=board[0].length; function dfs(r,c,k){if(k===word.length)return true;if(r<0||r>=R||c<0||c>=C||board[r][c]!==word[k])return false;const tmp=board[r][c];board[r][c]='#';const found=dfs(r+1,c,k+1)||dfs(r-1,c,k+1)||dfs(r,c+1,k+1)||dfs(r,c-1,k+1);board[r][c]=tmp;return found;} for(let r=0;r<R;r++)for(let c=0;c<C;c++)if(dfs(r,c,0))return true; return false;",
    cpp: "        int R=board.size(),C=board[0].size(); function<bool(int,int,int)> dfs=[&](int r,int c,int k)->bool{if(k==(int)word.size())return true;if(r<0||r>=R||c<0||c>=C||board[r][c]!=word[k])return false;char tmp=board[r][c];board[r][c]='#';bool found=dfs(r+1,c,k+1)||dfs(r-1,c,k+1)||dfs(r,c+1,k+1)||dfs(r,c-1,k+1);board[r][c]=tmp;return found;}; for(int r=0;r<R;r++)for(int c=0;c<C;c++)if(dfs(r,c,0))return true; return false;",
    java: "        int R=board.length,C=board[0].length; for(int r=0;r<R;r++)for(int c=0;c<C;c++)if(dfs(board,word,r,c,0))return true; return false;\n    }\n    boolean dfs(char[][] board,String word,int r,int c,int k){int R=board.length,C=board[0].length; if(k==word.length())return true; if(r<0||r>=R||c<0||c>=C||board[r][c]!=word.charAt(k))return false; char tmp=board[r][c];board[r][c]='#'; boolean found=dfs(board,word,r+1,c,k+1)||dfs(board,word,r-1,c,k+1)||dfs(board,word,r,c+1,k+1)||dfs(board,word,r,c-1,k+1); board[r][c]=tmp; return found;",
  },
  'task-scheduler': {
    python: '        cnt={}\n        for ch in s: cnt[ch]=cnt.get(ch,0)+1\n        maxf=max(cnt.values())\n        maxc=sum(1 for f in cnt.values() if f==maxf)\n        return max(len(s), (maxf-1)*(k+1)+maxc)',
    javascript: '    const cnt={}; for(const ch of s)cnt[ch]=(cnt[ch]||0)+1; let maxf=0; for(const kk in cnt)maxf=Math.max(maxf,cnt[kk]); let maxc=0; for(const kk in cnt)if(cnt[kk]===maxf)maxc++; return Math.max(s.length,(maxf-1)*(k+1)+maxc);',
    cpp: '        map<char,int> cnt; for(char ch:s)cnt[ch]++; int maxf=0; for(auto& kv:cnt)maxf=max(maxf,kv.second); int maxc=0; for(auto& kv:cnt)if(kv.second==maxf)maxc++; return max((int)s.size(),(maxf-1)*(k+1)+maxc);',
    java: '        Map<Character,Integer> cnt=new HashMap<>(); for(char ch:s.toCharArray())cnt.merge(ch,1,Integer::sum); int maxf=0; for(int f:cnt.values())maxf=Math.max(maxf,f); int maxc=0; for(int f:cnt.values())if(f==maxf)maxc++; return Math.max(s.length(),(maxf-1)*(k+1)+maxc);',
  },
};
module.exports = { SOL };
